### ISSUE TITLE
Some critical errors on standard output instead of standard error

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#1939] opened 2017-01-18 12:24 UTC
##### Steps to reproduce the problem:

I'm parsing output of mitmdump in Objective-C and some major errors appears on standard output.

Example:
"Insufficient privileges to access pfctl. " (osx.py:34 - Treated with raise RuntimeError)
-> This appears on standard output, although it's a critical error on a configuration point of view

Instead, example of a correct error output:
"Error starting proxy server: OSError(48, 'Address already in use')" (server.py:51 - Treated with raise exceptions.ServerException)
-> This "correctly" appears on standard error

##### Any other comments? What have you tried so far?

This is just an example, there may be other critical errors which should be treated on standard error

##### System information

Mitmproxy version: 1.0.2
Python version: 3.5.2
Platform: Darwin-16.3.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.2 ('', '', '') x86_64

**Comment by mhils** [comment] 2017-01-18 16:24
I think the root cause for this is here: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/termlog.py

I'd be happy to accept a PR that modifies the default argument to `None` and then uses either `sys.stdout` or `sys.stderr` depending on the log level.

**Comment by Kriechi** [comment] 2017-01-25 16:52
fixed by #1952

**Closed by Kriechi** 2017-01-25 16:52 UTC
Labels: area/addons, kind/enhancement
