### ISSUE TITLE
mitmproxy crashes with error Too many open files

### ISSUE THREAD

**Issue by sunnyandsnow** [mitmproxy/mitmproxy#4966] opened 2021-12-01 09:18 UTC
Hi,

After a while working with mitmproxy it crashes with the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/master.py", line 54, in run_loop
  File "/usr/local/lib/python3.8/dist-packages/urwid/main_loop.py", line 287, in run
  File "/usr/local/lib/python3.8/dist-packages/urwid/main_loop.py", line 385, in _run
  File "/usr/local/lib/python3.8/dist-packages/urwid/main_loop.py", line 1494, in run
  File "/usr/local/lib/python3.8/dist-packages/urwid/compat.py", line 58, in reraise
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 164, in _accept_connection
  File "/usr/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files

mitmproxy has crashed!

I was just running mitmproxy with the parameter -m for redirecting to another proxy
Like this: mitmproxy  -p incoming -m upstream:http://127.0.0.1:1234 -k --anticache

I have experienced this multiple times now. Thinking it is related to #4933 ?

mitmproxy --version
Mitmproxy: 7.0.2
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.4.0-31-generic-x86_64-with-glibc2.29

**Comment by youkai95** [comment] 2021-12-03 07:51
Have you ran `ulimit` command and ensure that your `open files` limit is longer enough for your service?

**Comment by sunnyandsnow** [comment] 2021-12-03 14:48
You are probably right. Have to increase the soft limit perhaps? Just 1024

**Comment by youkai95** [comment] 2021-12-03 20:48
You should try rising the limit and check if that solves the problem, perhaps in the issue you mentioned that limit was not the problem so there is still a doubt about if it is a mitm issue or it is related to another service running on that server.

**Comment by tacerus** [comment] 2021-12-07 21:30
Hello,

I compiled `mitmproxy` from the v7.0.4 source tarball and encounter this issue upon trying to reach a `mitmweb` instance while `ulimit` reports `unlimited`. This is experienced on a freshly installed, minimal, OpenSUSE VM which does not house any other services. The console `mitmproxy` application seems to work fine.

Would appreciate any ideas.

**Comment by mhils** [comment] 2022-01-15 16:09
Closing this as a duplicate of #4933.

**Closed by mhils** 2022-01-15 16:09 UTC
Labels: kind/triage
