### ISSUE TITLE
mitmweb 8.1.1, macOS 12.2.1: "Address already in use" error on start when no process is listening on that port

### ISSUE THREAD

**Issue by jcollum-nutrien** [mitmproxy/mitmproxy#5492] opened 2022-07-26 19:43 UTC
#### Problem Description

Installed with `brew` about 20 minutes ago (26 Jul 22). 

```
~ mitmweb -p 9000

Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmweb", line 33, in <module>
    sys.exit(load_entry_point('mitmproxy==8.1.1', 'console_scripts', 'mitmweb')())
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 144, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 114, in run
    return asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 111, in main
    await master.run()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/master.py", line 48, in run
    await self.running()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/web/master.py", line 83, in running
    http_server.listen(self.options.web_port, self.options.web_host)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
```

Someone is listening on 9000? I don't think they are. OK I'll run my `findbyport` function: 

```
findbyport () { lsof -i4TCP:$1 -sTCP:LISTEN -t || echo "(no process listening at $1)"; }
```

Result: 

```
~ findbyport 9000
(no process listening at 9000)
```

Same result if I just run `mitmweb`. Is there some configuration that I have to perform first? I didn't see anything in the instructions about it. 

#### System Information

```
 ~ mitmproxy --version
Mitmproxy: 8.1.1
Python:    3.10.5
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.2.1-arm64-arm-64bit
```

**Comment by jcollum-nutrien** [comment] 2022-07-26 23:19
`mitmweb --listen-host 127.0.0.1 --listen-port 9999` this didn't work either, same result

**Comment by Prinzhorn** [comment] 2022-07-27 08:09
mitmweb also starts a web server for the UI, see `--web-port` (the stack trace also points to `tornado`). I'll mark this as UX, because maybe the error message could include the port if that's feasible.

**Comment by Prinzhorn** [comment] 2022-07-27 08:10
Is there a reason for opening a second issue? It seems like you already suggested improving the error message in #5491 and there's already a PR. Closing as duplicate of #5491

**Closed by Prinzhorn** 2022-07-27 08:10 UTC
Labels: kind/triage

**Comment by jcollum-nutrien** [comment] 2022-07-27 17:23
Please reopen. There is an error when the `mitmweb` app starts up, see above. A coworker did the same instructions and ran into the same issue.  

The other ticket was about giving back a better error code.

**Comment by Prinzhorn** [comment] 2022-07-27 17:25
` --web-port` did not help?

**Comment by jcollum-nutrien** [comment] 2022-07-27 17:31
Actually yeah that worked. The app doesn't have a default port? 

```
✗ mitmweb
Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmweb", line 33, in <module>
    sys.exit(load_entry_point('mitmproxy==8.1.1', 'console_scripts', 'mitmweb')())
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 144, in mitmweb
    run(web.master.WebMaster, cmdline.mitmweb, args)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 114, in run
    return asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 111, in main
    await master.run()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/master.py", line 48, in run
    await self.running()
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/mitmproxy/tools/web/master.py", line 83, in running
    http_server.listen(self.options.web_port, self.options.web_host)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/homebrew/Cellar/mitmproxy/8.1.1/libexec/lib/python3.10/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use

✗ mitmweb --web-port 9999
Web server listening at http://127.0.0.1:9999/
Proxy server listening at *:8080
```

The solution here would be to add a default port or change the instructions. I'm surprised I'm the first person to run into this. Like I said, coworker hit the same issue.

**Comment by Prinzhorn** [comment] 2022-07-27 18:03
> The app doesn't have a default port?

It does, see `mitmweb --options`. What does `findbyport 8081` yield?

**Comment by jcollum-nutrien** [comment] 2022-07-27 18:09
```✗ findbyport 8081
(no process listening at 8081)```

**Comment by Prinzhorn** [comment] 2022-07-28 06:56
That is odd, assuming `findbyport` works as intended. You're basically saying that for you and your co-worker mitmweb cannot listen on `8081` (which is allegedly free) but other ports such as `9999` work? If that is truly the case then something with your machines might be broken, because that doesn't make sense to me. But I'm ready to be surprised. I don't have access to a mac and I doubt anyone can reproduce this.

Can other tools listen on `80881`? Can you please try the following:

1. Try to start `mitmweb --web-port 8081` and make sure it fails and the process exists. Now we know the port is somehow broken.
2. Try starting a different process, e.g. `ncat -l 8081` or `python3 -m http.server 8081`. If that fails too, it's not a mitmproxy issue.

**Comment by Cruzalexandar** [comment] 2023-09-01 13:59
I have the same issue please is there a solution
