### ISSUE TITLE
Invalid server scheme: socks5

### ISSUE THREAD

**Issue by salisbury-espinosa** [mitmproxy/mitmproxy#4098] opened 2020-07-22 08:37 UTC
https://docs.mitmproxy.org/stable/concepts-options/

![Screenshot from 2020-07-22 11-36-29](https://user-images.githubusercontent.com/18151481/88154544-ad29e080-cc0f-11ea-980a-d22298dd0d0f.png)

test:
mitmdump --listen-port 8083 --mode upstream:socks5://127.0.0.1:7000 --ssl-insecure  --set termlog_verbosity=error
failed:
mitmdump: Invalid server scheme: socks5

#### System Information
mitmdump --version
Mitmproxy: 5.1.1
Python:    3.7.4
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.0.0-38-generic-x86_64-with-debian-buster-sid

**Comment by mhils** [comment] 2020-07-22 08:41
Closing this as a duplicate of #211.

The second part of the sentence you quoted explicitly states that the upstream spec must start with "http[s]".

**Closed by mhils** 2020-07-22 08:41 UTC
Labels: kind/triage
