### ISSUE TITLE
Transparent mode failure: File not found in Docker container

### ISSUE THREAD

**Issue by LaumiH** [mitmproxy/mitmproxy#3799] opened 2020-01-27 09:35 UTC
#### Problem Description
I have mitmproxy running inside a docker container, entrypoint is mitmdump, and I want to execute the unmodified `send_reply_from_proxy.py`.
The container starts correctly, but when I send a http message through it I get `Transparent mode failure: FileNotFoundError(2, 'No such file or directory')`.

I am aware of #3236, but it did not solve my issue.

#### Steps to reproduce the behavior:
1. Create a Docker container as follows:
```
FROM mitmproxy/mitmproxy:latest

RUN mkdir test
WORKDIR /home/$USER/test
COPY ./script.py .

EXPOSE 80:80
EXPOSE 8080:8080

ENTRYPOINT ["/usr/bin/mitmdump", "--mode", "transparent", "-s", "./script.py"]
```
2. Build it with `docker build . -t mitmdump`
3. Run it with `docker run -it mitmdump`. I also tried with `--network=host` option, no change
4. Execute `https_proxy=http://localhost:8080/ curl -k https://example.com/`
5. There is a `clientconnect`, and then the error message.

#### System Information
Docker image is :latest.
Docker version 19.03.5-ce, build 633a0ea838.
I am running it on Linux 5.4.13-3-MANJARO.

**Comment by LaumiH** [comment] 2020-01-27 14:15
Update: Option `-v` in mitmdump gives me nothing new.

**Comment by mhils** [comment] 2020-01-27 21:50
Thanks for the report! This is a duplicate of #3236, closing this here. :smiley:

**Closed by mhils** 2020-01-27 21:50 UTC
Labels: kind/triage
