### ISSUE TITLE
Intermittent test exception: http2

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1193] opened 2016-06-02 05:10 UTC
##### Steps to reproduce the problem:

1. Rebuild on travis

##### What is the expected behavior?

No errors!

##### What went wrong?

Very occasionally, we observe this exception in test output, though no tests fail:

```
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/travis/build/mitmproxy/mitmproxy/mitmproxy/protocol/http2.py", line 445, in run
    self()
  File "/Users/travis/build/mitmproxy/mitmproxy/mitmproxy/protocol/http2.py", line 451, in __call__
    layer()
  File "/Users/travis/build/mitmproxy/mitmproxy/mitmproxy/protocol/http.py", line 185, in __call__
    flow = self.channel.ask("response", flow)
  File "/Users/travis/build/mitmproxy/mitmproxy/mitmproxy/controller.py", line 137, in ask
    raise exceptions.Kill()
Kill: None
```

##### Any other comments? What have you tried so far?

---

Mitmproxy Version: -master
Operating System: I see this in the xdcode travis builds

**Comment by Kriechi** [comment] 2016-07-11 18:56
Seems similar to #1284 - only this affects the request instead of the response.

**Comment by cortesi** [comment] 2016-07-18 11:21
It's worth adding a wee bit of information from the ticket you've just closed. I haven't seen this on travis for a long, long time. The only place I see this now is on my development workstation. It's reproducible (but not very reliably) by firing up mitmproxy, pumping http2 traffic through it, and then exiting. The trace seems to occur on exit, not during normal operation. 

```
Python version: 3.5.1
Platform: Darwin-15.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2h 3 May 2016
Mac version: 10.11.5 ('', '', '') x86_64
```

**Comment by mhils** [comment] 2016-07-23 00:35
Closing this as a duplicate of #1395, which has a consistent way to reproduce it!

**Closed by mhils** 2016-07-23 00:35 UTC
Labels: bug
