### ISSUE TITLE
--set spoof_source_address does not work with -s switch

### ISSUE THREAD

**Issue by samiux** [mitmproxy/mitmproxy#3042] opened 2018-04-05 02:22 UTC
The mitmproxy version is 3.0.3

The python version is 3.6

The iptable rule :

sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --match multiport --dport 80,443 -j REDIRECT --to-port 8080

The command to run :

mitmdump -p 8080 -s /etc/myscript/myscript.py -m transparent -q -k --certs *.mysite.com=/etc/mycert/mysite.pem --set spoof_source_address=true

The result :

502 Bad Gateway

ProtocolException('Server connection to (\'192.168.20.100\', 443) failed: Error connecting to "192.168.20.100": [Errno 99] Cannot assign requested address',)

Any idea?

**Comment by mhils** [comment] 2018-04-05 11:43
Hi,

This looks like a duplicate of https://github.com/mitmproxy/mitmproxy/issues/3019.

**Closed by mhils** 2018-04-05 11:43 UTC

**Comment by samiux** [comment] 2018-04-06 03:48
When "spoof_source_address" is used alone, it will crash with the captioned error.  

When "spoof_source_address" used with "upstream_bind_address" and "upstream_bind_address" not blank, it will running smoothly.

If "upstream_bind_address" is blanked with "spoof_source_address", it will also crash with the captioned error.

Can "spoof_source_address" work alone?  In my understanding, "spoof_source_address" will show the original source client IP address.  Am I right?
