### ISSUE TITLE
mitmproxy -m -socks5 

### ISSUE THREAD

**Issue by Thanhdn1984** [mitmproxy/mitmproxy#4792] opened 2021-09-06 08:15 UTC
File "mitmproxy\master.py", line 54, in run_loop
  File "urwid\main_loop.py", line 287, in run
  File "urwid\main_loop.py", line 385, in _run
  File "urwid\main_loop.py", line 1494, in run
  File "urwid\compat.py", line 58, in reraise
  File "mitmproxy\addons\proxyserver.py", line 154, in refresh_server
  File "asyncio\streams.py", line 94, in start_server
  File "asyncio\base_events.py", line 1494, in create_server
OSError: [Errno 10013] error while attempting to bind on address ('0.0.0.0', 8080): an attempt was made to access a socket in a way forbidden by its access permissions

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues

**Comment by mhils** [comment] 2021-09-13 07:31
Duplicate of #4796

**Closed by mhils** 2021-09-13 07:31 UTC
Labels: kind/triage
