### ISSUE TITLE
Modify headers and HTTP/2 lead to protocol error (stream reset by client)

### ISSUE THREAD

**Issue by Tensho** [mitmproxy/mitmproxy#4793] opened 2021-09-06 13:57 UTC
#### Problem Description

For some reason simple HTTP header modification doesn't work with HTTP/2 protocol. Everything is fine without `--modify-headers` or with `--no-http2` option.

#### Steps to reproduce the behavior:

1. [Tab 1] Run `mitmproxy --modify-headers`:
```
SSLKEYLOGFILE="$PWD/.mitmproxy/sslkeylogfile.txt" mitmproxy --modify-headers "/~q/X-Custom-Header/Custom-Value"
```
2. [Tab 2] Configure clients to use proxy:
```
export HTTPS_PROXY=https://localhost:8080
```
3. [Tab 2] Make request from client:
```
curl https://google.com
<html>
<head>
    <title>502 Bad Gateway</title>
</head>
<body>
    <h1>502 Bad Gateway</h1>
    <p>stream reset by client (PROTOCOL_ERROR)</p>
</body>
</html>%
```

<img width="1920" alt="Screenshot 2021-09-06 at 16 37 04" src="https://user-images.githubusercontent.com/892721/132228069-c9673dfc-05e3-44e2-b233-359884d16f06.png">
<img width="1920" alt="Screenshot 2021-09-06 at 16 37 15" src="https://user-images.githubusercontent.com/892721/132228073-57e9afeb-cca8-4554-af15-706f603ed3a9.png">
<img width="1920" alt="Screenshot 2021-09-06 at 16 42 20" src="https://user-images.githubusercontent.com/892721/132228076-db419789-3411-4ea8-b040-b093ba82ffaf.png">
<img width="1912" alt="Screenshot 2021-09-06 at 16 42 31" src="https://user-images.githubusercontent.com/892721/132228079-4ace44a1-8db0-488e-a7b8-25dc0a769750.png">

JFYI, I can send Wireshark capture file.

#### System Information

```
$ mitmproxy --version
Mitmproxy: 7.0.2
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.3-x86_64-i386-64bit
```

**Comment by mhils** [comment] 2021-09-06 13:59
Is this perhaps a duplicate of #4746?

**Comment by Tensho** [comment] 2021-09-06 14:04
@mhils It does. Thank you for referencing. With lower-case everything works fine.

**Comment by mhils** [comment] 2021-09-06 14:05
Good stuff. Thank you for the excellent writeup anyhow, looks like we need to get this fixed ASAP :)

**Closed** 2021-09-06 14:04 UTC
Labels: kind/triage

**Comment by 89z** [comment] 2022-04-25 19:16
Just ran into this as well. Looks like the resolution commit didn't hit until version 8, and I was still on 7.0.4.

Upgrading seems to fix the problem. Thank you!
