### ISSUE TITLE
mitmproxy has crashed when tried to copy a response.

### ISSUE THREAD

**Issue by tatiana-fox** [mitmproxy/mitmproxy#4883] opened 2021-10-27 21:41 UTC
#### Problem Description
mitmproxy has crashed when tried to copy a response.

#### Steps to reproduce the behavior:
1. Sniff a traffic.
2.  Focus on a request -> Ctrl l
3. Input cut.clip @focus response.raw_content -> Enter

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6-x86_64-i386-64bi
[Untitled.txt](https://github.com/mitmproxy/mitmproxy/files/7429435/Untitled.txt)
t

**Comment by Prinzhorn** [comment] 2021-11-01 08:24
Thanks for reporting, this is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/3965 with the exact same error message

**Closed by Prinzhorn** 2021-11-01 08:24 UTC
Labels: kind/triage
