### ISSUE TITLE
Anticache is not set with config.yaml

### ISSUE THREAD

**Issue by andrefreitas** [mitmproxy/mitmproxy#2073] opened 2017-02-27 14:54 UTC
##### Steps to reproduce the problem:

1. Edit ~/.mitmproxy/config.yaml
2. Set `anticache: true`
3. Run with `mitmproxy`

##### Any other comments? What have you tried so far?
I tried with `True` and `true`. It only works if I set --anticache as a command line option. Others params such web_port are correctly set from the config file.

##### System information

```
Mitmproxy version: 2.0.0 (release version)
Python version: 3.6.0
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.1 ('', '', '') x86_64
```

**Comment by mhils** [comment] 2017-02-27 16:31
Thanks for the report. Duplicate of #1899?

**Comment by andrefreitas** [comment] 2017-02-27 16:34
Hi, maybe is a duplicated yes. Just by solving the other issue we will know :)

**Comment by mhils** [comment] 2017-02-27 18:27
Pretty sure it is - I'll close this here, we'll look at this when closing #1899.

**Closed by mhils** 2017-02-27 18:27 UTC
