### ISSUE TITLE
Crash when resizing (OS X, 0.11.4)

### ISSUE THREAD

**Issue by zbuc** [mitmproxy/mitmproxy#497] opened 2015-03-04 04:25 UTC
I had mitmproxy in a small terminal window, then double clicked the terminal window to maximize and it crashed when attempting to redraw.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/console/__init__.py", line 628, in run
    self.ui.run_wrapper(self.loop)
  File "/Library/Python/2.7/site-packages/urwid/display_common.py", line 757, in run_wrapper
    return fn()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/console/__init__.py", line 854, in loop
    self.statusbar.message("")
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/console/__init__.py", line 253, in message
    self.master.drawscreen()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mitmproxy-0.11.4-py2.7.egg/libmproxy/console/__init__.py", line 799, in drawscreen
    self.ui.draw_screen(size, canvas)
  File "/Library/Python/2.7/site-packages/urwid/raw_display.py", line 749, in draw_screen
    if osb and osb[y] == row:
IndexError: list index out of range
```

I'm having trouble reproducing, but filing the bug with the stack trace in case you see an obvious reason this can happen.

**Comment by mhils** [comment] 2015-03-04 05:00
Looks like a duplicate of https://github.com/wardi/urwid/issues/96.

**Closed by mhils** 2015-03-04 05:00 UTC

**Comment by mhils** [comment] 2015-03-04 05:01
Forgot to mention: Thanks for the report of course! :-)
