### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode characters

### ISSUE THREAD

**Issue by SydoQQ** [mitmproxy/mitmproxy#4217] opened 2020-10-02 14:21 UTC
#### Problem Description

Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 250, in error
    self.echo_flow(f)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 218, in echo_flow
    self._echo_request_line(f)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 166, in _echo_request_line
    self.echo(line)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 70, in echo
    click.secho(text, file=self.outfp, **style)
  File "/usr/local/lib/python3.6/site-packages/click/termui.py", line 548, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 111-112: surrogates not allowed

#### Steps to reproduce the behavior:
1. mitmproxy crashed and exit app

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 5.1.1
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core

App started:
mitmdump --ssl-insecure --mode transparent --showhost

**Comment by Prinzhorn** [comment] 2020-10-05 13:14
1. Does this happen with the latest version as well (5.2)?
2. How can we reproduce this? Does ` mitmdump --ssl-insecure --mode transparent --showhost` crash immediately for you or are there more steps involved? Do we have to visit a specific website?

**Comment by SydoQQ** [comment] 2020-10-07 09:35
Upgrade version mitm:

Mitmproxy: 5.2
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core

Error:

Addon error: Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 250, in error
    self.echo_flow(f)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 218, in echo_flow
    self._echo_request_line(f)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 166, in _echo_request_line
    self.echo(line)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/mitmproxy/addons/dumper.py", line 70, in echo
    click.secho(text, file=self.outfp, **style)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/termui.py", line 548, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 111-112: surrogates not allowed

I'm send custom request contains cyrilic symbol
Example:
"https://test.com/test/download.php?s=ппп"

**Comment by Prinzhorn** [comment] 2020-10-07 10:15
> I'm send custom request contains cyrilic symbol

What HTTP client are you using? At least in regular mode I cannot reproduce it. Even with ncat and literally using the cyrilic symbols (explicitly without URL encoding). I haven't set up transparent mode, so maybe it only happens there (I don't think so).

But it looks like this is a duplicate of #4070

```sh
echo -e 'GET http://www.example.com/test/download.php?s=ппп HTTP/1.1\r\nHost: www.example.com\r\n\r\n' | ncat localhost 8080
```

![Selection_677](https://user-images.githubusercontent.com/679144/95317299-48d4ff80-0895-11eb-9f5c-88a6fde6340e.png)
![Selection_678](https://user-images.githubusercontent.com/679144/95317304-4a9ec300-0895-11eb-9aba-a97e27d3a35a.png)

**Comment by SydoQQ** [comment] 2020-10-07 13:35
I'm using windows JScript code

var ie2 = new ActiveXObject("InternetExplorer.Application");
ie2.Navigate(""https://test.com/test/download.php?s=ппп"");

**Comment by Prinzhorn** [comment] 2020-12-22 11:55
I'm closing this in favor of #4070, I think this was a duplicate

**Closed by Prinzhorn** 2020-12-22 11:55 UTC
Labels: kind/triage
