### ISSUE TITLE
Error in WebSocket connection

### ISSUE THREAD

**Issue by frida42** [mitmproxy/mitmproxy#4281] opened 2020-11-06 17:47 UTC
#### Problem Description
I've used mitmproxy locally to watch Instagram traffic on desktop browser in real time and got this "Error in WebSocket connection ...".

#### Steps to reproduce the behavior:
1. Run command `mitmproxy --listen-port 8083 -q`
2. Try to go to URL https://instagram.com/
3. Observe errors:
```
Error in WebSocket connection to edge-chat.instagram.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None)
Error in WebSocket connection to edge-chat.instagram.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None)
Error in WebSocket connection to edge-chat.instagram.com:443: WebSocket connection closed unexpectedly by client: TcpDisconnect(None)
```

#### System Information
```
Mitmproxy: 5.3.0
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.19.0-12-amd64-x86_64-with-debian-10.6
Browser: Mozilla Firefox 78.4.0esr
```

Possible workaround is to enable `--ignore-hosts '^edge-chat.instagram.com:' ` option

I also tested it in Burp Suite proxy (instead of mitmproxy) and it's working normal
![image](https://user-images.githubusercontent.com/72792688/98402637-b3d24b80-2078-11eb-8598-e9f919d6adea.png)

**Comment by Kriechi** [comment] 2020-11-07 09:52
I'm not able to reproduce this on the plain instagram.com home page - are you signed in to an account?

**Comment by CITIZENDOT** [comment] 2020-11-08 11:52
It is working fine, Firefox has different certificates, Did you import them?

**Comment by frida42** [comment] 2020-11-09 17:11
@Kriechi Yes, I was signed into instagram. I recorded this bug, please see https://vimeo.com/477230835

**Comment by Prinzhorn** [comment] 2020-11-10 07:52
In your original report you were using `mitmproxy` not `mitmdump`. Now I can only guess that what you want to be fixed is that `--quiet` should be respected? Or are you seeing issues on an application level?

**Comment by Prinzhorn** [comment] 2020-11-13 08:21
Please ignore my message above. `--quiet` never prevented stderr and I actually depend on that behavior :smile:

**Comment by Kriechi** [comment] 2020-12-18 21:17
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.

**Closed by Kriechi** 2020-12-18 21:17 UTC
Labels: kind/triage
