### ISSUE TITLE
Throttle a domain using mitmdump

### ISSUE THREAD

**Issue by StephanieCherian** [mitmproxy/mitmproxy#4264] opened 2020-11-02 10:26 UTC
I want to throttle a particular domain at 1Mbps,2Mbps,5Mbps and 10Mbps when running mitmdump in transparent mode

**Comment by Prinzhorn** [comment] 2022-08-01 16:22
I'm closing this in favor of #4264 (which should've been a duplicate of this one), which is newer but has been more active

**Closed by Prinzhorn** 2022-08-01 16:22 UTC
Labels: kind/feature

**Comment by ericbeland** [comment] 2022-08-02 03:11
Isn't **this** issue you closed #4264?  Was the wrong number was pasted?

**Comment by Prinzhorn** [comment] 2022-08-02 06:44
Updated
