### ISSUE TITLE
pathod HTTP/1.0 support and custom new line (0x0A)

### ISSUE THREAD

**Issue by fieryo** [mitmproxy/mitmproxy#2023] opened 2017-02-14 13:08 UTC
I tested pathod 1.0.2 trying to simulate a web server that responds with a HTTP/1.0 protocol and has only 0x0A as new lines. I almost succeeded with "200:r:da" (to close the connection) and some custom headers, but I can't change the new lines to LF and the protocol from HTTP/1.1 to HTTP/1.0. It would be great if I can put the entire response+content in a binary file, tell pathod to disconnect at the end and load something like this: 
http://localhost:9999/p/rf=response_file:da

Would you please add these options in pathod.

Here is the server response which I try to replicate:
```
HTTP/1.0 200 OK
Content-type: application/octet-stream
Connection: close
Cache-Control: no-cache
```

**Comment by Kriechi** [comment] 2018-03-06 21:09
The newline part of this issues could be considered a duplicate of #944.

**Comment by Kriechi** [comment] 2020-12-13 11:34
Closing, as pathod and pathoc command line tools and their libraries inside mitmproxy are deprecated. See #4273.

**Closed by Kriechi** 2020-12-13 11:34 UTC
Labels: area/pathod, kind/feature
