### ISSUE TITLE
mitmproxy has crashed

### ISSUE THREAD

**Issue by dragonforeverliu** [mitmproxy/mitmproxy#4049] opened 2020-06-29 02:59 UTC
#### Problem Description
test@test-VirtualBox:~$ ./mitmproxy --set block_global=false --ssl-insecure
Traceback (most recent call last):
  File "mitmproxy/master.py", line 86, in run_loop
  File "urwid/main_loop.py", line 287, in run
  File "urwid/main_loop.py", line 385, in _run
  File "urwid/main_loop.py", line 1494, in run
  File "urwid/compat.py", line 58, in reraise
  File "asyncio/events.py", line 88, in _run
  File "urwid/main_loop.py", line 1454, in faux_idle_callback
  File "urwid/main_loop.py", line 574, in entering_idle
  File "urwid/main_loop.py", line 588, in draw_screen
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/container.py", line 1086, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/decoration.py", line 226, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/container.py", line 1086, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/listbox.py", line 457, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/widget.py", line 1761, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/container.py", line 1554, in render
  File "urwid/widget.py", line 145, in cached_render
  File "urwid/container.py", line 2125, in render
  File "urwid/widget.py", line 145, in cached_render
  File "mitmproxy/tools/console/common.py", line 173, in render
  File "urwid/canvas.py", line 358, in __init__
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified 
15
[23]
[b'\xe2\x80\xa6o -3] \xe5\x9f\x9f\xe5\x90\x8d\xe8\xa7\xa3\xe6\x9e\x90\xe6\x9a\x82\xe6\x97\xb6\xe5\xa4\xb1\xe8\xb4\xa5']

mitmproxy has crashed!
Please lodge a bug report at:
 https://github.com/mitmproxy/mitmproxy
test@test-VirtualBox:~$ 

#### Steps to reproduce the behavior:
1. there maybe some non-http inside tls in my test.
2. some https can be dump correctly before crash.

#### System Information
Paste the output of "mitmproxy --version" here.
version 5.1.1
ubuntu 20.04

**Comment by mhils** [comment] 2020-06-29 15:28
Thanks! This looks like a duplicate of #2894.

**Closed by mhils** 2020-06-29 15:28 UTC
Labels: kind/triage
