### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by zhaoyulu** [mitmproxy/mitmproxy#3769] opened 2020-01-02 02:49 UTC
#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
    callback()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 1765, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1523, in render
    canv = w.render((maxcol,), focus=focus and item_focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 2087, in render
    focus = focus and self.focus_position == i)
  File "/usr/local/lib/python3.6/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/tools/console/common.py", line 173, in render
    return urwid.TextCanvas([c_text.encode()], [c_attr], maxcol=width)
  File "/usr/local/lib/python3.6/dist-packages/urwid/canvas.py", line 358, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified 
18
[23]
[b'\xe2\x80\xa6[Errno 101] \xe7\xbd\x91\xe7\xbb\x9c\xe4\xb8\x8d\xe5\x8f\xaf\xe8\xbe\xbe']

**Comment by mhils** [comment] 2020-01-03 11:37
Duplicate of #2894.

**Closed by mhils** 2020-01-03 11:37 UTC
Labels: kind/triage
