### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by Storyyeller** [mitmproxy/mitmproxy#3827] opened 2020-02-24 02:07 UTC
#### Problem Description

Traceback (most recent call last):
  File "mitmproxy/master.py", line 86, in run_loop
  File "site-packages/urwid/main_loop.py", line 286, in run
  File "site-packages/urwid/main_loop.py", line 384, in _run
  File "site-packages/urwid/main_loop.py", line 1484, in run
  File "site-packages/urwid/compat.py", line 58, in reraise
  File "asyncio/events.py", line 88, in _run
  File "site-packages/urwid/main_loop.py", line 1443, in faux_idle_callback
  File "site-packages/urwid/main_loop.py", line 572, in entering_idle
  File "site-packages/urwid/main_loop.py", line 586, in draw_screen
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/container.py", line 1086, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/decoration.py", line 226, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/container.py", line 1086, in render
  File "site-packages/urwid/widget.py", line 144, in cached_render
  File "site-packages/urwid/listbox.py", line 471, in render
  File "site-packages/urwid/listbox.py", line 416, in calculate_visible
  File "mitmproxy/tools/console/flowlist.py", line 68, in get_next
  File "mitmproxy/tools/console/flowlist.py", line 12, in __init__
  File "mitmproxy/tools/console/flowlist.py", line 22, in get_text
  File "mitmproxy/tools/console/common.py", line 561, in format_flow
  File "mitmproxy/tools/console/common.py", line 488, in raw_format_table
ValueError: math domain error

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

#### Steps to reproduce the behavior:
1.  This error happened while trying to use server replay with an edited response body
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.0.1 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.4.0-104-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment] 2020-02-24 17:24
Thanks! This is a duplicate of #3819.

**Closed by mhils** 2020-02-24 17:24 UTC
Labels: kind/triage
