### ISSUE TITLE
Try to edit the flow response Set-Cookie (mitmproxy has crashed!)

### ISSUE THREAD

**Issue by mindcat** [mitmproxy/mitmproxy#1031] opened 2016-03-15 14:01 UTC
1. Open mitmproxy
2. A HTTP flow has Set-Cookie header through mitmproxy
3. Try to edit the flow response Set-Cookie
```
╭─mindcat@mindcat-linux-pc ~  
╰─➤  mitmproxy -p 8888 -s ~/mitmproxy/eleme.py 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 500, in run
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 124, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 80, in keypress
    self.prompt_execute(k)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/statusbar.py", line 105, in prompt_execute
    msg = p(txt, *args)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/flowview.py", line 400, in edit
    message
  File "/usr/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 559, in view_grideditor
    ge.make_help()
  File "/usr/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 291, in sig_push_view_state
    self.loop.draw_screen()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 339, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 704, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 674, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 342, in calculate_visible
    focus_widget, focus_pos = self.body.get_focus()
  File "/usr/lib/python2.7/site-packages/libmproxy/console/grideditor.py", line 292, in get_focus
    self.lst[self.focus]
  File "/usr/lib/python2.7/site-packages/libmproxy/console/grideditor.py", line 140, in __init__
    w = self.editor.columns[i].text(v)
  File "/usr/lib/python2.7/site-packages/libmproxy/console/grideditor.py", line 71, in text
    p = http_cookies._format_pairs(obj, sep="\n")
NameError: global name 'http_cookies' is not defined

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

Mitmproxy Version:
```
╭─mindcat@mindcat-linux-pc ~/workspace/wengdo/20160311  
╰─➤  mitmproxy --version                                                                                                                                          1 ↵
mitmproxy 0.15
```
Operating System:
```
╭─mindcat@mindcat-linux-pc ~/workspace/wengdo/20160311  
╰─➤  LC_ALL=C pacman -Ss mitm
community/mitmproxy 0.16-1 [installed: 0.15-3]
    SSL-capable man-in-the-middle HTTP proxy
community/python2-netlib 0.16-1 [installed: 0.15.1-2]
    A collection of network utilities used by pathod and mitmproxy
community/sslstrip 0.9-7
    Python tool to hijack HTTPS connections during a MITM attack
╭─mindcat@mindcat-linux-pc ~/workspace/wengdo/20160311  
╰─➤  uname -a
Linux mindcat-linux-pc 4.4.1-pf #1 SMP PREEMPT Wed Jan 20 13:21:41 CST 2016 x86_64 GNU/Linux
```

**Comment by mhils** [comment] 2016-03-15 14:04
Thanks for the report. This is a duplicate of #1018, which is already fixed.

**Closed by mhils** 2016-03-15 14:04 UTC

**Comment by mindcat** [comment] 2016-03-15 14:16
ok :D
