### ISSUE TITLE
Mitmproxy received an absolute-form request error

### ISSUE THREAD

**Issue by axot** [mitmproxy/mitmproxy#2079] opened 2017-03-01 06:42 UTC
##### Steps to reproduce the problem:
tcpdump result:
```
CONNECT sample.domain.com:80 HTTP/1.1
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Host: sample.domain.com:80

HTTP/1.1 200 Connection established

POST http://sample.domain.com/ajax/info/info HTTP/1.1
User-Agent: Unity/5.4.3p4 (Mac OS X 10.12.3; MacBookPro12,1)
Host: sample.domain.com
Accept-Encoding: gzip, identity
Proxy-Connection: Keep-Alive
Connection: Keep-Alive, TE
TE: identity
Content-Length: 0
Cookie: apv=1.0; abc=; abd=; abe=

HTTP/1.1 400 Bad Request
Server: mitmproxy 2.0.0
Connection: close
Content-Length: 436
Content-Type: text/html

<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>
            <h1>400 Bad Request</h1>
            <p>HttpException(&#x27;Mitmproxy received an absolute-form request even though it is not running in regular mode. This usually indicates a misconfiguration, please see http://docs.mitmproxy.org/en/stable/modes.html for details.&#x27;,)</p>
            </body>
        </html>HTTP/1.1 502 Bad Gateway
Server: mitmproxy 2.0.0
Connection: close
Content-Length: 479
Content-Type: text/html

<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&#x27;HTTP protocol error in client request: Mitmproxy received an absolute-form request even though it is not running in regular mode. This usually indicates a misconfiguration, please see http://docs.mitmproxy.org/en/stable/modes.html for details.&#x27;,)</p>
            </body>
        </html>
```

##### Any other comments? What have you tried so far?
I fixed this temporarily with
https://github.com/mitmproxy/mitmproxy/blob/83f1e2eec01ab3edec723b252b0c109f00b77c56/mitmproxy/proxy/root_context.py#L100
```diff
- return protocol.Http1Layer(top_layer, http.HTTPMode.transparent)
+ return protocol.Http1Layer(top_layer, http.HTTPMode.regular)
``` 

##### System information

Mitmproxy version: 2.0.0 (release version)
Python version: 3.6.0
Platform: Darwin-16.4.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.3 ('', '', '') x86_64

**Comment by mhils** [comment] 2017-03-01 09:03
Thanks for the extensive report. This seems to be a duplicate of https://github.com/mitmproxy/mitmproxy/issues/848?

**Comment by axot** [comment] 2017-03-01 13:17
Did this meaning, I should change the behaviour to like this way?
```
CONNECT sample.domain.com:80
POST /ajax/info/info HTTP/1.1
```

**Comment by Kriechi** [comment] 2017-03-01 14:05
Yes, this is what most clients do. They send a `CONNECT` with the host they need a connection to, and then they *only* send relative paths.

**Comment by axot** [comment] 2017-03-03 13:13
Should we add an option to disable validate_request_form ?

**Comment by mhils** [comment] 2017-03-03 18:08
So there are two things I'd love to see:

1. First, always accept requests in absolute-form going to the same host. For example, after `CONNECT example.com`, we should accept `GET http://example.com/foo`, but not `GET http://example.org/foo`. This would for example fix this issue.
2. Second, as you suggested, add a `--relax-http-form-validation` switch.

**Comment by mhils** [comment] 2017-03-03 18:09
I copied that to #848, let's continue there :)

**Closed by mhils** 2017-03-03 18:09 UTC
Labels: kind/triage

**Comment by sk3lk0** [comment] 2019-12-18 15:35
--relax-http-form-validation not working
