### ISSUE TITLE
requests library not working while mitm proxy enabled

### ISSUE THREAD

**Issue by mcg88** [mitmproxy/mitmproxy#4572] opened 2021-04-21 17:54 UTC
#### Problem Description
Can't use requests library in script, throws following error:

in script mitm.py: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1034: The handshake operation timed out')))

Any idea how I can resolve this?

**Comment by Prinzhorn** [comment] 2021-04-22 06:30
Please share some code that reproduces the problem, otherwise we can only make guesses.

**Comment by mcg88** [comment] 2021-04-23 14:00
`class WsLog:
	def __init__(self):
		print('starting WSLogger')

		a = requests.get('https://www.google.com/', timeout=5)

		print('request done')

addons = [
	WsLog()
]`

**Comment by Prinzhorn** [comment] 2021-04-23 15:04
Here's what I'm seeing for both mitmdump 6.0.2 and 7.0.0-dev:

```py
import requests

class WsLog:
  def __init__(self):
    print('starting WSLogger')

    a = requests.get('https://www.google.com/', timeout=5)
    print(a)

    print('request done')

addons = [
  WsLog()
]
```

```
mitmdump --quiet --scripts req.py 
starting WSLogger
<Response [200]>
request done
```

**Comment by Prinzhorn** [comment] 2021-04-28 07:31
I'm going to close this. If you believe this is a bug in mitmproxy then please provide clear steps to reproduce it and re-open the issue.

**Closed by Prinzhorn** 2021-04-28 07:31 UTC
Labels: kind/triage

**Comment by xwqiang** [comment] 2022-03-29 11:07
I have the same problem and can't reproduce it immediately，it occured hours after proxy started.

**Comment by Prinzhorn** [comment] 2022-03-29 11:22
> it occured

What occurred? It's entirely normal for networks to fail occasionally or for Google (or your endpoint) to go down for a brief moment.
