### ISSUE TITLE
Use ~/.config/.mitmproxy/ instead of ~/.mitmproxy/ for options yaml file

### ISSUE THREAD

**Issue by Semnodime** [mitmproxy/mitmproxy#6083] opened 2023-04-26 22:36 UTC
#### Problem Description
Currently, mitmproxy does not adhere to the freedesktop standard of base directory specification.

#### Proposal
Use the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) as mentioned in [StackOverflow: location of config files in linux](https://stackoverflow.com/a/1024339).

#### Alternatives
A user could link `~/.mitmproxy/` to point to `~/.config/.mitmproxy/`, but this still clutters the home dir.

**Comment by Prinzhorn** [comment] 2023-04-27 06:01
Closing as duplicate of https://github.com/mitmproxy/mitmproxy/issues/3863 , see also https://github.com/mitmproxy/mitmproxy/pull/3950 and https://github.com/mitmproxy/mitmproxy/pull/5134

PRs are welcome.

**Closed by Prinzhorn** 2023-04-27 06:01 UTC
Labels: kind/feature

**Comment by sujaldev** [comment] 2023-04-27 08:15
@Prinzhorn besides a few things, is there something wrong with #5134?

**Comment by mhils** [comment] 2023-04-27 08:36
@sujaldev:

1. Windows CI failures
2. It adds a new datadir option, which I think shouldn't exist.
3. It still defaults to `~/.mitmproxy`. If we don't change to a better default, we'r just adding additional complexity with no real benefit.
4. Following from 3), it has no clear migration plan off `~/.mitmproxy`.

I will admit I haven't looked closely because of the CI failures. Honestly the bar for a PR here is super high because 1) it will definitely break compatibility in some ways and 2) The current approach of using `~/.mitmproxy` is not infinitely terrible and at least consistent across platforms.

**Comment by jrabinow** [comment] 2023-04-27 10:02
@mhils answered [on the original PR](https://github.com/mitmproxy/mitmproxy/pull/5134#issuecomment-1525340923)
