### ISSUE TITLE
mitmproxy crash

### ISSUE THREAD

**Issue by Michagogo** [mitmproxy/mitmproxy#1357] opened 2016-07-14 21:11 UTC
##### Steps to reproduce the problem:

1. add stream.twitter.com to /etc/hosts, pointing to 127.0.0.1
2. run `sudo mitmproxy -R https://stream.twitter.com -p 443`
3. attempt to connect to the Twitter Streaming API using tweepy

##### What is the expected behavior?
Stream connects, data is captured for analysis

##### What went wrong?
mitmproxy crashes. The error is attached -- it does something to the terminal that prevents me from selecting the text and copying it.
![image](https://cloud.githubusercontent.com/assets/2559390/16855963/77e7f6d4-4a20-11e6-890d-790eb3e749aa.png)

##### Any other comments? What have you tried so far?

---

Mitmproxy Version: whatever pip installs right now
Operating System: Ubuntu Trusty Server

**Comment by Kriechi** [comment] 2016-07-16 10:38
Duplicate of #383?

**Comment by Michagogo** [comment] 2016-07-21 14:55
This doesn't appear to share characteristics with the various comments on
that issue.

1. It happens right away, not after a while.
2. I'm not using it as a transparent proxy, I've pointed the address at it
via the hosts file and am running it in reverse proxy mode.
3. There aren't many clients or many connections -- it's exactly one client
making exactly one connection. And it's not supposed to close it -- it's a
stream.

**Comment by mhils** [comment] 2016-07-21 17:10
How do you redirect requests to the proxy? Do you possibly have a /etc/hosts entry that resolves stream.twitter.com to localhost?

**Comment by Michagogo** [comment] 2016-07-21 17:11
Yes, as I mentioned in the original issue. Why?

**Comment by mhils** [comment] 2016-07-21 17:12
Sorry, overlooked that :innocent: 
Well, mitmproxy respects /etc/hosts as any other program would do, so your ininvocation is basically 
```
mitmproxy -R https://localhost -p 443
```
which creates an infinite connect-to-self loop.

**Comment by Michagogo** [comment] 2016-07-21 17:18
Oh. Now I feel really stupid... What's the best way to avoid this? Would just giving mitmproxy the original IP address work, or would that mess up something involving the host identification or something like that? BTW, it may be a good idea to add detection for that mistake to mitmproxy itself -- seems like the kind of thing that shouldn't be too hard to check for/notice when it happens, and it could respond much more friendlily than a crash...

**Comment by mhils** [comment] 2016-07-21 17:22
Hardcoding the IP address or specifying a different domain that resolves similarly should do the job.
We actually do have that kind of [detection](https://github.com/mitmproxy/mitmproxy/blob/3d6f714b5d768b7ce24091f03a0e05e47a534271/mitmproxy/protocol/base.py#L120), but I think we do not want to make a DNS lookup at that point, @cortesi, thoughts?

**Comment by Michagogo** [comment] 2016-07-21 17:25
Would it be too kludgy/difficult to simply detect when a request sent by
the proxy is sent directly to itself? Or just to not necessarily do a DNS
lookup as part of the init, but just check when you send the first packet
out that the IP address isn't in 127/8?

**Comment by mhils** [comment] 2016-07-21 17:29
Without having tried it out, but checking after connect() won't solve the issue. 
We'd need to manually resolve the IP before connecting [here](https://github.com/mitmproxy/mitmproxy/blob/3d6f714b5d768b7ce24091f03a0e05e47a534271/netlib/tcp.py#L721).

**Comment by mhils** [comment] 2016-07-22 22:40
Closing this for now, as I believe it's not _that_ common. If you are a random person on the internet  stumbling over the same issue, please comment here so that we know we should do better on this.

**Closed by mhils** 2016-07-22 22:40 UTC
