### ISSUE TITLE
mitmdump addon stops randomly without any warning/error

### ISSUE THREAD

**Issue by tperalta82** [mitmproxy/mitmproxy#4315] opened 2020-11-27 17:02 UTC
Hey guys, 
I have no idea how to replicate this, it only happened 3 times in a month, but it seems that an addon script stops working from time to time without warning.
The only way to get it back working is either touching the script file, or restarting mitmdump.

Is there anything I can do to monitor loaded scripts and/or any kind of debugging?

**Comment by mhils** [comment] 2020-11-28 14:20
You can get some debugging info by sending SIGUSR1/SIGUSR2 to the running mitmdump process. It's really hard to say anything about this unless we have an idea how to reproduce it.

**Comment by tperalta82** [comment] 2020-11-28 15:34
Hey, thanks a lot for the reply, well, all I can say, because it's all I can notice, is that websocket_messages stop working after random time, the proxy still works and all but that's it, cannot parse them anymore!, i wish I could give more info , but honestly it's all i've got! And the only way to get it back working, is either by touching the addon file, or restarting.

Happens both with latest stable 5.3.0 and master branch code.
At the moment i coded a small thread inside the addon that is sending data constantly onto a redis server with timestamps to see if everything gets unloaded, or just the websocket_messages part... i'll try to keep this issue updated.

**Comment by mhils** [comment] 2020-12-10 08:57
I'm closing this here for now because there's nothing actionable for us. If you, dear random reader, encounter the same thing please chime in, I'm happy to reopen this if we have some ways to reproduce this.

**Closed by mhils** 2020-12-10 08:57 UTC
