### ISSUE TITLE
Option (--set web_columns) doesn't work on Windows PowerShell

### ISSUE THREAD

**Issue by andronick83** [mitmproxy/mitmproxy#4891] opened 2021-11-04 23:53 UTC
Tried different variants:
```
mitmweb.exe --set web_columns="tls icon path"
mitmweb.exe --set web_columns="tls,icon,path"
mitmweb.exe --set web_columns="tls\nicon\npath"
mitmweb.exe --set web_columns="tls`nicon`npath"
etc
```

Works with only one parameter:
`mitmweb.exe --set web_columns="path"
`

#### System Information
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.19043-SP0

**Comment by mhils** [comment] 2021-11-05 12:35
I think this is a duplicate of #4509. Can you confirm that passing `--set web_columns` multiple times works?
Again, the UX here is horrible, this is merely a workaround.

**Comment by andronick83** [comment] 2021-11-05 13:08
Yes it works
`mitmweb --set web_columns="tls" --set web_columns="icon" --set web_columns="path"
`

Thanks for the mitmproxy

**Closed** 2023-02-07 09:26 UTC
Labels: kind/triage
