### ISSUE TITLE
SSL handshake error 

### ISSUE THREAD

**Issue by lefuturiste** [mitmproxy/mitmproxy#3619] opened 2019-08-18 16:14 UTC
##### Steps to reproduce the problem:

0. Take an Android 7.1.2 Xiaomi Redmi 4X with MIUI 10.3
1. Install mitmproxy
2. launch mitmdump command
3. Set proxy on the phone & Install root certificate provided by the domain mitm.it
   using settings app: "More settings" > "Privacy" > "Install certificate" 
4. Go to any apps and try to make a http request like twitter or discordapp
5. Errors appears:

```
192.168.0.14:56294: CONNECT android.googleapis.com:443
 << Cannot establish TLS with client (sni: android.googleapis.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)
```

![](https://i.imgur.com/FxAqaHY.png)

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-5.2.5-arch1-1-ARCH-x86_64-with-arch

**Comment by lefuturiste** [comment] 2019-08-27 08:32
And so ?? it's the whole point of why I want to use that! I want to see what is coming in and out of my phone.

**Comment by lefuturiste** [comment] 2019-09-05 15:53
ok so I guess it will be more difficult to hack some apps...

**Comment by ltoop** [comment] 2019-09-10 11:52
It's possible, but you'll need to work at it...

Here's background on Android certificate pinning, with a test that MITMproxy doesn't work to confirm that it was done correctly: https://medium.com/@appmattus/android-security-ssl-pinning-1db8acb6621e

That author links to some resources on reverse engineering and patching applications, essentially you have to patch the app to skip the cert verification or replace the cert file with your own: https://medium.com/@felipecsl/bypassing-certificate-pinning-on-android-for-fun-and-profit-1b0d14beab2b and https://security-assessment.com/files/documents/whitepapers/Bypassing%20SSL%20Pinning%20on%20Android%20via%20Reverse%20Engineering.pdf

**Comment by mhils** [comment] 2019-11-15 16:35
This is a dupe of #2054.

**Closed by mhils** 2019-11-15 16:35 UTC

**Comment by Mowhow** [comment] 2022-12-25 18:39
[09:37:25]: App: com.yammer.v1 host: receiver.yamalytics.yammer.com: MITM certificate was rejected: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN

**Comment by Mowhow** [comment] 2022-12-25 18:40
What's the above posted
