### ISSUE TITLE
Certificate Verification Error for 108.62.206.196:5222: hostname 'no-hostname' doesn't match either of '*.tktn.be', 'tktn.be'

### ISSUE THREAD

**Issue by TelmoNeves** [mitmproxy/mitmproxy#1889] opened 2016-12-26 23:15 UTC
##### Steps to reproduce the problem:

1. Install mitmweb on windows 7
2. Install mitm certificate on smartphone running android 4.3
3. Run mitmweb --socks --insecure
4. Run an app which connects to a xmpp server

I get the following error:

Certificate Verification Error for 108.62.206.196:5222: hostname 'no-hostname' doesn't match either of '*.tktn.be', 'tktn.be'

Ignoring server verification error, continuing with connection

##### System information

Mitmproxy version: 1.0.0
Python version: 3.5.2
Platform: Windows-7-6.1.7601-SP1
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by mhils** [comment] 2016-12-26 23:30
Thanks! This sounds like a duplicate of https://github.com/mitmproxy/mitmproxy/issues/1846#issuecomment-266416869?

**Comment by TelmoNeves** [comment] 2016-12-26 23:35
Ah, I didn't found that issue. Ye, seems like its the same error. But how can I solve it? I'm using --insecure and it still doesn't work.

**Comment by mhils** [comment] 2016-12-26 23:46
As long as you pass `--insecure`, mitmproxy will still emit a warning, but continue with the connection anyway. In other words, whatever your issue is, it is not caused by the error you posted. Happy to help, but we need more info 😛

**Comment by TelmoNeves** [comment] 2016-12-27 00:41
Well, I don't know what kind of other info I can give. The app is using ssl sockets, that's probably why it is failing. It doesn't fail if I use charlesproxy, so I don't know why it fails here.

**Comment by mhils** [comment] 2016-12-27 00:51
Do you see anything in mitmweb's event log?

**Comment by TelmoNeves** [comment] 2016-12-27 01:03
This? http://prntscr.com/do9mv2

**Comment by mhils** [comment] 2016-12-27 01:08
In mitmweb, you can click on Options -> Show Event Log, which opens the event log (where you can also increase verbosity)

**Comment by TelmoNeves** [comment] 2016-12-27 10:46
Sorry, I missed that. It only shows clientconnect and clientdisconnect

**Comment by TelmoNeves** [comment] 2016-12-27 14:24
Ah, I think the problem is the app itself, because it is verifying the certificates. Nothing we can do, right?

**Comment by mhils** [comment] 2017-01-03 15:56
If the app does [certificate pinning](http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning), you'd need to fix that first - sorry about that.

**Closed by mhils** 2017-01-03 15:56 UTC
Labels: kind/triage

**Comment by TelmoNeves** [comment] 2017-01-03 19:49
You may close this issue, I solved the issue without mitmproxy

**Comment by 105039** [comment] 2025-08-22 08:56
Thik bro,👍😊😅🫣
