### ISSUE TITLE
crash report in v0.16

### ISSUE THREAD

**Issue by r2evans** [mitmproxy/mitmproxy#1039] opened 2016-03-17 13:50 UTC
##### Steps to reproduce the problem:

1. `mitmproxy` (no arguments, localhost with port 8080)
2. `openssl s_client -connect localhost:8080`

##### What is the expected behavior?

This should return info about the certificate.

##### What went wrong?

It crashed:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 345, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 427, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 424, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 433, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 566, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 341, in get_cert
    sans),
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 96, in dummy_cert
    ipaddress.ip_address(i.decode("ascii"))
AttributeError: 'NoneType' object has no attribute 'decode'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

##### Any other comments?

Thanks for all of the hard work :-)

---

Mitmproxy Version: 0.16
Operating System: Ubuntu 14.04.3

**Comment by mhils** [comment] 2016-03-17 13:51
Thanks. Is this a duplicate of #1025?

**Comment by r2evans** [comment] 2016-03-17 13:54
Quite possibly, but I suspected that since this is just gathering info on the cert and not actually presenting a hostname for proxying, I thought it might be a slightly different bug. I looked and hadn't seen #1025 (nor #169), I realize I was likely too quick to start a new issue.

**Comment by mhils** [comment] 2016-03-17 13:56
Just tried to reproduce it (thanks for the super easy steps!) - the error is gone on master, I think we can close this. :smiley:
FWIW, you can install the latest development snapshot from snapshots.mitmproxy.org. If you are interested in the root certificate, just take a look at ~/.mitmproxy. :wink:

**Closed by mhils** 2016-03-17 13:56 UTC

**Comment by r2evans** [comment] 2016-03-17 13:58
I'll look at a snapshot. I'm familiar with `~/.mitmproxy`; I've been having problems with a local-only transparent proxy and was troubleshooting. It appears I'm having certificate problems (I think I found it), and this was one step to see if my previous "fix" had worked.

**Comment by mhils** [comment] 2016-03-17 14:01
Good. If you have problems with the snapshot, I'd be super interested to hear where you are struggeling. We recently introduced some changes here so that just using a binary or `pip install`ing the the wheel should be everything you need to do, but that has received little testing so far. If that doesn't work, please give us a ping. :smiley:
