### ISSUE TITLE
No response when sending a large file.

### ISSUE THREAD

**Issue by SergeyMokhov** [mitmproxy/mitmproxy#6286] opened 2023-07-31 21:41 UTC
#### Problem Description
mitmproxy does not send a response when response body is large.
- Curl will times out, without receiving any data, no matter how long you wait. 
![image](https://github.com/mitmproxy/mitmproxy/assets/15617269/7226c82c-41f5-4840-b8a0-eb02f3691f4d)

- mitmproxy TUI shows flow as "content missing", but does show correct response code. 
![image](https://github.com/mitmproxy/mitmproxy/assets/15617269/27952f38-cc6b-495f-a25e-2312b55ccb97) 
![image](https://github.com/mitmproxy/mitmproxy/assets/15617269/6062818c-872b-4a1b-8f8d-ca1101a17c65)
![image](https://github.com/mitmproxy/mitmproxy/assets/15617269/d569345e-9309-4039-bd21-ad7b5f31a8da)

- Nginx logs register incoming request and response code. `xxx.xxx.xxx.xxx - - [31/Jul/2023:20:05:02 +0000] "GET /kffff HTTP/1.1" 200 6549996 "-" "curl/7.85.0" "-"`

#### Steps to reproduce the behavior:
1. Generate a large file to send later ` dd if=/dev/urandom bs=2000000000 count=1 | base64 | fold -w100 >> /tmp/file.txt`
2. Write an Nginx config to serve the file 
```
server {
    listen          80;
    server_name    localhost;
    location ~* .* {
        root                        /usr/share/nginx;
        try_files                   /payload =404;
        chunked_transfer_encoding   on;
        sendfile                    on;
    }
}
```
4. Write a script to start Nginx and mount files to the container
```
#!/usr/bin/env bash

docker run --rm -d --name nginx \
  -v path_to_config_file/nginx.conf:/etc/nginx/conf.d/default.conf \
  -v  /tmp/file.txt:/usr/share/nginx/payload \
  -p 6000:80 nginx
```
5. Start nginx and make a curl request to port 6000 to verify nginx configuration. `curl -v localhost:6000/kffff`
5. Start mitmproxy `mitmproxy --mode reverse:http://localhost:6000 -p 6001 --set keep_host_header=true`
6. Make a request to proxy `curl -v localhost:6001/kffff`

##### Expected result
- Curl starts to output the file
- mitmproxy TUI shows content of the response and not message "content missing"

##### Actual result
- Curl does not receive any data
- mitmproxy shows "content missing" instead of the response content.

#### System Information
Mitmproxy: 9.0.1
Python:    3.11.4
OpenSSL:   OpenSSL 1.1.1u  30 May 2023
Platform:  macOS-13.1-x86_64-i386-64bit

#### Additional Info
Similar results are achieved when response body is replaced by an addon. 
```
import mitmproxy

file_path = "/tmp/file.txt"


def generate_chunked_response(file_path):
    try:
        with open(file_path, 'rb') as file:
            result = bytearray()

            # Read the file in chunks
            chunk_size = 1024  # You can adjust this value to your needs
            while True:
                data_chunk = file.read(chunk_size)
                if not data_chunk:
                    break  # Reached the end of the file
                chunk_length_hex = hex(len(data_chunk))[2:]  # Get the chunk size in hexadecimal format
                chunk_header = f"{chunk_length_hex}\r\n".encode('utf-8')
                result.extend(chunk_header + data_chunk + b'\r\n')

            # Add the final chunk indicating the end of the response
            result.extend(b'0\r\n\r\n')

            return result

    except FileNotFoundError:
        return b"File not found."

print('Generatig paylod')
payload = bytes(generate_chunked_response(file_path))


class OverWriteResponseHeaders:
    def response(self, flow: mitmproxy.http.HTTPFlow):
        flow.response.content = payload



addons = [OverWriteResponseHeaders()]
```

**Comment by mhils** [comment] 2023-08-01 09:35
thanks - duplicate of #6126 I think.

**Closed by mhils** 2023-08-01 09:35 UTC
Labels: kind/triage

**Comment by SergeyMokhov** [comment] 2023-08-01 14:29
@mhils I do not think it is a duplicate. #6126 is about UI, this one is about not sending a reply when response body is large.
I probably should not have put this many details in this ticket, but my main concern is the fact that the file is not being received. There is no traffic going back to curl at all.

**Comment by mhils** [comment] 2023-08-01 16:26
Have you tried setting https://docs.mitmproxy.org/stable/concepts-options/#stream_large_bodies?

**Comment by SergeyMokhov** [comment] 2023-08-01 17:20
I did, but apparently I was not doing it properly. Now, when I corrected my mistake it works as expected. Thank you for your support.
