### ISSUE TITLE
certutil.exe import error on windows 10

### ISSUE THREAD

**Issue by vincenthawke** [mitmproxy/mitmproxy#3605] opened 2019-08-01 21:51 UTC
I managed to manually import the certificate but wish to use the console in the future where I encountered this error:

```
C:\Users\User\Desktop>certutil.exe -importpfx Root mitmproxy-ca-cert.p12
Enter PFX password:
CertUtil: -importPFX command FAILED: 0x80092007 (-2146885625 CRYPT_E_SELF_SIGNED)
CertUtil: The specified certificate is self signed.
```
Version information:
```
Mitmproxy: 4.0.4
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.17763-SP0
```

**Comment by mhils** [comment] 2020-01-03 12:18
Thanks for the report! This is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/3622#issuecomment-561968523, closing this here. :smiley:

**Closed by mhils** 2020-01-03 12:18 UTC
