### ISSUE TITLE
mitmdump --no-pop results in redirect loop

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#652] opened 2015-06-25 20:20 UTC
**What's the problem?**
Running mitmdump with the --no-pop results in an error like "This webpage has a redirect loop" for some pages.

**Which versions are affected?**
I am not sure when I first encounter this problem. I think it should go back to a version of 0.9 or 0.10. But I can confirm that this is still an issue in version 0.12.1.

**How to reproduce the problem?**
Setup mitmdump as a transparent proxy and let is save the content with option `-w`. 
Open a browser capable of following redirects like `HTTP/1.1 301 Moved Permanently` and it should be configured to open with an empty start page like `about:blank`. Firefox, Internet Explorer, Chrome and more should work.
Go to URL `bing.com`. After the website is loaded the URL should be `www.bing.com`.
Now clear the cache of the browser and close the browser.
Stop mitmdump and start it as a transparent proxy with the captured content and the `--no-pop` option.
Open the same browser and go to URL `bing.com`. Now the browser should complain about an redirect loop instead of presenting the website.

**Why does this happen?**
mitmdump use the IP but ignores the host-field and thus the domain to find the correct response. With the `--no-pop` option mitmdump search for the first appearance of [IP]/ for both domains; with and without www. Thus the redirection is presented in both cases and the loop is born.

**Are there other related problems?**
Yes. The problem is not limited for redirection to the url with www but for all virtual host related calls for the same URI on the same IP. For example it once happened that to bigger sites, both using akamai, get temporarily the same IP on recording. Thus on rewind the wrong site was presented when the second one was requested. Now they get different IPs thus it does not happen at the moment.

**Are there more information?**
I am aware of the `--replay-ignore-host` option but it is not set and thus it should be false and I could validate that it is. I also know the lines

```
         if not self.ignore_host:
             key.append(r.host)
```

in the _hash function of flow.py. But r.host is the IP of the host and not the host field of the HTTP headers.

**How could the problem be solved?**
Obviously the host field needs to be considered. As a workaround I added `r.headers.get("host")` to the hash function, if present.
I am not sure what the correct solution is. For example I do not know if r.host should be the IP and not the host-field. Additionally I do not know if the intention of `--replay-ignore-host` is to cover the request host IP and not the request host field. Thus it is not clear if these two lines are totally correct and the problem is somewhere else or not.

**Comment by mhils** [comment] 2015-07-04 16:19
Thanks for the excellent bug report (and sorry for getting back at it so late). The easy solution to this issue is passing `--rheader Host` to mitmdump. 
Nonetheless, I think we should probably use `r.pretty_host(hostheader=True)` instead of `r.host`. A PR would be highly appreciated! :smiley:

**Comment by Nerudifus** [comment] 2015-08-13 19:47
It took some time but now I could test.
As suggested the ```rheader``` worked as good as my workaround. The string for the hash is a little bit longer but I doubt that this has a mensurable negative effect.

Changing ```r.host``` to ```r.pretty_host(hostheader=True)``` leads to the fact that the domain is in the string for the hash and that there is no IP.  
Thus there should be a changing in behaviour. I once saw a DNS server sending another IP answer on every request. Thus with IP in Hash it would be a miss in cache every time and here, without the IP but with domain, it should be a hit. 
Google also change the IP from time to time. But I do not know the algorithm behind it thus there is no good way to reproduce it. Therefore this is only a speculation of mine by seeing the string for the hash. Maybe a dynamic DNS with an IP changing internet provider could help by testing this.

Independent of that, the reason of writing this text is that mitmdump is not working as suggested without an additional parameter, at least in my opinion. Thus if ```--no-pop``` should not work with vhosts without ```--rheader Host``` I would propose to add a note to the description of ```--no-pop```.

**Comment by kira0204** [comment] 2018-02-12 00:03
Hi, I tested it using the `server_replay_nopop` and there was no issue when I tried to reproduce the problem. I am not able to find when this was resolved but I think it's not an issue anymore :)

**Comment by mhils** [comment] 2018-02-12 10:11
This issue still very much exists - the first step would probably be coming up with a good test case and then changing `.host` to `.pretty_host`.
Long term, the ideal approach might be to cycle through all valid responses for one key, but finding good data structures here is not entirely trivial.

**Comment by AdderAdder** [comment] 2021-01-03 13:39
Hi, @mhils is this still an active issue?

If so I could try working on it (I'm new to open source contributing and I'm trying to get into it).

However, at the moment I have only time for this during weekends so if this issue is urgent I will look for a more suitable issue to take.

**Comment by mhils** [comment] 2021-01-03 14:13
@AdderAdder: I haven't looked at this for over two years now. Since nobody complained in the meantime, I'll just close this now.

If someone runs into this in the future, please open a new issue with a suitable test case. :)

**Closed by mhils** 2021-01-03 14:13 UTC
Labels: help wanted, kind/feature
