### ISSUE TITLE
'ValueError: math domain error' when rendering certain DNS requests

### ISSUE THREAD

**Issue by nneonneo** [mitmproxy/mitmproxy#7356] opened 2024-11-27 02:10 UTC
#### Problem Description
When using Wireguard mode, some DNS responses appear to arrive before the request is finished. This results in a negative duration value, which causes the console UI to repeatedly throw errors of the following form:

```
error: [07:30:01.291] Unhandled error in task.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/lib/python3.10/site-packages/urwid/event_loop/asyncio_loop.py", line 104, in wrapper
    return callback(*args, **kwargs)
  File "/lib/python3.10/site-packages/urwid/display/_posix_raw_display.py", line 273, in wrapper
    return self.parse_input(event_loop, callback, self.get_available_raw_input())
  File "/lib/python3.10/site-packages/urwid/display/_raw_display_base.py", line 488, in parse_input
    callback(decoded_codes, raw_codes)
  File "/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 466, in _update
    self.process_input(keys)
  File "/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 566, in process_input
    handled_key = self._topmost_widget.keypress(self.screen_size, key)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/window.py", line 301, in keypress
    k = super().keypress(size, k)
  File "/lib/python3.10/site-packages/urwid/widget/frame.py", line 526, in keypress
    return self.body.keypress((maxcol, remaining), key)
  File "/lib/python3.10/site-packages/urwid/widget/widget.py", line 729, in keypress
    return get_delegate(self).keypress(size, key)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/window.py", line 42, in keypress
    ret = super().keypress(size, key)
  File "/lib/python3.10/site-packages/urwid/widget/frame.py", line 526, in keypress
    return self.body.keypress((maxcol, remaining), key)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/flowlist.py", line 102, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/lib/python3.10/site-packages/urwid/widget/listbox.py", line 1345, in keypress
    return actual_key(self._keypress_page_up((maxcol, maxrow)))
  File "/lib/python3.10/site-packages/urwid/widget/listbox.py", line 1567, in _keypress_page_up
    widget, pos = self._body.get_prev(pos)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/flowlist.py", line 81, in get_prev
    return self._get(pos - 1)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/flowlist.py", line 75, in _get
    return FlowItem(self.master, self.master.view[pos]), pos
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/flowlist.py", line 13, in __init__
    w = self.get_text()
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/flowlist.py", line 24, in get_text
    return common.format_flow(
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/common.py", line 796, in format_flow
    return format_dns_flow(
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/common.py", line 723, in format_dns_flow
    duration_pretty, duration_style = format_duration(duration)
  File "/lib/python3.10/site-packages/mitmproxy/tools/console/common.py", line 349, in format_duration
    99 - 100 * min(math.log2(1 + 1000 * duration) / 12, 0.99)
ValueError: math domain error
```

Notably, I left mitmproxy running overnight and the memory usage ballooned to 14 GB - all due to copies of this message (the Wireguard client had already disconnected).

#### Steps to reproduce the behavior:
1. Load the attached [dns.mitmproxy](https://github.com/user-attachments/files/17927796/dns.mitmproxy.zip) file (`mitmproxy -r dns.mitmproxy -n`)
2. The middle DNS request displays with a negative duration
3. Watch as the event log fills with errors

#### System Information

Mitmproxy: 11.0.1
Python:    3.10.11
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  macOS-14.6.1-x86_64-i386-64bit

#### Suggested Fix

An immediate fix would be to ensure that `duration` is not negative in `format_duration`, e.g. to clamp it to zero if it is negative. It may also be worth figuring out why and how a DNS request can have a negative duration; this is observed with some regularity on my network. Finally, a crash in the renderer should not produce such a huge volume of logging; perhaps a minor rendering failure should produce a single log message and the resulting failure cached to avoid log explosions.

**Comment by mhils** [comment] 2024-11-27 09:41
Thanks! I believe this is a duplicate of #6646.

**Closed** 2024-11-27 09:41 UTC
Labels: kind/triage
