### ISSUE TITLE
mitmproxy crashes with OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by charlbury** [mitmproxy/mitmproxy#5141] opened 2022-02-18 13:11 UTC
#### Problem Description
With mitmproxy running, browsing to the bbc.co.uk website and most other web sites, mitmproxy crashes with the error "OSError: [WinError 10038] An operation was attempted on something that is not a socket"

This is running on a newly setup windows 10 PC, I have used pipx to install mitmproxy. I have configured the proxy in Windows Settings to point to http://locahost and the port 8080.

![Screenshot 2022-02-18 131002](https://user-images.githubusercontent.com/3824684/154688837-f0532864-9d5d-4acf-a191-eba48eb17522.png)

#### Steps to reproduce the behavior:
1. In windows settings configure the proxy to point to http://localhost and the port to b 8080
2. start mitmproxy in a terminal window
3. open chrome and browse to bbc.co.uk

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 8.0.0.dev
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1m  14 Dec 2021
Platform:  Windows-10-10.0.19042-SP0

**Comment by mhils** [comment] 2022-02-18 13:38
Thanks! Duplicate of #5016. 7.x should work as expected.

**Closed by mhils** 2022-02-18 13:38 UTC
Labels: kind/triage

**Comment by mhils** [comment] 2022-02-18 13:41
https://docs.mitmproxy.org/dev/overview-installation/

Our standalone binaries are 7.x, and `pipx install mitmproxy` should also install 7.x.

**Comment by charlbury** [comment] 2022-02-18 13:46
pipx install mitmproxy is definitely installing the 8.0.0.0dev version for me. I want to avoid using the binaries as I am trying to install additional Python packages alongside mitmproxy.

my attempts at pipx installing a previous version don't work

pipx install 'mitmproxy<8.0.0.0dev' --force-reinstall

Is there another way? Thanks!

**Comment by mhils** [comment] 2022-02-18 13:51
There are no 8.0.0.dev binaries on PyPI (https://pypi.org/project/mitmproxy/), so I'm a bit confused where pipx would pick them up from?

```
PS C:\Users\user> pipx install mitmproxy
  installed package mitmproxy 7.0.4, installed using Python 3.10.0
```

What's the output of `pipx list` and `Get-Command mitmproxy` on your system?

**Comment by charlbury** [comment] 2022-02-18 14:54
So, I pipx uninstalled mitmproxy. Then I did `pipx install mitmproxy` and it reported that 7.0.4 had been installed. I updated windows proxysettings to turn on the proxy and browsed to bbc.co.uk and I got the same error again.

When I went back to the terminal and did a `mitm --version`, it reports I have 8.0.0.dev installed.

When I do a `pipx list`, it reports that package mitmproxy 7.0.4 is installed.

![Screenshot 2022-02-18 145207](https://user-images.githubusercontent.com/3824684/154706190-75ed3b85-ac44-4b81-865f-e93eee1498cd.png)

**Comment by mhils** [comment] 2022-02-18 15:43
This looks like you also have a `pip`-installed mitmproxy, and the pip-installed version comes first on your PATH.

**Comment by charlbury** [comment] 2022-02-18 17:18
I've reset the windows machine to a clean install (using the windows settings -> update & security ->  recovery -> reset this pc) and completely reset all files and install.

I have git cloned my project and installed the requirements then pipx installed mitmproxy. My `pip list` and `pipx list` results are below showing mitmproxy only in the pipx list. 

mitmproxy --version does now show 7.0.4 after an error occurs, but I still get mitmproxy 7.0.4 crashing with an error when I browse bbc.co.uk website and other popular sites, as seen in screengrab below.

![Screenshot 2022-02-18 170732](https://user-images.githubusercontent.com/3824684/154730519-95f6de42-002b-42e4-b396-47a96bbee9ac.png)


```
C:\Users\admin>pipx list
venvs are in C:\Users\admin\.local\pipx\venvs
apps are exposed on your $PATH at C:\Users\admin\.local\bin
   package mitmproxy 7.0.4, installed using Python 3.10.2
    - mitmdump.exe
    - mitmproxy.exe
    - mitmweb.exe

C:\Users\admin>pip list
Package          Version
---------------- ----------
argcomplete      2.0.0
asgiref          3.4.1
blinker          1.4
Brotli           1.0.9
certifi          2021.10.8
cffi             1.15.0
click            8.0.3
colorama         0.4.4
cryptography     36.0.1
Flask            2.0.3
h11              0.12.0
h2               4.1.0
hpack            4.0.0
hyperframe       6.0.1
itsdangerous     2.0.1
Jinja2           3.0.3
kaitaistruct     0.9
ldap3            2.9.1
MarkupSafe       2.0.1
msgpack          1.0.3
packaging        21.3
passlib          1.7.4
pip              22.0.3
pipx             1.0.0
protobuf         3.19.4
publicsuffix2    2.20191221
pyasn1           0.4.8
pycparser        2.21
pydivert         2.1.0
pyOpenSSL        21.0.0
pyparsing        3.0.7
pyperclip        1.8.2
ruamel.yaml      0.17.21
ruamel.yaml.clib 0.2.6
setuptools       58.1.0
six              1.16.0
sortedcontainers 2.4.0
tornado          6.1
urwid            2.1.2
userpath         1.8.0
Werkzeug         2.0.3
wsproto          1.0.0
zstandard        0.16.0

```

**Comment by mhils** [comment] 2022-02-18 22:25
(please post text and not screenshots where possible, that simplifies finding related issues)

Thanks! This is a different error now. Can you reproduce this with mitmdump instead of mitmproxy? This way we should not get the console UI in the way. bbc.co.uk works fine on my Windows system...

**Comment by charlbury** [comment] 2022-02-18 22:44
Apologies for this moving from one error to another. I completely reset the windows machine again (again using the windows settings -> update & security -> recovery -> reset this pc), but this time did nothing but install python and pipx. I then tried the `pipx install mitmproxy` but got this error

```
C:\Users\admin\Documents>pipx install mitmproxy

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\pipx.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pipx\main.py", line 779, in cli
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pipx\main.py", line 202, in run_pipx_command
    return commands.install(
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pipx\commands\install.py", line 60, in install
    venv.install_package(
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pipx\venv.py", line 238, in install_package
    subprocess_post_check_handle_pip_error(pip_process)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pipx\util.py", line 349, in subprocess_post_check_handle_pip_error
    print(completed_process.stderr, file=pip_error_fh, end="")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 112: character maps to <undefined>
```

I have seen this before and have worked around it by building the library using the setup.py script, however, I would avoid this on this occasion as I want the pipx installed version so that I can ad packages to its virtual environment.

These are the results of my pip and pipx installs on this fresh install windows 10 machine

```
C:\Users\admin\Documents>pip list
Package     Version
----------- -------
argcomplete 2.0.0
click       8.0.3
colorama    0.4.4
packaging   21.3
pip         22.0.3
pipx        1.0.0
pyparsing   3.0.7
setuptools  58.1.0
userpath    1.8.0

C:\Users\admin\Documents>pipx list
nothing has been installed with pipx 😴
```

**Comment by mhils** [comment] 2022-02-18 22:49
I'm afraid I can't help you with that. That's not a mitmproxy issue, that's a pipx issue. You can also just use pip if that's easier for you.

**Comment by mhils** [comment] 2022-02-23 23:24
> The simple fact of the matter is that you **cannot do MITM Proxy with Pip on Windows**, period.

Both pip and pipx work great for me on Windows to install mitmproxy. It's my primary development environment. But I'm happy to hear whatever issues you are facing if they are in some way related to mitmproxy. 🙃

**Comment by 89z** [comment] 2022-02-23 23:38
Ah yeah, my mistake. It does work, but you have to install "Microsoft C++ Build Tools", because of this package:

~~~
Building wheel for urwid (setup.py) ... error
~~~

which I refuse to do. I dont think I should have to install a C compiler for a Python package. So in the end I chose to use the prebuilt version. Is it possible for MITM Proxy to dump the requirement on `urwid`?

**Comment by mhils** [comment] 2022-02-24 08:04
We need urwid for the console UI, unfortunately there's no way around it.
