### ISSUE TITLE
mitmproxy has crashed! AttributeError: 'NoneType' object has no attribute 'host'

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1409] opened 2016-07-22 22:20 UTC
##### Steps to reproduce the problem:

1. Redirect multiple requests requests

##### Any other comments? What have you tried so far?
```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 497, in _find_cert
    host = self.server_conn.address.host
AttributeError: 'NoneType' object has no attribute 'host'
```

---

Mitmproxy Version:
Operating System:

**Comment by mhils** [comment] 2016-07-22 22:22
duplicate of https://github.com/mitmproxy/mitmproxy/issues/861

**Closed by mhils** 2016-07-22 22:22 UTC
