### ISSUE TITLE
Starting via Python is no longer supported after version 7.0.2

### ISSUE THREAD

**Issue by anylayer** [mitmproxy/mitmproxy#5327] opened 2022-05-06 15:27 UTC
#### Problem Description
Debugging and interaction are more effective  in the above way, but it has been removed after 7.0.2.
Maybe mitmproxy is positioned as a middle agent to capture packets, but I prefer to use it to do something automated as a library.
see [here](https://stackoverflow.com/questions/68654077/is-there-a-way-to-start-mitmproxy-v-7-0-2-programmatically-in-the-background)
![image](https://user-images.githubusercontent.com/46556817/167165581-52cbaad0-d41c-4424-ab0e-1f073f23409a.png)

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by mhils** [comment] 2022-05-06 15:41
Duplicate of https://github.com/mitmproxy/mitmproxy/discussions/5274

**Closed by mhils** 2022-05-06 15:41 UTC
Labels: kind/triage
