### ISSUE TITLE
problem with port in host

### ISSUE THREAD

**Issue by Nerudifus** [mitmproxy/mitmproxy#651] opened 2015-06-24 20:31 UTC
RFC 7230 (HTTP 1.1) declares in 5.4 Host that it is possible to add the port to the Host header field. For example ```Host = this.is.some.example.host:8080```. This is especially true if not the default port is used.
This is not properly handled by mitmdump. In my first, pre 0.12.1, tests with HTTPS mitmdump generates a bad gateway as response. In my current test with HTTP and port 8080 it seems to work but the output of mitmdump is still incorrect. It uses this.is.some.example.host:8080:8080 in its output.

I am not sure if this is only a display error or if mitmdump internally use the duplicated port and that the old HTTPS server could not handle it but the current HTTP could.

**Comment by mhils** [comment] 2015-06-24 21:02
Thanks for the report. This probably needs to be fixed in `HTTPRequest.pretty_host`. I'd be happy to accept a patch!

**Comment by MatthewShao** [comment] 2015-11-05 06:45
Hi there!
I want to have a try on this issue, could you guys please tell me how to reproduce the error?

**Comment by dufferzafar** [comment] 2016-02-08 18:21
I am having a hard time reproducing this too!

I ran `mitmdump --host`, and then ran this command to add a request to mitmdump, but I don't see repeated port numbers. 

```bash
printf "GET http://example.com HTTP/1.1\r\nhost: this.is.some.example.host:8090" | nc localhost 8080 >/dev/null
```

**Comment by mhils** [comment] 2016-02-08 22:37
You can reproduce it with `GET http://example.com:8084/ HTTP/1.1\r\nHost: example.org:8090`.

Cheers,
Max

**Comment by dufferzafar** [comment] 2016-02-09 15:20
@mhils Thanks. 

This is being caused because [`netlib.http.request.pretty_host`](https://github.com/mitmproxy/netlib/blob/master/netlib/http/request.py#L162-L169) just returns the `host` header as it is.

So, this should be fixed in netlib (rather than mitmproxy's `HTTPRequest.pretty_host`) right?

**Comment by mhils** [comment] 2016-02-09 15:26
Yes, please.

https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py#L29 is also relevant here.

**Comment by dufferzafar** [comment] 2016-02-13 12:06
@mhils I am a bit confused :/

What should actually happen in the case of two port numbers (like the one you mentioned: `GET http://example.com:8084/ HTTP/1.1\r\nHost: example.org:8090`)

Which port does the actual connection opens to?

**Comment by Nerudifus** [comment] 2016-02-14 09:23
Depending on [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) ```5.2 The Resource Identified by a Request```:

> An origin server that does not allow resources to differ by the
   requested host MAY ignore the Host header field value when
   determining the resource identified by an HTTP/1.1 request. (But see
   section 19.6.1.1 for other requirements on Host support in HTTP/1.1.
>
>An origin server that does differentiate resources based on the host
   requested (sometimes referred to as virtual hosts or vanity host
   names) MUST use the following rules for determining the requested
   resource on an HTTP/1.1 request:
>
>   1. If Request-URI is an absoluteURI, the host is part of the
     Request-URI. Any Host header field value in the request MUST be
     ignored.
>
>   2. If the Request-URI is not an absoluteURI, and the request includes
     a Host header field, the host is determined by the Host header
     field value.
>
>   3. If the host as determined by rule 1 or 2 is not a valid host on
     the server, the response MUST be a 400 (Bad Request) error message.

I think for server side both ports 8090 and 8084 should handle it as a request for ```example.com:8084```. Thus I think the service behind 8090 should be a proxy or answer with 404. In conclusion the port to connect to should be 8084.

I'm currently not able to test. Thus I can not present a working example. At that time I used mitmdump as a transparent proxy and simply request a real server at port 8080 with Firefox. So the request should be something like ```GET / [...]```
> The most common form of Request-URI is that used to identify a
   resource on an origin server or gateway. In this case the absolute
   path of the URI MUST be transmitted (see section 3.2.1, abs_path) as
   the Request-URI, and the network location of the URI (authority) MUST
   be transmitted in a Host header field.

But I have no network capturing so this is not for sure. I hope I have the time to create a way to reproduce it in the next days.

**Comment by mhils** [comment] 2016-02-14 23:42
We always take the absolute-form info for the target address, so this matches what we do. For `pretty_host`, we should probably do something along those lines:

0. If there is no host header, return `self.host`.
1. Try to split host header into host and port.
2. If there is no port, set the port to be the default for the scheme (http=80, https=443).
3. Compare port it with `self.port`.    
    4.1 If both match, return host.    
    4.2 otherwise, return `self.host`.

This prevails the original address when the host header has an unexpected form.

@dufferzafar, makes sense?

**Comment by Nerudifus** [comment] 2016-02-17 17:28
To reproduce portquiz could be used.

With the current version 0.16 I started mitmdump as transparent proxy (```mitmdump -T --host -w [...]```) on a computer with two ethernet ports configured as a bridge. The client (firefox 38) opens ```http://www.portquiz.net:8080``` and in the output of mitmdump there is something like
```
[...]
192.168.X.Y:49700: clientconnect
192.168.X.Y GET http://www.portquiz.net:8080:8080/
 << 301 Moved Permanently 193B
[...]
192.168.X.Y:49700: clientdisconnect
[...]
```
I hope this is helpful.

**Closed** 2016-02-18 23:14 UTC
Labels: enhancement, good first contribution
