### ISSUE TITLE
'Too many open files' bugs.

### ISSUE THREAD

**Issue by secsnake** [mitmproxy/mitmproxy#743] opened 2015-08-31 00:56 UTC
This is some error info.
<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 135, in handle
    **conn_kwargs).handle_messages()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1035, in handle_messages
    while self.handle_flow():
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1109, in handle_flow
    ret = self.process_request(flow, req)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1308, in process_request
    return self.process_connect_request(self.c.server_conn.address)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1501, in process_connect_request
    self.c.establish_ssl(server=True, client=True)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 279, in establish_ssl
    chain_file=chain_file
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/connection.py", line 71, in convert_to_ssl
    tcp.BaseHandler.convert_to_ssl(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 652, in convert_to_ssl
    **sslctx_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 615, in create_ssl_context
    context = self._create_ssl_context(**sslctx_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 426, in _create_ssl_context
    context.load_verify_locations(ca_pemfile, ca_path)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
</pre>
and
<pre>
Exception in thread SlaveThread (0.0.0.0:8080):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/controller.py", line 83, in run
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 711, in serve_forever
  File "/usr/lib/python2.7/socket.py", line 202, in accept
error: [Errno 24] Too many open files
</pre>

maybe,the reason is ssl cer file too many?

**Comment by mhils** [comment] 2015-08-31 01:02
duplicate of https://github.com/mitmproxy/mitmproxy/issues/383#issuecomment-72677661?

**Closed** 2015-09-08 15:47 UTC
