### ISSUE TITLE
Unable to write mitmproxy flow results to sqlite3 database

### ISSUE THREAD

**Issue by aldabrada** [mitmproxy/mitmproxy#4494] opened 2021-03-11 15:37 UTC
#### Problem Description
I am trying to store the mitmproxy flows to the database for further processing but when using the following code to insert into the sqlite3 database it's just skipping the insert into the database line and no data gets saved.

#### Steps to reproduce the behavior:
I've used the following code:

```
from mitmproxy.options import Options
from mitmproxy.proxy.config import ProxyConfig
from mitmproxy.proxy.server import ProxyServer
from mitmproxy.tools.dump import DumpMaster

import sqlite3

conn = sqlite3.connect('traffic.db')

c = conn.cursor()

c.execute("""CREATE TABLE IF NOT EXISTS traffic (
        id INTEGER PRIMARY KEY,    
        path,
        method,
        status,
        request,
        response
        )""")
conn.commit()


class Addon(object):
    def __init__(self):
        self.num = 1

    def request(self, flow):
        print("flow.request.path")
        print(flow.request.path)
        c.execute("INSERT INTO traffic VALUES (null, :path, :method, :status, :request, :response)",
                  {'path': flow.request.path, 'method': flow.request.method, 'status': flow.response.status_code,
                   'request': flow.request.get_content(), 'response': flow.response.content})
        conn.commit()
        flow.request.headers["count"] = str(self.num)

    def response(self, flow):
        self.num = self.num + 1
        flow.response.headers["count"] = str(self.num)
        print(self.num)

if __name__ == "__main__":
    options = Options(listen_host='0.0.0.0', listen_port=8080, http2=True)
    m = DumpMaster(options, with_termlog=False, with_dumper=False)
    config = ProxyConfig(options)
    m.server = ProxyServer(config)
    m.addons.add(Addon())
    m.run()
```

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.18362-SP0

What is the correct way of doing this or what am I doing wrong?

**Comment by mhils** [comment] 2021-03-11 18:06
It's hard to say what the problem is here, that generally looks right. I would recommend not to instantiate mitmproxy manually, but to just run `mitmdump -s script.py`.

**Comment by aldabrada** [comment] 2021-03-11 23:51
> It's hard to say what the problem is here, that generally looks right. I would recommend not to instantiate mitmproxy manually, but to just run `mitmdump -s script.py`.

That's the main idea here, to use it inside a script but even with mitmdump, what would be the best approach to send the dump to a database?

**Comment by mhils** [comment] 2021-03-12 07:39
If you run your addon in mitmdump (add `addons = [Addon()]` at the bottom, remove `if __name__ == "__main__":` block), you'l quicky notice that it prints you a useful error:

```
Addon error: Traceback (most recent call last):
  File ".\foo.py", line 26, in request
    {'path': flow.request.path, 'method': flow.request.method, 'status': flow.response.status_code,
AttributeError: 'NoneType' object has no attribute 'status_code'
```

I'm closing this here in favor of https://stackoverflow.com/questions/66569878/unable-to-write-mitmproxy-flow-results-to-sqlite3-database, this is not a mitmproxy bug.

**Closed by mhils** 2021-03-12 07:39 UTC
Labels: kind/triage

**Comment by aldabrada** [comment] 2021-03-12 12:57
The error show only when using mitmdump -s myscript.py and has nothing to do with not being able to send to database. Moreover, it might be a bug or at least a valid question on how to send mitmproxy flows to a database.
