### ISSUE TITLE
502 server disconnected response, SSL

### ISSUE THREAD

**Issue by dsultanr** [mitmproxy/mitmproxy#3036] opened 2018-04-04 08:09 UTC
##### Steps to reproduce the problem:

1. the request must be repeated a few times (page reload), 10-15 times in chrome (mine is chromium 65.0.3325.181)

https://search.tez-tour.com/tariffsearch/refs?callback=jsonp1522770924501&_=1522770924725&locale=ru&rfCityId=345

could be also reproduced on another host and url (ssl only)
also I can't reproduce the issue by curl

HAR:
[dump.har.txt](https://github.com/mitmproxy/mitmproxy/files/1874875/dump.har.txt)

pcap key 
`CLIENT_RANDOM 73c073fb0b36203e0804d5b106daa69e827a28b8727d8f76636cf8a59a6dd729 595b421c229a47c77e5c44386070e1c630b6f249579479c38e14a334a44abb0b523dee9321cb11d1a498ae7ec74d8522`

pcap from tcpdump is attached
there are a few successful requests and last one is unsuccessful in pcap
[capture.zip](https://github.com/mitmproxy/mitmproxy/files/1874777/capture.zip)

chrome://net-internals output
[chrome-net-internals.txt](https://github.com/mitmproxy/mitmproxy/files/1874879/chrome-net-internals.txt)

finally mitmdump -v output
[mitmdump0404.log](https://github.com/mitmproxy/mitmproxy/files/1874881/mitmdump0404.log)

##### System information
Mitmproxy: 3.0.3
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core

**Comment by dsultanr** [comment] 2018-04-04 15:12
same issue on mozilla firefox quantum 59.0.2

**Comment by mhils** [comment] 2018-04-05 16:28
Thanks for the report. This seems to be a duplicate of #3038, which was just resolved with the release of mitmproxy 3.0.4. :-)

**Closed by mhils** 2018-04-05 16:28 UTC

**Comment by dsultanr** [comment] 2018-04-05 17:50
confirm, thanks
