### ISSUE TITLE
Network is slow when reading file inside a script

### ISSUE THREAD

**Issue by amirbilu** [mitmproxy/mitmproxy#1747] opened 2016-11-16 07:40 UTC
Hi,

First of all, would like to thank anyone for this amazing project.

I wrote a small script which gets a key-value json of url1->url2,
And respond with url2 while trying to reach url1.

This is the script:

```
import argparse
import os
import json
from mitmproxy import ctx
from netlib.http import url


class Replacer:
    def __init__(self, urls_mapping):
        with open(os.path.expanduser(urls_mapping)) as urls_mapping_file:
            self.urls_mapping = json.load(urls_mapping_file)
        

    def request(self, flow):
        if not flow.request.url in self.urls_mapping:
            return;

        src = url.parse(flow.request.url)
        dst = url.parse(self.urls_mapping[flow.request.url])

        flow.request.path = dst[3]
        flow.request.port = dst[2]
        flow.request.host = dst[1]


def start():
    parser = argparse.ArgumentParser()
    parser.add_argument("urls_mapping",type=str)
    args = parser.parse_args()
    return Replacer(args.urls_mapping)

```

The logic works good, but it seems to make the network much slower. 
Is the construction of the Replacer object made with every request? Making it reading the json file every time? Is there any way to optimize the script?

Thanks guys!

**Comment by mhils** [comment] 2016-11-21 12:00
Hi,

Thanks. 

> Is the construction of the Replacer object made with every request? Making it reading the json file every time?

No. (if you see this, that would be a bug)

> Is there any way to optimize the script?

Overall, this looks pretty solid to me. I would suspect that the perceived slowness is caused by connecting to the original server first. You can pass `--no-upstream-cert` and see if that improves things.

**Comment by amirbilu** [comment] 2016-11-24 12:16
Thanks for the quick response!

I do see that when I change the JSON file, it immediately impacts the script. So unless there's some magic way it watches the file for changes.. I guess it does read it with every request.

What do you say? Is there any way I can help to find the problem?

**Comment by mhils** [comment] 2016-11-24 15:20
> I do see that when I change the JSON file, it immediately impacts the script. So unless there's some magic way it watches the file for changes.

Yes - it watches your script's directory in the background and automatically reloads your script when something changes. This is a permanent thing happening in the background and does not happen for every request.

> Is there any way I can help to find the problem?

Which problem are we talking about here? Reloading or "slowness"?

**Comment by amirbilu** [comment] 2016-11-24 21:32
I was referring to the slowlness.

The json file indeed is in the script's directory. So it now makes sense to
me it loaded with every change.

Okay, so don't let me bother you with false assumptions. I'll try to find
some time for debugging and get back with answers.

Appreciate your prompt response

Amir

**Comment by mhils** [comment] 2016-11-28 01:16
> I was referring to the slowlness.

`--no-upstream-cert` should be the switch giving you the most obvious speedups. I'm closing this for now - please feel free to open a new issue if you have something where we can easily reproduce performance regressions. :smiley:

**Closed by mhils** 2016-11-28 01:16 UTC
Labels: kind/triage
