### ISSUE TITLE
mitmproxy has crashed!Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1408] opened 2016-07-22 18:34 UTC
##### Steps to reproduce the problem:

1. Redirecting few requests
 

##### What is the expected behavior?
It should not crash, it should be running all the time

##### What went wrong?
mitmproxy crashed

##### Any other comments? What have you tried so far?

```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxyTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 323, in __call__
    self.handle_regular_mode_connect(request)
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 409, in handle_regular_mode_connect
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 408, in _establish_tls_with_client
    alpn_select_callback=self.__alpn_select_callback,
  File "/Library/Python/2.7/site-packages/libmproxy/models/connections.py", line 82, in convert_to_ssl
    super(ClientConnection, self).convert_to_ssl(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 759, in convert_to_ssl
    **sslctx_kwargs)
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 722, in create_ssl_context
    context = self._create_ssl_context(**sslctx_kwargs)
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 504, in _create_ssl_context
    context.load_verify_locations(ca_pemfile, ca_path)
  File "build/bdist.macosx-10.9-intel/egg/OpenSSL/SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "build/bdist.macosx-10.9-intel/egg/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

---

Mitmproxy Version: 
Operating System:

**Comment by Kriechi** [comment] 2016-07-22 18:54
duplicate of #743 and #383

**Closed by Kriechi** 2016-07-22 18:54 UTC
