### ISSUE TITLE
Support listening on multiple ports

### ISSUE THREAD

**Issue by bramp** [mitmproxy/mitmproxy#4887] opened 2021-11-01 01:30 UTC
#### Problem Description

I would like to listen on both port 80 and 443.

#### Proposal

Allow listen_port to accept a comma separated list, for example, `--listen_port=80,443`

#### Alternatives

Running two instances of mitmproxy, or using a `iptables` redirect hack.

#### Additional context

I'm aware of the `iptables` style hacks to redirect multiple ports to a single one. It just seemed simpler to get mitmproxy to listen on two ports, and avoid different setup on mac, window, linux, etc.

**Comment by Prinzhorn** [comment] 2021-11-01 08:09
> Allow listen_port to accept a comma separated list, for example, --listen_port=80,443

We actually want/need to take this one step further, since it's more complicated than just listening on multiple ports (e.g. you need different mappings in reverse mode for each port).

Closing as duplicate of https://github.com/mitmproxy/mitmproxy/issues/4656

**Closed by Prinzhorn** 2021-11-01 08:09 UTC
Labels: kind/feature

**Comment by Prinzhorn** [comment] 2022-08-02 15:55
This is now available on `main`. Any feedback is appreciated, please test it.

`mitmproxy --mode 'regular@8080' --mode 'regular@8443'`

https://docs.mitmproxy.org/dev/concepts-options/#mode

**Comment by MarkShawn2020** [comment] 2022-09-11 14:51
> This is now available on `main`. Any feedback is appreciated, please test it.
> 
> `mitmproxy --mode 'regular@8080' --mode 'regular@8443'`
> 
> https://docs.mitmproxy.org/dev/concepts-options/#mode

I really need this feature, please merged it into the latest pypi ASAP, much tks!

**Comment by mhils** [comment] 2022-09-11 16:00
You can `pip install` the wheel from https://snapshots.mitmproxy.org/branches/main/ and provide feedback. :-)
