### ISSUE TITLE
Number of flows not updated after setting `view filters`

### ISSUE THREAD

**Issue by fenilgandhi** [mitmproxy/mitmproxy#3000] opened 2018-03-19 05:52 UTC
##### Steps to reproduce the problem:
After setting or  removing the `view_filter` in flows list, the number of flows in the status bar is not updated. 
1. open `mitmproxy`
2. open some url (populate flow list)
3. Without navigating through the list,  set a view filter e.g.  `:set view_filter=google` 
4. The flow list  is filtered but the status bar is not updated.
5. On navigating through the focus, the status is updated.
6. Try removing the `view_filter`. Same thing happens.

Before pressing any key | After pressing key
:-------------------------:|:-------------------------:
![a](https://user-images.githubusercontent.com/9128903/37580069-da27bec2-2b67-11e8-960d-544695fda948.png) |  ![b](https://user-images.githubusercontent.com/9128903/37580070-daa0e932-2b67-11e8-9f81-b4723c3307c8.png)

##### System information
Mitmproxy: 4.0.0.dev103(commit 3c7725a)
Python: 3.6.4
OpenSSL: OpenSSL 1.1.0g 2 Nov 2017
Platform: Linux-4.14.21-1-MANJARO-x86_64-with-arch-Manjaro-Linux

**Comment by kajojify** [comment] 2018-03-19 07:20
Strange. I can't reproduce this.
I filled flow list with flows. Statusbar was updated every new flow.
![screenshot from 2018-03-19 09-14-11](https://user-images.githubusercontent.com/20267977/37582537-29132db2-2b56-11e8-850d-65a98e015447.png)

I set `:set view_filter=google` and statusbar is updated:
![screenshot from 2018-03-19 09-14-31](https://user-images.githubusercontent.com/20267977/37582595-65c720ce-2b56-11e8-8015-a63b85668a2d.png)

I get rid of `view_filter` and everything is ok.

**Comment by fenilgandhi** [comment] 2018-03-19 10:13
Yes, even for me it get updated with the flow updates. The problem is not that. The bug occurs when the list of flows is shortened(modified) by the view_filter.  My exact inputs were like maybe you could follow them to reproduce the bug.
- open mitmproxy
- Press `b` to open a attached browser 
- open some urls and once when the list is populated close the browser.
- set view_fitler using `:set view_filter=google`
- use the arrow keys to change focus ( the statusbar get updated till this moment)
- remove the filter using `:set view_filter=""`
- On this the flow list will be updated but the statusbar will not. 
- Press any arrow key, and the statusbar is updated.

**Comment by kajojify** [comment] 2018-03-19 14:41
@fenilgandhi It is a recent bug. I had `4.0.0.dev99` if I am not mistaken and I couldn't reproduce it - everything worked fine. I renewed mitmproxy codebase according to the last commit and now I see this bug :grin:

**Comment by cortesi** [comment] 2018-05-08 05:26
This is fixed on master, I believe.

**Closed by cortesi** 2018-05-08 05:26 UTC
