### ISSUE TITLE
Support IPv6 transparent proxying on Windows

### ISSUE THREAD

**Issue by spozdnyakov** [mitmproxy/mitmproxy#3080] opened 2018-04-26 12:32 UTC
Transparent mode used to work OK on Windows in version 2.0.2. There was an issue with showing correct Host headers however, so I tried to upgrade to 3.0.4 and found that transparent mode now doesn't work at all. On every client request mitmweb shows the following error message:

> Transparent mode failure: RuntimeError('Cannot resolve original destination.',)

I've tried previous mitmproxy releases and found that this functionality was broken starting from v3.0.0 
RC2. I do understand that this mode is not "officially" supported on Windows, but since it used to work, I hope it can be fixed :)

##### Steps to reproduce the problem:

1. Enable IP forwarding (https://gist.github.com/mhils/e9769fab7b1dd0775335)
2. Set port redirection, e.g.:
> netsh interface portproxy add v4tov4 listenport=80 connectaddress=192.168.0.90 connectport=8080
> netsh interface portproxy add v4tov4 listenport=443 connectaddress=192.168.0.90 connectport=8080
3. Start mitmproxy in transparent mode:
> mitmweb.exe --mode transparent --showhost
4. Install mitmproxy certificate on the phone
5. Set default gateway in phone's Wi-Fi connection properties to the mitmproxy host (e.g. 192.168.0.90)
6. Open any website in phone's browser

##### System information

Mitmproxy: 3.0.4 binary
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.16299

**Comment by mhils** [comment] 2018-04-26 13:35
Hi,

2.0.2 still works for you but 3.x doesn't? Also where do the netsh rules come from? Normally that's not required, the important part is to have the redirector running (see https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/windows.py#L122)

**Comment by spozdnyakov** [comment] 2018-04-26 13:59
More specifically, it looks like something was broken between the following commits: https://github.com/mitmproxy/mitmproxy/compare/14b33dca5d19afc2427499e25aee8b7439b4b485...40943f5618d0cc9e5ce100df4620aae9cdc236ac
Since when I'm trying to install specific revision of mitmproxy from source with --hosts issue fixed (commit 40943f5618d0cc9e5ce100df4620aae9cdc236ac), I get the same error (which I don't get in 2.0.2 release).

**Comment by mhils** [comment] 2018-04-26 14:00
Can you git-bisect it down to a specific commit?

**Comment by spozdnyakov** [comment] 2018-04-26 14:10
OK, I'll try to do it later. Regarding your questions above - yes, exactly, 2.0.2 still works but 3.x doesn't. netsh rules come from some mitmproxy setup guide for transparent mode (I just changed Linux iptables port redirection rules to its Windows analogues). When I remove these rules, nothing changes - I see the same error. So probably these rules are no longer necessary, but they are not the cause of the problem anyway.

**Comment by Jazzelhawk** [comment] 2018-05-24 22:40
Not sure why you closed this. The problem is still present in v4 and v3 with only v2 still working for transparent proxying.

Version information I tested this with:
```
Mitmproxy: 4.0.1
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17134-SP0
```
```
Mitmproxy: 3.0.4
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17134-SP0
```
```
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.4
Platform: Windows-10-10.0.17134-SP0
SSL version: OpenSSL 1.1.0f  25 May 2017
Windows version: 10 10.0.17134 SP0 Multiprocessor Free
```

**Comment by Jazzelhawk** [comment] 2018-05-25 01:39
Did a git-bisect to find the specific commit, hope this helps.

```
fab3a8dcf4d7cdce55099172e45a6a0978eac4ab is the first bad commit
commit fab3a8dcf4d7cdce55099172e45a6a0978eac4ab
Author: Maximilian Hils <git@maximilianhils.com>
Date:   Wed Feb 22 22:58:52 2017 +0100

    fix constant definition

:040000 040000 c11646312e07113d064ff98dd56dbb91d6a38fec a0a6c773bd2dcc2a47aefe980c091320a1e65329 M  mitmproxy
```

**Comment by mhils** [comment] 2018-05-25 13:30
Thanks @Jazzelhawk! It looks like IPv6 is the culprit here, which now works in mitmproxy but is not supported by our Windows resolver yet:

https://github.com/mitmproxy/mitmproxy/blob/76c056affdad6a8f57a523534c56a50524c8f7e9/mitmproxy/platform/windows.py#L152-L158

I started working on IPv6 support (https://github.com/mhils/mitmproxy/tree/windows-ipv6), but it's a bit tricky and will need a few days. One workaround for now might be binding the proxy to 127.0.0.1 in order to force IPv4.

**Comment by mhils** [comment] 2018-05-25 13:33
Ah, also regarding the close: It worked for me when testing (IPv4) and we had no further information on how to reproduce this.

**Closed** 2018-05-30 18:35 UTC
Labels: area/core, kind/feature, os/windows
