### ISSUE TITLE
request dissect curl upload file size error.

### ISSUE THREAD

**Issue by zjwangmin** [mitmproxy/mitmproxy#7172] opened 2024-09-09 07:29 UTC
#### Problem Description
As photo show blew, when I use curl upload file and use file_content = flow.request.multipart_form.get(b'file') get file content and len(file_content) is not correct, thanks. 
<img width="951" alt="image" src="https://github.com/user-attachments/assets/433b1604-687e-468d-aee7-031c9eed6586">
<img width="1472" alt="image" src="https://github.com/user-attachments/assets/bf822214-ce4f-43cf-a0c7-32a4a0b11819">
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/6739a7be-b429-4fc4-9091-a2f922092b60">

#### System Information
<img width="514" alt="image" src="https://github.com/user-attachments/assets/c0e88f59-aadd-4a0e-a439-e9ce0131ccf2">

**Comment by Prinzhorn** [comment] 2024-09-09 07:40
Please follow the template when opening a [new bug report](https://github.com/mitmproxy/mitmproxy/issues/new?assignees=&labels=kind%2Ftriage&projects=&template=bug_report.md&title=). Provide the exact curl command and a mitmproxy script.

**Comment by zjwangmin** [comment] 2024-09-09 08:23
def upload_check(self, flow):
        parsed_url = urlparse(flow.request.url)
        path = parsed_url.path
        if(path == '/upload_check'):
            if flow.request.method == "POST" and flow.request.multipart_form:
                for key, value in flow.request.multipart_form.items():
                    print(f"Key: {key}, Value size: {len(value) if value else 0}")

                file_content = flow.request.multipart_form.get(b'file')
                password = flow.request.multipart_form.get(b'password')
                size = flow.request.multipart_form.get(b'size')
                type = flow.request.multipart_form.get(b'type')
                if file_content:
                    file_data = file_content
                    file_size = len(file_data)
                    print(f"Received file size: {file_size} bytes")
                    with open(f"received_file.{type}", "wb") as f:
                        f.write(file_data)
                    print("File saved for debugging")
                    raw_size = len(flow.request.content)
                    print(f"Raw size:  {raw_size} bytes")
                    with open("raw_request.bin", "wb") as f:
                        f.write(flow.request.content)

As the code, use command curl -F "file=@2.xlsx" -F  "type=xlsx" http://127.0.0.1:8080/upload_check  
Result is raw size is correct but file size incorrect.

**Comment by zjwangmin** [comment] 2024-09-09 08:24
[2.xlsx](https://github.com/user-attachments/files/16927615/2.xlsx)
curl use file.

**Comment by Prinzhorn** [comment] 2024-09-09 09:06
Thanks, I can repro this. It seems that in particular `\n` is not correctly handled. If I upload a file with nothing but 10 newlines I get  a single "Vertical Tab" (0x0B).

This make this a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4466

**Closed by Prinzhorn** 2024-09-09 09:06 UTC
Labels: kind/triage
