### ISSUE TITLE
'TransparentProxy' object has no attribute 'request_filter' in platform/windows.py

### ISSUE THREAD

**Issue by gushengyuan** [mitmproxy/mitmproxy#3876] opened 2020-03-31 02:07 UTC
#### Problem Description
`
C:\Python37\Lib\site-packages\mitmproxy\platform>python windows.py redirect --no-local
 * Redirection active.
Traceback (most recent call last):
  File "windows.py", line 592, in <module>
    cli()
  File "C:\Python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "windows.py", line 572, in redirect
    print(f"   Filter: {proxy.request_filter}")
AttributeError: 'TransparentProxy' object has no attribute 'request_filter'
`
#### Steps to reproduce the behavior:
1. change directory to "mitmproxy\platform"
2. run command "python windows.py redirect --no-local"

#### System Information
C:\Python37\Lib\site-packages\mitmproxy\platform>mitmweb --version
Mitmproxy: 5.0.1
Python:    3.7.4
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Windows-10-10.0.18362-SP0

**Comment by techathena** [comment] 2020-03-31 19:21
hey have you tried this? 
https://github.com/mitmproxy/mitmproxy/issues/336#issuecomment-53579385

I looked at the windows.py file but couldn't  find the cause of  error.
Here ,you can take a look at how it works  here:
starting from line 370
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/windows.py
I do not have access to a windows machine at the moment so cant replicate the issue!

**Comment by gushengyuan** [comment] 2020-04-05 03:11
> hey have you tried this?
> [#336 (comment)](https://github.com/mitmproxy/mitmproxy/issues/336#issuecomment-53579385)
> 
> I looked at the windows.py file but couldn't find the cause of error.
> Here ,you can take a look at how it works here:
> starting from line 370
> https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/windows.py
> I do not have access to a windows machine at the moment so cant replicate the issue!
> Lemme know if it works for you.

hi @techathena ,
I trid to comment line #572 below, that worked well, seams like the memer request_filter is not defined anywhere.

`    print(f"   Filter: {proxy.request_filter}") `

**Comment by mhils** [comment] 2021-11-16 20:12
This is fixed on main now, I can successfully use transparent mode on Windows from an elevated command prompt. 😃

**Closed** 2021-11-16 20:12 UTC
Labels: kind/triage
