### ISSUE TITLE
shutdown mitmdump 7.0.4 raise  coroutine 'ConnectionHandler.hook_task' was never awaited

### ISSUE THREAD

**Issue by mrsiano** [mitmproxy/mitmproxy#5008] opened 2021-12-21 08:08 UTC
#### Problem Description
running mitmdump 7.0.4 with custom addon, following the [shutdown](https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/shutdown.py) example,
when it gets the shutdown() call, it raise `coroutine 'ConnectionHandler.hook_task' was never awaited`

#### Steps to reproduce the behavior:
1. run the following script 
```
from mitmproxy import ctx, http


class NetworkDumper:
    def request(self, flow: http.HTTPFlow):
        if "shutdown" in flow.request.url:
            ctx.master.shutdown()


addons = [NetworkDumper()]
```
#### System Information
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-10.15.7-x86_64-i386-64bit

**Comment by mhils** [comment] 2021-12-21 08:32
Closing as a duplicate of https://github.com/mitmproxy/mitmproxy/discussions/5000.

**Closed by mhils** 2021-12-21 08:32 UTC
Labels: kind/triage
