### ISSUE TITLE
HTTPS interception on Android 8.0 for apps with target API level 26 not working

### ISSUE THREAD

**Issue by dragosMC91** [mitmproxy/mitmproxy#3367] opened 2018-10-26 14:32 UTC
##### Steps to reproduce the problem:

1. Complete setup of mitmproxy on - pc/ mac
2. Install mitmproxy certificate on client - samsung phone with android 8.0
3. Start debugging traffic for apps on the client which have api target leve = 26

##### Actual results

I've noticed that ever since the mobile app i'm testing updated its target api level (targetSdkVersion) parameter to '26', traffic is no longer visible in mitmproxy interface.

##### What i've tried

I have tried various combinations of setups (mac/ pc) with numerous OSs (macos, ubuntu, windows) and with various clients.

The same app's traffic can easily be inspected from a different phone with android 5.1. 

I'm not sure i fully grasp what goes on 'behind the scenes' while decrypting https traffic but i found something in the android 8.0 documentation (https://developer.android.com/about/versions/oreo/android-8.0-changes) which might be the problem. The notes state '

> The system no longer sends user-agent and proxy-authorization headers from a tunneled request to the proxy server.
> The system no longer sends a proxy-authorization header on a tunneled Http(s)URLConnection to the proxy when setting up the tunnel. Instead, the system generates a proxy-authorization header, and sends it to the proxy when that proxy sends HTTP 407 in response to the initial request.
> 
> Similarly, the system no longer copies the user-agent header from the tunneled request to the proxy request that sets up the tunnel. Instead, the library generates a user-agent header for that request. 

'

##### PS
I'm having the exact same issue while trying to debug https traffic with Fiddler.

This tool has been super helpful for my testing effort, hope this will get fixed or that i'm missing something in my config.

**Comment by mhils** [comment] 2018-10-26 14:50
Thanks for the detailed report. This is a duplicate of #2054, we unfortunately can't do much here.

**Closed by mhils** 2018-10-26 14:50 UTC
