### ISSUE TITLE
Could I use socks proxy in upstream mode ?

### ISSUE THREAD

**Issue by fztfztfztfzt** [mitmproxy/mitmproxy#2772] opened 2018-01-08 11:03 UTC
##### Steps to reproduce the problem:

Could I use socks proxy in upstream mode? 
like,
`mitmproxy --mode upstream:socks://127.0.0.1:1080`
It seems that mitmproxy doesn't support socks proxy yet?

##### System information

Mitmproxy: 3.0.0.dev27 (commit 1c769b0) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by Kriechi** [comment] 2018-01-08 11:08
duplicate of #211

**Closed by Kriechi** 2018-01-08 11:08 UTC
