### ISSUE TITLE
Doesn't work with Python 3.6.0

### ISSUE THREAD

**Issue by dimaqq** [mitmproxy/mitmproxy#1892] opened 2016-12-27 14:24 UTC
##### Steps to reproduce the problem:

1. pyenv install 3.6.0
2. pyenv virtualenv 3.6.0 mitm
3. (activate mitm virtualenv)
4. pip install mitmproxy
5. mitmproxy --host

```
Successfully installed Flask-0.11.1 Jinja2-2.8 MarkupSafe-0.23 Pillow-3.4.2 PyYAML-3.12 Werkzeug-0.11.13 argh-0.26.2 blinker-1.4 brotlipy-0.6.0 certifi-2016.9.26 cffi-1.9.1 click-6.6 construct-2.8.8 cryptography-1.7.1 cssutils-1.0.1 editorconfig-0.12.1 h2-2.5.1 hpack-2.3.0 html2text-2016.9.19 hyperframe-4.0.1 idna-2.2 itsdangerous-0.24 jsbeautifier-1.6.4 mitmproxy-1.0.0 passlib-1.7.0 pathtools-0.1.2 pyOpenSSL-16.2.0 pyasn1-0.1.9 pycparser-2.17 pyparsing-2.1.10 pyperclip-1.5.27 requests-2.12.4 ruamel.yaml-0.13.6 six-1.10.0 sortedcontainers-1.5.7 tornado-4.4.2 urwid-1.3.1 watchdog-0.8.3
```

```
 ~/mitm▶mitmproxy --host                                                                                                                                   1.1m  Tue 27 Dec 2016 15:20:29 CET
Traceback (most recent call last):
  File "/dima/.pyenv/versions/mitm/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 67, in mitmproxy
    console_options = options.Options()
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/options.py", line 123, in __init__
    self.rfile = rfile
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 111, in __setattr__
    self._typecheck(attr, value)
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 122, in _typecheck
    typecheck.check_type(attr, value, expected_type)
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/utils/typecheck.py", line 24, in check_type
    if typeinfo.__qualname__ == "Union":
AttributeError: '_Union' object has no attribute '__qualname__'
```

##### System information

```
# Cut and paste the output of "mitmdump --sysinfo".

Traceback (most recent call last):
  File "/dima/.pyenv/versions/mitm/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 106, in mitmdump
    dump_options = options.Options()
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/options.py", line 123, in __init__
    self.rfile = rfile
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 111, in __setattr__
    self._typecheck(attr, value)
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/optmanager.py", line 122, in _typecheck
    typecheck.check_type(attr, value, expected_type)
  File "/dima/.pyenv/versions/3.6.0/envs/mitm/lib/python3.6/site-packages/mitmproxy/utils/typecheck.py", line 24, in check_type
    if typeinfo.__qualname__ == "Union":
AttributeError: '_Union' object has no attribute '__qualname__'

# If you're using an older version if mitmproxy, please specify the version and OS.
```

**Comment by mhils** [comment] 2016-12-27 14:25
Thanks! This is a duplicate of #1886, we hope to have this fixed ASAP.

**Comment by dimaqq** [comment] 2016-12-27 14:26
Cool, thanks!

**Closed by mhils** 2016-12-27 14:25 UTC
