### ISSUE TITLE
Occasional HTTP2-related traceback when exiting mitmproxy console

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1377] opened 2016-07-17 22:17 UTC
##### Steps to reproduce the problem:

I see this when viewing live HTTP2 traffic, after quitting the program normally with the keyboard shortcut.

##### What is the expected behavior?

No traceback.

##### What went wrong?

```
Exception in thread Http2SingleStreamLayer-15:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/protocol/http2.py", line 576, in run
    layer()
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/protocol/http.py", line 185, in __call__
    flow = self.channel.ask("response", flow)
  File "/Users/cortesi/mitmproxy/mitmproxy/mitmproxy/controller.py", line 188, in ask
    raise exceptions.Kill()
mitmproxy.exceptions.Kill
```

---

Mitmproxy version: 0.18
Python version: 3.5.1
Platform: Darwin-15.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2h  3 May 2016
Mac version: 10.11.5 ('', '', '') x86_64

**Comment by Kriechi** [comment] 2016-07-18 07:30
Duplicate of #1193.

**Closed by Kriechi** 2016-07-18 07:30 UTC
