### ISSUE TITLE
Console user interface is broken in macOS's default Terminal after upgrade to urwid 2.1.0

### ISSUE THREAD

**Issue by itaisod** [mitmproxy/mitmproxy#3936] opened 2020-04-14 08:32 UTC
#### Problem Description

The UI is dark and hard to read:
![image](https://user-images.githubusercontent.com/10780214/79202767-bf42f880-7e42-11ea-8308-5d00f6bc09d0.png)

This is just on the default Terminal. iTerm2 for example displays a healthy UI. After doing git bisect, commit 842ecbf seem to have caused it. I'll try to find the root cause when I can.

#### System Information

Mitmproxy: 5.1.1
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Darwin-19.4.0-x86_64-i386-64bit

**Comment by mhils** [comment] 2020-04-14 08:57
Very helpful, thanks! Does adjusting the console  transparency option on mitmproxy help as a workaround?

**Comment by itaisod** [comment] 2020-04-14 09:02
Nope. The main issue is that I can't see selections.

**Comment by itaisod** [comment] 2020-04-14 14:42
After bisecting urwid I found this commit to be the cause:
```
commit f6f5586582d17b6bd6abc17661c44910bda5fd23 (refs/bisect/bad)
Author: Tony Cebzanov <tonycpsu@gmail.com>
Date:   Sat Feb 10 17:27:22 2018 -0500

    24-bit (true color) support.
    
    * Palette entires can now use 6-digit #rrggbb hex codes.
    * These codes are converted to true color escape sequences for terminals that
          have the proper support.
    * Documentation updates to follow.
```

Which makes sense, mac's terminal app indeed struggles with 24bit colors. Changed to "lowlight" console palette and it's at least usable now.

**Comment by mhils** [comment] 2020-04-14 15:15
Thanks for the fantastic detective work, @itaisod! 🍰 
I have little or no idea what we can do to fix this, but knowing the root cause is a good step forward.

@Kriechi, can you confirm that you see this as well?

**Comment by mhils** [comment] 2020-04-14 16:15
@itaisod: I'd like to track down if this is a mitmproxy or an urwid bug. Would you mind running https://raw.githubusercontent.com/urwid/urwid/master/examples/palette_test.py and check if that looks consistenly across your terminals?

**Comment by itaisod** [comment] 2020-04-14 17:07
Funny, that's exactly what I've been doing. I don't know urwid very well, but I suspect this issue only affects palettes and not text markup with color attributes (if that's the correct way to call it). It looks like colors are being parsed into 24bit values instead of 256 color mode values.

That's palette_test.py on 16 bit mode on Terminal.app:
![image](https://user-images.githubusercontent.com/10780214/79252551-7e6ed200-7e8a-11ea-98d7-a1a533d29622.png)

now 256 bit mode:
![image](https://user-images.githubusercontent.com/10780214/79252679-afe79d80-7e8a-11ea-87a3-8be1f7d2ec29.png)

iTerm2:
![image](https://user-images.githubusercontent.com/10780214/79252736-c130aa00-7e8a-11ea-9ae5-981bc67d4d61.png)

Should I open an issue over there?

**Comment by mhils** [comment] 2020-04-14 19:00
I don't know what I'm doing either, but that does look like an urwid issue. Yes, please do!

**Comment by itaisod** [comment] 2020-04-15 19:36
Update: the issue was fixed and is now merged to master over at urwid.

**Comment by mhils** [comment] 2020-04-15 20:52
Thanks so much @itaisod! :cake: 

@tonycpsu: Do you have an ETA for an urwid patch release? No pressure - I don't think we don't depend on anything in 2.1, we could ship a downgraded patch release in any case. :)

**Comment by mhils** [comment] 2020-04-17 11:09
Small update: We can't easily downgrade to urwid 2.0 due to #3765. But again, we're all doing this as volunteers, so no pressure on the urwid folks. We could monkeypatch if we need to, I have no idea how bad this is in practice. :-)

**Comment by itaisod** [comment] 2020-04-17 17:31
I've experimented with 88 colors mode (`self.ui.set_terminal_properties(88)`). It seems to work not too bad actually! Can it perhaps be configured as a new config option? Maybe use 88 colors instead of 256 when `$COLORTERM` is not `truecolor`?

**Comment by mhils** [comment] 2020-04-17 20:32
Thanks, this is valuable input - maybe we do that as a temporary workaround then.

**Comment by itaisod** [comment] 2020-04-18 15:50
Alright. I'll open a PR when I can.

**Comment by mhils** [comment] 2020-07-16 14:53
We've downgraded urwid to 2.0.1 for now, which should fix this issue. We'll hopefully be back with full color support soon!

**Comment by veehaitch** [comment] 2020-07-27 22:30
FYI: [urwid 2.1.1](https://github.com/urwid/urwid/tree/release-2.1.1) is out and this [should be fixed](https://github.com/urwid/urwid/issues/419#issuecomment-654501374) :)

**Comment by mhils** [comment] 2020-08-27 10:09
Thanks again @veehaitch!

**Closed by mhils** 2020-08-27 10:09 UTC
Labels: area/console, upstream
