### ISSUE TITLE
Crash when repeatedly pressing 'd' on OS X Mavericks

### ISSUE THREAD

**Issue by kylecronin** [mitmproxy/mitmproxy#592] opened 2015-05-23 15:01 UTC
I installed MITMProxy from Homebrew on OS X Mavericks ("brew install mitmproxy"). It works normally most of the time, but it has crashed twice when I have held down the 'd' key for a few seconds to delete some entries in the list. I don't have any clear-cut steps to reproduce because it doesn't happen most of the time.

Here is the stack trace:

    Traceback (most recent call last):
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 614, in run
    self.ui.run_wrapper(self.loop)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/display_common.py", line 757, in run_wrapper
    return fn()
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 845, in loop
    k = self.view.keypress(size, k)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 269, in keypress
    return urwid.ListBox.keypress(self, size, key)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/vendor/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/flowlist.py", line 147, in keypress
    self.state.delete_flow(self.flow)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/console/__init__.py", line 331, in delete_flow
    ret = flow.State.delete_flow(self, f)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 548, in delete_flow
    self.flows._remove(f)
    File "/usr/local/Cellar/mitmproxy/0.11.3/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 462, in _remove
    self._list.remove(f)
    ValueError: list.remove(x): x not in list
    
    mitmproxy has crashed!
    Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
    Shutting down...

**Comment by mhils** [comment] 2015-05-23 19:35
Hi there,

this is probably a duplicate of #437.

Cheers,
Max

**Comment by kylecronin** [comment] 2015-05-23 19:39
OK, no problem, but it looks like the issue in #437 is still happening in 0.11.3, as that's the version I was using.

**Comment by mhils** [comment] 2015-05-23 19:40
Uh oh. Didn't read properly then. Thanks, I'll reopen!

**Comment by cortesi** [comment] 2015-05-25 22:51
Hi there. There have been significant changes since 0.11.3, especially in the console app. I've just released v0.12, and I don't seem to be able to reproduce this - can you please check if you still see it in the latest relese?

**Comment by cortesi** [comment] 2015-05-28 23:37
Fixed in 1a106f4080d89a236a193f2cb007a00aa195a1ad

**Comment by cortesi** [comment] 2015-05-28 23:38
Thanks for reporting this. I'll do a minor point release to address this in the next few days.

**Closed by cortesi** 2015-05-28 23:38 UTC
Labels: bug
