### ISSUE TITLE
Icons not loading in mitmweb - potential fontawesome issue?

### ISSUE THREAD

**Issue by victorhooi** [mitmproxy/mitmproxy#3478] opened 2019-02-14 22:32 UTC
##### Steps to reproduce the problem:

1. Launch mitmweb with `mitmweb --set block_global=false --web-iface 0.0.0.0`.
2. Navigate to port 8081 on the mitmweb IP address.

##### Any other comments? What have you tried so far?

I see square instead of what I assume are fontawesome icons.

<img width="481" alt="screen shot 2019-02-15 at 9 30 07 am" src="https://user-images.githubusercontent.com/243499/52821977-899e6480-3104-11e9-9af8-4f7acc25f8e8.png">

I think this might be similar to https://github.com/mitmproxy/mitmproxy/issues/3397 - and maybe even https://github.com/mitmproxy/mitmproxy/issues/3034 - however, will let developers decide.

##### System information

```
^Cvictorhooi@mitmproxy:~$ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.18.0-1006-gcp-x86_64-with-Ubuntu-18.10-cosmic
```

**Comment by kajojify** [comment] 2019-02-15 00:35
Hello! Thank you for the report. It seems to be duplicate of https://github.com/mitmproxy/mitmproxy/issues/3397

**Closed** 2019-02-20 15:53 UTC
