### ISSUE TITLE
Android nougat chrome "NET_ERR_CERT_AUTHORITY_INVALID"

### ISSUE THREAD

**Issue by Yannik** [mitmproxy/mitmproxy#2821] opened 2018-01-30 02:07 UTC
##### Steps to reproduce the problem:

1. add mitmproxy ca cert to system certificate store as described here: https://github.com/mitmproxy/mitmproxy/issues/2054#issuecomment-327735569
2. Open https site on google chrome for android 63 on android 7.1.2
3. error shows up

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.4
Platform: Linux-4.14.13-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
SSL version: OpenSSL 1.1.0g-fips  2 Nov 2017
Linux distro: Fedora 27 Twenty Seven

**Comment by mhils** [comment] 2018-01-30 16:08
Thanks for the report. I believe this is a duplicate of #2054.

**Closed by mhils** 2018-01-30 16:08 UTC

**Comment by Yannik** [comment] 2018-01-30 17:14
@mhils I explicitly linked #2054 in my bug report. I already applied the proposed fix for #2054. Therefore I don't think it is a duplicate.

**Comment by mhils** [comment] 2018-01-30 17:16
Interception works just fine for me - what specific error are you seeing?

**Comment by Yannik** [comment] 2018-01-31 13:03
@mhils The certificate is not accepted by the client.
