### ISSUE TITLE
mitmdump server playback has very slow requests per second

### ISSUE THREAD

**Issue by macmantrl** [mitmproxy/mitmproxy#529] opened 2015-03-21 18:38 UTC
I have a setup where multiple clients are hitting an instance of mitmdump which is doing server playback. If enough of these clients start connecting, I start to see very slow page loads and sometimes connection resets.

I ran ApacheBench against mitmdump to see what sort of performance I was getting, and it was extremely low, about 340 requests per second on my machine (OS X, 2013 MacBook Pro).

$ mitmdump --no-pop --keepserving --anticache -p8888 -S /tmp/file
$ ab -c20 -n1000 -X '127.0.0.1:8888' -k 'http://simplewebsite/'
Concurrency Level:      20
Time taken for tests:   2.946 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    0
Total transferred:      7454000 bytes
HTML transferred:       7261000 bytes
Requests per second:    339.47 [#/sec] (mean)
Time per request:       58.915 [ms] (mean)
Time per request:       2.946 [ms] (mean, across all concurrent requests)
Transfer rate:          2471.10 [Kbytes/sec] received

If I increase ApacheBench's connection count to 30 or greater, then it just gets 'apr_socket_recv: Connection reset by peer (54)'.

**Comment by macmantrl** [comment] 2015-03-21 18:44
I'd be interested in tackling this if anyone has some suggestions for how to get started.

I already tried switching netlib.tcp.TCPServer to a thread pool (rather than creating a new thread for each connection) which didn't have much effect (which means that maybe it's a good change anyway, performance was the same while using fewer system resources). I also tried creating a pool of workers in controller.Master that all were running their own `tick()` loop and getting items off of the master queue, but that either had no effect or worsened the performance. Multiprocessing seems sort of promising (running 10 processes could increase requests per second to at least 3000) but none of my attempts worked due to tricky problems with pickling.

Maybe the bottleneck is somewhere else, but I'm not that familiar with Python profiling tools.

**Comment by mhils** [comment] 2015-04-08 23:41
Hi @macmantrl,

thanks for raising this question. Sorry that it took a while to respond, your inquiry motivated me to run some tests on my own before replying (https://github.com/mitmproxy/mitmproxy/commit/f37efecd0a22313eacad33251512ef371557fde7). In a nutshell, @cortesi's [post](https://groups.google.com/forum/#!topic/mitmproxy/potC0rzrH6M) on the mailing list is pretty spot on. Load-balancing between several instances is probably the best way to go for now. Did you try pypy? I'd be interested to hear how that plays out.

Cheers,
Max

**Comment by macmantrl** [comment] 2015-04-09 00:27
Thanks for the reply. Yeah, I've tried pypy since I originally posted this and it helps–I get around 800 requests per second vs. 340. I still have issues with 'connection reset by peer' if I do more than about 30 requests at once.

Load balancing seems like a reasonable alternative, especially given that Python will always be limited by its threading model. I was already planning on looking into something like that, although it would still be nice if mitmproxy were a bit faster (for reference I think Flask gets about 3000 req/s on my machine).

I'll take a look at the benchmarking that you added and see if I can find any potential improvements.

**Comment by mhils** [comment] 2015-04-09 12:13
> I still have issues with 'connection reset by peer' if I do more than about 30 requests at once.

Thanks for the pypy reference - that sounds cool.
I can't reproduce the refused connections - 500 concurrent requests are no problem for me. The yappi benchmarks are interesting, but we should look into the threads where most of the work is done. There's a yappi feature for threads I haven't explored yet, https://github.com/vpelletier/pprofile would be another alternative.

Cheers,
Max

**Comment by mhils** [comment] 2015-04-16 16:59
Closing for now - if you find any major bottlenecks, please let us know and we're happy to fix them. Nonetheless, extreme performance won't become a primary goal for mitmproxy.

Cheers,
Max

**Closed by mhils** 2015-04-16 16:59 UTC
