### ISSUE TITLE
https interception while using https proxy failure

### ISSUE THREAD

**Issue by marcosdiazr** [mitmproxy/mitmproxy#4226] opened 2020-10-09 16:38 UTC
#### Problem Description
maybe there is something I'm not getting right, but if using http proxy works then using https proxy should work too

#### Steps to reproduce the behavior:
1. run mitmproxy with default configuration
2. on a terminal run: 
`curl -x https://localhost:8080 https://example.com --proxy-cacert .mitmproxy/mitmproxy-ca-cert.pem --cacert .mitmproxy/mitmproxy-ca-cert.pem -v`
3. I get this error in curl: curl: (56) Received HTTP code 502 from proxy after CONNECT
and this error in mitmproxy logs: 
Cannot connect to server, no server address given.

the thing is that if I use -x http://localhost:8080 (without the s) this works. shouldn't it get the same information from the client no matter if the connection is through http https?
#### System Information
v5.2

**Comment by Prinzhorn** [comment] 2020-10-10 08:09
Duplicate of #4154

> So technically mitmproxy only is an HTTP proxy, not an HTTPS proxy (which is a relatively new concept that includes a second, initial client -> proxy TLS connection). We're working to add that, but TLS-over-TLS is tricky with socket APIs and requires significant changes (#1775).

**Closed** 2020-10-10 10:30 UTC
Labels: kind/triage
