### ISSUE TITLE
Invalid certificate, closing connection. While I did pass --ssl-insecure

### ISSUE THREAD

**Issue by djorkaef** [mitmproxy/mitmproxy#3865] opened 2020-03-22 16:23 UTC
#### Problem Description
Invalid certificate, closing connection. While I did pass --ssl-insecure.
I cannot manage the client device, but I assume the issue is in mitmproxy.

#### Steps to reproduce the behavior:
1.  mitmprocy --mode transparent --showhost --ssl-insecure
2. the moment the blackbox IOT device is connecting:
- warn: 192.168.12.111:xxxxx Certificate verification error for None: (*hostname 'no-hostname' doesn't match either of  '....amazonaws.com", '*.....amazonaws.com".)
- warn: 192.168.12.111:xxxxx Invalid certificate, closing connection. Pass --insecure to disable validation.
- info: 192.168.12.111:xxxxx: clientdisconnect

#### System Information
Mitmprocy: 4.0.4
Python: 3.7.6
OpenSSL: 1.1.1d 10 Sep 2019
Platform: Linux-5.4.0-kali3-amd64-with-debian-kali-rolling

**Comment by djorkaef** [comment] 2020-03-22 18:56
I am not a coder, but am searching in the source code perhaps this helps.
Not sure this is the right place to look.
All I can find in regards to this argument is:


https://github.com/mitmproxy/mitmproxy/blob/e01f044c33aba51d9e5b6053e759b47594ad0855/mitmproxy/net/tls.py#L230

    if sni is None and verify != SSL.VERIFY_NONE:
        raise exceptions.TlsException("Cannot validate certificate hostname without SNI")

https://github.com/mitmproxy/mitmproxy/blob/e01f044c33aba51d9e5b6053e759b47594ad0855/mitmproxy/net/tls.py#L270

    else:
            conn.cert_error = exceptions.InvalidCertificateException(
                "Certificate verification error for {}: {} (errno: {}, depth: {})".format(
                    sni,
                    SSL._ffi.string(SSL._lib.X509_verify_cert_error_string(errno)).decode(),
                    errno,
                    depth
                )


https://github.com/mitmproxy/mitmproxy/blob/e01f044c33aba51d9e5b6053e759b47594ad0855/mitmproxy/net/tls.py#L279

       # SSL_VERIFY_NONE: The handshake will be continued regardless of the verification result.
        return is_cert_verified

**Comment by mhils** [comment] 2020-04-03 15:27
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by djorkaef** [comment] 2020-04-03 20:18
> Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

Thank you for your response. I have install the version 5.0.1 now, but it has the same issue. Please see screenshot here:

[url=https://ibb.co/rbc8RXn][img]https://i.ibb.co/cbCfSsz/mitmproxy-issue-png.png[/img][/url]

**Comment by mhils** [comment] 2020-04-03 21:42
Thanks, this is helpful. I still cannot reproduce the error your are seeing. Does it also happen in regular mode for you, or only in transparent mode?

**Comment by djorkaef** [comment] 2020-04-03 21:48
> Thanks, this is helpful. I still cannot reproduce the error your are seeing. Does it also happen in regular mode for you, or only in transparent mode?

Hi, my transparent mode is perfectly working using a regular windows PC clients with web browsers. no issue. However, when I link my IOT device, which is a blackbox to me and is assumed to be connecting without supplying an SNI, it fails with above errors. It is not possible to configure non-transparent proxy server in that IOT device.

**Comment by Neolo** [comment] 2020-04-06 00:28
Confirming, --ssl-insecure or -k is **NOT being respected** still seeing prompts "Pass --ssl-insecure to disable validation".

**Comment by mhils** [comment] 2020-04-09 06:53
#3908 indicates that this also applies to SOCKS5 mode (which is a bit easier to test), but I unfortunately still can't reproduce this issue.
```
$ mitmdump --mode socks5 --listen-port 1080 --ssl-insecure
$ curl -k --socks5-hostname localhost:1080 https://104.154.89.105
```
works for me as expected. I suspect that this may happen if the client doesn not include a SNI extension in the TLS handshake, but I don't have the resources to confirm this right now.

**Comment by Neolo** [comment] 2020-04-15 00:57
> works for me as expected. I suspect that this may happen if the client doesn not include a SNI extension in the TLS handshake, but I don't have the resources to confirm this right now.

Well, as a bunch of people confirmed it, why don't you simply believe it?
And yes, apparently it's a non-SNI certificate. I don't understand what is the problem to simply ignore SNI expectation? Instead of telling everyone you can't reproduce it.

**Comment by Neolo** [comment] 2020-04-15 01:05
./mitmproxy --mode socks5 --listen-port 1080

clientconnect
Error in HTTP connection: TlsProtocolException("Cannot establish TLS with ************ (sni: None): TlsException('Cannot validate certificate hostname without SNI',)",)
clientdisconnect
clientconnect
Error in HTTP connection: TlsProtocolException("Cannot establish TLS with ************ (sni: None): TlsException('Cannot validate certificate hostname without SNI',)",)
clientdisconnect
clientconnect

**Duuh!**

**Comment by Neolo** [comment] 2020-04-15 01:46
Replace SSL.VERIFY_PEER with SSL.VERIFY_NONE
and 

>         elif is_cert_verified:
>             pass
>         else:
>             pass
> #            conn.cert_error = exceptions.InvalidCertificateException(
> #                "Certificate verification error for {}: {} (errno: {}, depth: {})".format(
> #                    sni,
> #                    SSL._ffi.string(SSL._lib.X509_verify_cert_error_string(errno)).decode(),
> #                    errno,
> #                    depth
> #                )
> #            )
> 
>         # SSL_VERIFY_NONE: The handshake will be continued regardless of the verification result.

and recompile ./dev.sh this way you can get rid of the issue, cuz this is ridiculous.

**Comment by Prinzhorn** [comment] 2020-04-23 05:46
@mhils I did some code review and _might_ have found the offending line

https://github.com/mitmproxy/mitmproxy/blob/3c1a184c5d440e08726d758ba4693f4a51e50433/mitmproxy/net/tls.py#L178

Shouldn't this be

```python
if verify != SSL.VERIFY_NONE
```

It's an integer and will never be `None`, it's even validated in `OpenSSL/SSL.py`: `raise TypeError("mode must be an integer")`

**Comment by decidedlygray** [comment] 2020-05-27 19:26
I was wondering when this fix might make it into the binary releases? Can confirm: with a self-signed upstream cert I am seeing this same issue in transparent mode

**Comment by mhils** [comment] 2020-05-27 19:31
@Prinzhorn may be onto something here, but I haven't had the time to properly look into this. 

If anyone wants to speed up things, instructions on how to reliably reproduce this would be highly appreciated.

**Comment by decidedlygray** [comment] 2020-05-27 22:35
I'll see what I can do in a clean environment. My target is using WebSockets which might be the complication causing a problem. Not sure if the same was true for @djorkaef

**Comment by mhils** [comment] 2020-12-19 10:06
This should be fixed on master. If that's not the case, please open a new issue!

**Closed by mhils** 2020-12-19 10:06 UTC
Labels: area/protocols, kind/bug, kind/triage
