### ISSUE TITLE
TypeError: unorderable types: function() < function()

### ISSUE THREAD

**Issue by krjarvis** [mitmproxy/mitmproxy#3217] opened 2018-06-21 03:20 UTC
##### Steps to reproduce the problem:

The exception happens intermittently, often several thousand requests into a session. I cannot reproduce at-will. The proxy is getting a lot of bad HTTP requests (expected) that cause this warning (or similar) to be displayed:

Warn: 10.137.0.2:52288: HTTP protocol error in client request: Bad HTTP request line:
81\xbb\x80\xa5\x02S;\\\xb7\xd1n\xb1\xcf\xad\xf7k\xb4\xbd\x9f<'

These are flashed in bold below the status bar. I cannot say for sure if it is related.

##### Any other comments? What have you tried so far?

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 242, in ticker
    self.loop.set_alarm_in(0.01, self.ticker)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 165, in set_alarm_in
    return self.event_loop.alarm(sec, cb)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 604, in alarm
    heapq.heappush(self._alarms, (tm, callback))
TypeError: unorderable types: function() < function()

mitmproxy has crashed!

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.2
Platform: Linux-4.13.0-41-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.1.0h  27 Mar 2018
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment] 2018-06-22 22:54
Duplicate of #2815 - upgrading to 4.0 should do the trick.

**Closed by mhils** 2018-06-22 22:54 UTC
