### ISSUE TITLE
setting ssl_insecure: true on mitmproxy.yml doesn't work

### ISSUE THREAD

**Issue by bwowk** [mitmproxy/mitmproxy#2031] opened 2017-02-15 15:06 UTC
##### Steps to reproduce the problem:

1. Create a **mitmproxy.yml** with:
`ssl_insecure: true`
2. Run mitmdump (using docker) with said config:
`docker run -p 8080:8080 -v $(pwd):/config mitmproxy/mitmproxy:1.0.2 mitmdump --conf /config/mitmproxy.yml`
3. Try accessing a site with invalid ssl certificate through the proxy:
`https_proxy=localhost:8080 curl -k https://wrong.host.badssl.com/`

##### Expected result:
```
Certificate Verification Error for wrong.host.badssl.com: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
Ignoring server verification error, continuing with connection
GET https://wrong.host.badssl.com/
               << 200 OK 475b
```

##### Actual result:
```
CONNECT wrong.host.badssl.com:443
 << Certificate Verification Error for wrong.host.badssl.com: hostname 'wrong.host.badssl.com' doesn't match either of '*.badssl.com', 'badssl.com'
```

##### Any other comments? What have you tried so far?

Running with --insecure flag works as expected:
`docker run -p 8080:8080 -v $(pwd):/config mitmproxy/mitmproxy:1.0.2 mitmdump --insecure`

##### System information

mitmdump 1.0.2
Using the [docker hub image](https://hub.docker.com/r/mitmproxy/mitmproxy/) mitmproxy/mitmproxy:1.0.2

**Comment by mhils** [comment] 2017-02-15 15:31
Thanks for the report. This seems to be a duplicate of #1899, so I'm closing this here for now. :)

**Closed by mhils** 2017-02-15 15:31 UTC
