### ISSUE TITLE
transparent -> http-connect/http-relay

### ISSUE THREAD

**Issue by s0i37** [mitmproxy/mitmproxy#4432] opened 2021-02-08 14:20 UTC
#### Problem Description

Old version of `mitmproxy` could converting proxy types. For examples in one commands I can redirect any from transitional traffic (iptalbes) to burp:
`mitmproxy -T -p 8088 --insecure -U http://127.0.0.1:8080`
Also I could converting http->socks. It was very useful for using doesn't support socks protocol programs with tor, like a:
`mitmproxy -p 8088 --insecure -U socks://lo:9050`
But now It anything don't work.
I dont understand that is the strange "improving" of this tool.

#### Proposal
Please return functional for using `mitmproxy` for various types of proxy. Because it is catastrophic disadvantage.

#### Alternatives
Unfortunately I don't know any approaches instead of using old version of this tool.

#### Additional context
Many of pythons tools have SNI or another SSL-errors. But using Burp as upstream proxy could solve this problem. However now I cant use mitmproxy with Burp together.

**Comment by Prinzhorn** [comment] 2021-02-08 16:06
Thanks for reporting this issue. Which version still works and which doesn't? Can you get into details what "anything don't work" means? Do you get an error message?

**Comment by s0i37** [comment] 2021-02-08 16:33
`mitmproxy -p 8088 --ssl-insecure --mode transparent --mode upstream:https://localhost:8080`
HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute,
got: relative)

`mitmproxy -p 8088 --ssl-insecure --mode http --mode upstream:socks://localhost:9050`
Invalid server scheme: socks
Previously `mitmproxy` returned something about forbidden simulteniusly using `http` and `socks` scheme.

Now I can't check which version still work because of py3.7/3.8/3.9 chaos. But I can say that it was versions with syntax like `mitmproxy -T --socks --insecure -U socks://localhost:9050`

**Comment by mhils** [comment] 2021-02-08 16:48
Right - this is something we'll eventually be able to support properly with the new proxy core. This issue seems to be a duplicate of #3845 though, so I'm closing it here. Thanks for the feedback!

**Closed by mhils** 2021-02-08 16:48 UTC
Labels: kind/feature

**Comment by s0i37** [comment] 2021-02-08 17:09
How soon are you planning to implement this?

**Comment by mhils** [comment] 2021-02-08 17:15
I _think_ you can already script this on master by setting `flow.server_conn.via` to a `mitmproxy.net.server_spec.ServerSpec` object, but I haven't tested it. If you are interested in trying it out, we have new work-in-progress API docs at https://github.com/mitmproxy/mitmproxy/pull/4422). How soon is difficult to answer, maybe as part of GSoC over the summer, maybe not. :)
