### ISSUE TITLE
Document supplying sequence parameters through command line or fix parsing cmd arguments

### ISSUE THREAD

**Issue by greatvovan** [mitmproxy/mitmproxy#4509] opened 2021-03-17 00:20 UTC
#### Steps to reproduce the behavior:
1. Pick a parameter that accepts a sequence, e.g. `server_replay_ignore_params`. Try setting more than one value of it (so that you see multiple values in the Options view).
2. `mitmproxy --set server_replay_ignore_params=value1 --set server_replay_ignore_params=value2` (only the latter is saved).
3. `mitmproxy --set server_replay_ignore_params=value1 server_replay_ignore_params=value2` (parsing error).
4. `mitmproxy --set server_replay_ignore_params=value1,value2` (not parsed).
5. `mitmproxy --set "server_replay_ignore_params=['value1','value2']"` (not parsed).

[Options](https://docs.mitmproxy.org/stable/concepts-options/) page provides no clues on the matter.

#### System Information
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit

**Comment by mhils** [comment] 2021-03-19 09:07
Thanks! I believe this is a duplicate of #3015.
The best way to do this right now is to set it in config.yaml, we really need to fix up our cmdline parser. I'll try to write something up in the next few days.

**Closed by mhils** 2021-03-19 09:07 UTC
Labels: kind/triage
