### ISSUE TITLE
Using socks5 in change_upstream_proxy

### ISSUE THREAD

**Issue by emedvedev2015** [mitmproxy/mitmproxy#6259] opened 2023-07-16 07:42 UTC
Mitmproxy: 9.0.1
Python:    3.9.2
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.10.0-17-amd64-x86_64-with-glibc2.31

Hi there,

my command line looks like:
```
mitmproxy -p 6000 --mode upstream:"socks5://proxyservice.com:1231/" --upstream-auth "proxy_service_login:proxy_service;password" --set block_global=false --set connection_strategy=lazy --proxyauth 123123:123123 -s /external_proxy.py
```

external_proxy.py contains script from https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/change_upstream_proxy.py
and it falls down with error:
```
/usr/local/bin/mitmproxy: Invalid proxy mode specification: upstream:socks5://proxyservice.com:1231/ (invalid upstream proxy scheme)
```
I suggest it is because there are no socks specification in the https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/net/server_spec.py

So I have tried to change this file on my server from
```
ServerSpec = tuple[
    Literal["http", "https", "http3", "tls", "dtls", "tcp", "udp", "dns", "quic"],
```
to
```
ServerSpec = tuple[
    Literal["http", "https", "tls", "dtls", "tcp", "udp", "dns", "socks5"],
```
and
```
if scheme not in ("http", "https", "tls", "dtls", "tcp", "udp", "dns"):
```
to
```
if scheme not in ("http", "https", "tls", "dtls", "tcp", "udp", "dns", "socks5"):
```

But error is still the same.

If I will change 'socks5' to 'http' in '--mode upstream' it would works fine. But I need especially socks5 connection.

Please, help me to fix/update this.

**Comment by mhils** [comment] 2023-07-16 09:29
We don't support SOCKSv5 upstream proxies yet, so this is currently not possible. The problem is not so much the server spec but that we need to implement the client side of SOCKS(v5).

**Comment by mhils** [comment] 2023-07-16 09:30
Closing as a duplicate of https://github.com/mitmproxy/mitmproxy/issues/211! :)

**Closed by mhils** 2023-07-16 09:30 UTC
Labels: kind/triage
