### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by fail2010** [mitmproxy/mitmproxy#4277] opened 2020-11-05 10:30 UTC
```
Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "~/.local/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "~/.local/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 1454, in faux_idle_callback
    callback()
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 574, in entering_idle
    self.draw_screen()
  File "~/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 588, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/container.py", line 1090, in render
    focus and self.focus_part == 'body')
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/container.py", line 1090, in render
    focus and self.focus_part == 'body')
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/listbox.py", line 452, in render
    canvas = widget.render((maxcol,))
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 1761, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/urwid/container.py", line 2131, in render
    focus = focus and self.focus_position == i)
  File "~/.local/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "~/.local/lib/python3.7/site-packages/mitmproxy/tools/console/common.py", line 207, in render
    return urwid.TextCanvas([c_text.encode()], [c_attr], maxcol=width)
  File "~/.local/lib/python3.7/site-packages/urwid/canvas.py", line 358, in __init__
    raise CanvasError("Canvas text is wider than the maxcol specified \n%r\n%r\n%r"%(maxcol,widths,text))
urwid.canvas.CanvasError: Canvas text is wider than the maxcol specified
21
[25]
[b'\xe2\x80\xa61": [Errno 111] \xe6\x8b\x92\xe7\xbb\x9d\xe8\xbf\x9e\xe6\x8e\xa5']
```

Mitmproxy: 5.3.0
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.4.0-166-generic-x86_64-with-debian-stretch-sid

**Comment by Kriechi** [comment] 2020-11-07 10:16
Looking at the last lines in the traceback, this should be a simple fix of just limiting the amount/length of text we want to display to `width`.

**Comment by SmallJoker** [comment] 2020-11-10 18:23
I do have the same issue. Is there a patch I could apply?

**Comment by mhils** [comment] 2020-11-13 12:15
Pretty sure this is a duplicate of #2894.

**Closed by mhils** 2020-11-13 12:15 UTC
Labels: kind/triage
