### ISSUE TITLE
Mitmproxy crashes

### ISSUE THREAD

**Issue by Leseratte10** [mitmproxy/mitmproxy#869] opened 2015-12-25 12:15 UTC
As soon as a device tries to access a HTTPS URL, mitmproxy crashes and tells me to lodge a bug report: 

	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 120, in handle
	    root_layer()
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
	    layer()
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 267, in __call__
	    self._establish_tls_with_client_and_server()
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
	    six.reraise(*sys.exc_info())
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
	    self._establish_tls_with_client()
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
	    cert, key, chain_file = self._find_cert()
	  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 497, in _find_cert
	    host = self.server_conn.address.host
	AttributeError: 'NoneType' object has no attribute 'host'

	mitmproxy has crashed!
	Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

This happens with the command line `$ sudo mitmproxy -p 443` and the domain I'd like to intercept has the local IP of my computer set in my DNS server. 

I cannot use the proxy function as my device refuses to use a proxy "for security reasons". 
EDIT: Oops, seems as if this is the same bug as in #861 .
Is there a way to fix that? Directly connecting to MITMproxy without Proxy?

**Comment by mhils** [comment] 2015-12-25 13:33
This looks like a duplicate of #861?

**Comment by Leseratte10** [comment] 2015-12-25 13:35
Yes, I've seen that after I've opened that issue. But I see no way to delete or merge an issue.

**Comment by mhils** [comment] 2015-12-25 13:36
Ok, thanks for clarifying, We can close this one here then.

**Closed by mhils** 2015-12-25 13:36 UTC
