### ISSUE TITLE
`confdir` inconsistencies

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4358] opened 2020-12-15 22:30 UTC
#### Problem Description

This unexpectedly fails:
```
λ mitmdump --set confdir=foo
/home/user/venv/bin/mitmdump: Certificate Authority parent directory does not exist:
```

This works, but also still creates certs in `~/.mitmproxy because confdir is only set after the first addon load:
```
λ mitmdump --set confdir=./foo
Proxy server listening at http://*:8080
```

#### System Information
Mitmproxy: 7.0.0.dev (+204, commit cfe401c)
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27

**Comment by Prinzhorn** [comment] 2020-12-16 08:42
did...did you just create a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4274#issuecomment-722177425 and contradict yourself :thinking: :thinking: :thinking:

**Comment by mhils** [comment] 2020-12-16 08:46
Guess I'm good a forgetting stuff. 😄 
Might be that this is still triggered by old code and will resolve itself once #4349 is in.

**Comment by Prinzhorn** [comment] 2020-12-16 08:47
I was getting some /r/TrumpCriticizesTrump/ vibes, weird :smile:

**Comment by o4x** [comment] 2022-06-14 13:35
Does this issue still exist?

**Comment by 1268** [comment] 2023-08-31 00:40
I think this is fixed. this seems to work as expected:

~~~
mitmproxy --set confdir=foo
~~~

**Closed** 2023-09-23 18:09 UTC
Labels: kind/bug, area/core
