### ISSUE TITLE
MITMdump crashes with ValueError("unserializable object exception while loading page via https 

### ISSUE THREAD

**Issue by du-premraj** [mitmproxy/mitmproxy#2574] opened 2017-09-15 09:02 UTC
##### Steps to reproduce the problem:

1. Ran the mitmdump in reverse proxy mode to intercept https messages and print the host, path and port in the request using an intercepting script
2. Tried to access the web server from chrome browser.
3.While the web page was loading, encountered following exception. Please note that if i don't invoke the mitmdump with script, then the below exception did not occur. 

Ignoring server verification error, continuing with connection
request path, host and ports are :  b'/rest/messaging/cometd/ws' b'<Deleted> 488
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mitmproxy/master.py", line 84, in run
    self.tick(0.1)
  File "/usr/lib/python3.5/site-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/lib/python3.5/site-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mitmproxy/addons/streamfile.py", line 55, in response
    self.stream.add(flow)
  File "/usr/lib/python3.5/site-packages/mitmproxy/io.py", line 63, in add
    tnetstring.dump(d, self.fo)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 66, in dump
    file_handle.write(dumps(value))
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 57, in dumps
    _rdumpq(q, 0, value)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
    size = _rdumpq(q, size, v)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
    size = _rdumpq(q, size, v)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 149, in _rdumpq
    raise ValueError("unserializable object: {} ({})".format(value, type(value)))
ValueError: unserializable object: <WebSocketFlow (0 messages)> (<class 'mitmproxy.websocket.WebSocketFlow'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 126, in mitmdump
    master.run()
  File "/usr/lib/python3.5/site-packages/mitmproxy/tools/dump.py", line 69, in run
    super().run()
  File "/usr/lib/python3.5/site-packages/mitmproxy/master.py", line 86, in run
    self.shutdown()
  File "/usr/lib/python3.5/site-packages/mitmproxy/master.py", line 119, in shutdown
    self.addons.done()
  File "/usr/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 66, in done
    self.invoke_with_context(i, "done")
  File "/usr/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 76, in invoke_with_context
    self.invoke(addon, name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mitmproxy/addons/streamfile.py", line 65, in done
    self.stream.add(flow)
  File "/usr/lib/python3.5/site-packages/mitmproxy/io.py", line 63, in add
    tnetstring.dump(d, self.fo)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 66, in dump
    file_handle.write(dumps(value))
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 57, in dumps
    _rdumpq(q, 0, value)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
    size = _rdumpq(q, size, v)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 142, in _rdumpq
    size = _rdumpq(q, size, v)
  File "/usr/lib/python3.5/site-packages/mitmproxy/contrib/tnetstring.py", line 149, in _rdumpq
    raise ValueError("unserializable object: {} ({})".format(value, type(value)))
ValueError: unserializable object: <WebSocketFlow (0 messages)> (<class 'mitmproxy.websocket.WebSocketFlow'>)

##### System information

mitmdump --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.1
Platform: Linux-2.6.32-573.3.1.el6.x86_64-x86_64-with-centos-6.7-Final
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: MgmtOS 6.7 Final
[root@ci-005056ad472b rpm]#

**Comment by Kriechi** [comment] 2017-09-15 09:06
Duplicate of #2113.
Already fixed by #2114.

**Closed by Kriechi** 2017-09-15 09:06 UTC
