### ISSUE TITLE
Unable to capture request and response in iOS execution using appium and java

### ISSUE THREAD

**Issue by yadsandy** [mitmproxy/mitmproxy#4522] opened 2021-03-22 06:36 UTC
#### Problem Description
I am trying to run my java code from appium script in eclipse and using mitmproxy to capture the requests. Whenever I start the test execution, the eclipse console showing me all the request and response code but it is not capturing in InterceptedMessage.

#### System Information
**The logs which I am receiving on eclipse console:**
[Thread-10] INFO io.appium.mitmproxy.MitmproxyJava - 127.0.0.1:52111: POST https://outlook.office.com/owa/service.svc?action=GetAt… HTTP/2.0
[Thread-10] INFO io.appium.mitmproxy.MitmproxyJava -      << HTTP/2.0 200 OK 1.37k
[Thread-10] INFO io.appium.mitmproxy.MitmproxyJava - 127.0.0.1:52136: clientconnect
[Thread-10] INFO io.appium.mitmproxy.MitmproxyJava - 127.0.0.1:52136: POST https://teams.events.data.microsoft.com/Collector/3.0/?…
[Thread-10] INFO io.appium.mitmproxy.MitmproxyJava -               << 200 OK 0b

**my mitmproxy version**
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1j  16 Feb 2021
Platform:  macOS-11.2-x86_64-i386-64bit

**and the method which I am using to capture the request is:**
	private MitmproxyJava proxy;
	public IOSDriver captureIosSimulatorTraffic(String appLocation)
			throws IOException, InterruptedException, TimeoutException {
		List<InterceptedMessage> messages = new ArrayList<InterceptedMessage>();
		// remember to set local OS proxy settings in the Network Preferences
		proxy = new MitmproxyJava("/usr/local/bin/mitmdump", (InterceptedMessage m) -> {
			System.out.println("intercepted request for " + m.getRequest().getUrl().toString());
			messages.add(m);
			return m;
		});
		proxy.start();
}

**Comment by Prinzhorn** [comment] 2021-03-22 07:24
Unless you can reproduce this using the `mitmweb` or `mitmdump` command line tools I'm afraid we cannot help you and must assume the issue is in https://github.com/appium/mitmproxy-java . I recommend you search for help there.

I'm closing this, feel free to re-open with steps to reproduce this without the Java wrapper.

**Closed by Prinzhorn** 2021-03-22 07:24 UTC
Labels: kind/triage

**Comment by Prinzhorn** [comment] 2021-03-22 07:25
From taking a peek at these projects they seem to require mitmproxy **v4**.
