### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by FreelancePentester** [mitmproxy/mitmproxy#1298] opened 2016-06-28 14:12 UTC
##### Steps to reproduce the problem:

1. 
2. 
3. 

##### What is the expected behavior?
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 345, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 427, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 424, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 433, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 566, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 341, in get_cert
    sans),
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 96, in dummy_cert
    ipaddress.ip_address(i.decode("ascii"))
AttributeError: 'NoneType' object has no attribute 'decode'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/modes/http_proxy.py", line 11, in __call__
    layer()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 345, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 427, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 424, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 433, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/tls.py", line 566, in _find_cert
    return self.config.certstore.get_cert(host, list(sans))
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 341, in get_cert
    sans),
  File "/usr/local/lib/python2.7/dist-packages/netlib/certutils.py", line 96, in dummy_cert
    ipaddress.ip_address(i.decode("ascii"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

##### Any other comments? What have you tried so far?

---

Mitmproxy Version: 0.16
Operating System: Linuxt Mint 18 beta

**Comment by dufferzafar** [comment] 2016-06-28 14:16
Thanks for filing the issue, but can you please provide us with some information regarding what triggered this? Any particular URL you were visiting etc. so that we can reproduce fix this!

**Comment by dufferzafar** [comment] 2016-06-28 14:24
Though I don't have much understanding of the underlying code, I think [this](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/protocol/tls.py#L601) is where the we're inserting a `None` to the `sans` set.

**Comment by mhils** [comment] 2016-06-29 04:38
Thanks @dufferzafar. I believe this is a duplicate of #1025. Please reopen if you still encouter this on 0.17.

**Closed by mhils** 2016-06-29 04:38 UTC
