### ISSUE TITLE
mitmweb Crash 

### ISSUE THREAD

**Issue by JadianZheng** [mitmproxy/mitmproxy#5761] opened 2022-11-27 15:19 UTC
#### Problem Description
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (http://127.0.0.1:8081/static/app.js:7:8533)
    at Object.enqueueSetState (http://127.0.0.1:8081/static/app.js:5:44513)
    at Oc.setState (http://127.0.0.1:8081/static/app.js:1:3945)
    at t.onViewportUpdate (http://127.0.0.1:8081/static/app.js:58:48851)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:48148)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:46203)
    at Yi (http://127.0.0.1:8081/static/app.js:7:1828)
    at dk (http://127.0.0.1:8081/static/app.js:9:5215)
    at Dt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)
    at gg (http://127.0.0.1:8081/static/app.js:5:40220)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:58:45836)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:49804)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)
```

#### Steps to reproduce the behavior:
1.  Open mitmweb
2. Use normal

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.8
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-13.0.1-arm64-arm-64bit

**Comment by Prinzhorn** [comment] 2022-11-27 17:38
This appears to be a duplicate of https://github.com/mitmproxy/mitmproxy/issues/5198 This should be fixed in the latest release, please upgrade to 9.0.1

**Closed by Prinzhorn** 2022-11-27 17:38 UTC
Labels: kind/triage
