### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by akosma** [mitmproxy/mitmproxy#913] opened 2016-02-04 10:39 UTC
##### Steps to reproduce the problem:

Just launched mitmproxy, setup a mobile device to use it as proxy, started browsing the web on the device, this happened:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/local/Cellar/mitmproxy/0.15/libexec/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 497, in _find_cert
    host = self.server_conn.address.host
AttributeError: 'NoneType' object has no attribute 'host'
```

##### What is the expected behavior?
Not crash.

##### What went wrong?
Crash.

##### Any other comments?
Nope.

---
mitmproxy version: 0.15
Operating System: OS X El Capitan 10.11.3

**Comment by mhils** [comment] 2016-02-04 17:03
Thanks for the well-structured report! :smiley:
This looks like a duplicate of #861, which is already fixed.

**Closed by mhils** 2016-02-04 17:03 UTC
