### ISSUE TITLE
mitm proxy won't install

### ISSUE THREAD

**Issue by profhase** [mitmproxy/mitmproxy#633] opened 2015-06-16 09:47 UTC
Installing mitmproxy with `pip install mitmproxy` I am getting the followingerror (pip 7.0.3, ubuntu 12.04, python 2.7):

      File "/home/me/virtualenvs/myvenv/build/mitmproxy/setup.py", line 19

        " netlib>=%s, <%s" % (version.MINORVERSION, version.NEXT_MINORVERSION),

                                                                         ^

        SyntaxError: invalid syntax

**Comment by mhils** [comment] 2015-06-16 14:06
This looks like a duplicate of #573 and #454 - please make sure that you're really using Python 2.7.

Cheers,
Max

**Closed by mhils** 2015-06-16 14:06 UTC
