### ISSUE TITLE
How to capture requests between processes in localhost in transparent mode [MacOS]

### ISSUE THREAD

**Issue by yufengJ** [mitmproxy/mitmproxy#3951] opened 2020-04-22 02:48 UTC
I followed the [howto-transparent](https://docs.mitmproxy.org/stable/howto-transparent/) doc to setup mitmproxy to capture HTTPS requests I sent to a remote server, and it's working great! However, I also hope to capture HTTP/HTTPS requests between a local client an a local server, but was having a hard time figuring out how to configure the `pf.conf` properly. It would be great if I could get some pointers here.

## Enviroment

MacOS Mojave 10.14.6

## Steps to reproduce

Follow [howto-transparent](https://docs.mitmproxy.org/stable/howto-transparent/)  to setup the environment in Mac. (I understand it does not support localhost-to-localhost calls, just want to let you know what I have currently).

```
#The ports to redirect to proxy, added 12345 since my dummy server listens on 12345
redir_ports = "{http, https, 12345}"

#The address the transparent proxy is listening on
tproxy = "127.0.0.1 port 8080"

#The user the transparent proxy is running as
tproxy_user = "nobody"

#The users whose connection must be redirected.
#
#This cannot involve the user which runs the
#transparent proxy as that would cause an infinite loop.
#

rdr pass proto tcp from any to any port $redir_ports -> $tproxy
pass out route-to (lo0 127.0.0.1) proto tcp from any to any port $redir_ports user { != $tproxy_user }
```

Start a local server listening to port 12345

e.g. A sample server in Python 3.7+
```
import http.server
import socketserver

PORT = 12345
Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("localhost", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()
```

Make a GET call to the server
```
curl localhost:12345
```
Received a 502 Gateway from mitmproxy (verified through the command GUI)

```html
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&#x27;Server connection to (\&#x27;127.0.0.1\&#x27;, 56106) failed: Error connecting to &quot;127.0.0.1&quot;: [Errno 61] Connection refused&#x27;)</p>
            </body>
        </html>
```

## Other notes

Currently I have to switch to wireshark to unblock me. But wireshark is 
- a little difficult to track the matching HTTP requests and response
- difficult to setup TLS decryption

I am also hesitant to use regular mode since the actual server and client I am using doesn't allow me to change them easily.

So it would be best if there is way to use mitmproxy solution.

**Comment by mhils** [comment] 2020-04-24 13:28
If you only talk to a single server, why don't you just set up mitmproxy in reverse proxy mode?

**Comment by yufengJ** [comment] 2020-04-29 02:48
Because the application doesn't allow me to configure the client and server port separately. Once configured, both of them uses the same port. That's why i was looking trying to see if we could treat it as blackboxes and intercept the traffic like wireshark did.

Adding more context, the application contains clients within the same server process. The client component could make HTTP requests to the server process. I guess the author never thought people might want to use proxies, hence didn't give the flexibility to configure different port numbers for clients and servers within the same process.

**Comment by mhils** [comment] 2020-04-29 09:20
I see. I have no idea, but if anyone has any recommendations for @yufengJ  please chime in!

Closing this as there's nothing actionable for us here - this is a pfconf question, not a bug in mitmproxy.

**Closed by mhils** 2020-04-29 09:20 UTC
