### ISSUE TITLE
Recording timeout traffic

### ISSUE THREAD

**Issue by nvanbalen** [mitmproxy/mitmproxy#463] opened 2015-01-28 21:52 UTC
Hi guys,

I have been using your tool for a couple months now, and so far, I think it is an amazing tool. It has a very good interface and is easy to use and set up. However, I have encountered a case in which mitmproxy does not provide the functionality I need.

I am working on a use case in which I want to be able to view *all* traffic and connection attempts sent by the client whether the server responds or not. At one point the client makes a connect attempt the a server that results in a connection timed out error (netliberror [error 110]). This gets recorded as an error in the event log but does not show up in the traffic recorded by mitmdump. Would it be possible to have an attempt at a connection that ends up timing out get recorded with the rest of the traffic? 

Thanks for all the work. Your tool is really awesome.

**Comment by mhils** [comment] 2015-02-03 15:55
Hi there,

thanks for the report! Unfortunately, @cortesi and I are fairly busy right now. We'll certainly get back to your issue, but it may take a bit - sorry for that.

Cheers,
Max

**Comment by mhils** [comment] 2015-02-05 15:53
Hi @nvanbalen,

I believe this is a duplicate of #108.

Cheers,
Max

**Closed** 2015-02-05 16:13 UTC
