### ISSUE TITLE
mitmproxy crashes:  module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

### ISSUE THREAD

**Issue by jdmevo123** [mitmproxy/mitmproxy#4143] opened 2020-08-11 04:06 UTC
#### Problem Description
Mitm proxy is crashing with module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

#### Steps to reproduce the behavior:
1. Start mitmdump
2. Access traffic through the proxy
3. Crash occurs

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 103, in __call__
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 203, in __call__
    if not self._process_flow(flow):
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 276, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 221, in handle_regular_connect
    layer()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 448, in _establish_tls_with_server
    **args
  File "/usr/lib/python3.6/site-packages/mitmproxy/connections.py", line 292, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 388, in convert_to_tls
    **sslctx_kwargs
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tls.py", line 290, in create_client_context
    SSL._lib.X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS | SSL._lib.X509_CHECK_FLAG_NEVER_CHECK_SUBJECT
AttributeError: module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

```

**Comment by Prinzhorn** [comment] 2020-08-11 06:20
Duplicate of https://github.com/mitmproxy/mitmproxy/issues/4078

> According to pyca/cryptography#4492, the problem is your outdated OpenSSL version. So you'd need to update that. I'm closing this here as it's not really a mitmproxy bug. :)

**Comment by mhils** [comment] 2020-08-12 07:46
Thanks @Prinzhorn!

**Closed by mhils** 2020-08-12 07:46 UTC
Labels: kind/triage
