### ISSUE TITLE
mitmweb UI crashes

### ISSUE THREAD

**Issue by areebbeigh** [mitmproxy/mitmproxy#5335] opened 2022-05-10 12:12 UTC
#### Problem Description
mitmweb UI crashes with the following message:

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (http://127.0.0.1:8081/static/app.js:7:8533)
    at Object.enqueueSetState (http://127.0.0.1:8081/static/app.js:5:44513)
    at t.kc.setState (http://127.0.0.1:8081/static/app.js:1:3945)
    at t.onViewportUpdate (http://127.0.0.1:8081/static/app.js:58:46527)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:45824)
    at t.componentDidUpdate (http://127.0.0.1:8081/static/app.js:58:43879)
    at Yi (http://127.0.0.1:8081/static/app.js:7:1828)
    at dk (http://127.0.0.1:8081/static/app.js:9:5215)
    at Mt.unstable_runWithPriority (http://127.0.0.1:8081/static/app.js:1:12961)
    at gg (http://127.0.0.1:8081/static/app.js:5:40220)

Component Stack:
    at AutoScrollWrapper (http://127.0.0.1:8081/static/app.js:58:43512)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:47480)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)
```

#### Steps to reproduce the behavior:
In my case, I am running [Proxifier](http://www.proxifier.com/) and `mitmweb --mode socks5`. There's a lot of raw TCP requests logged when the crash happens.

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 8.0.0
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  macOS-12.2.1-arm64-arm-64bit
```

**Comment by mhils** [comment] 2022-05-15 14:32
Thanks for the report! Very likely a duplicate of #5198. :)

**Closed by mhils** 2022-05-15 14:32 UTC
Labels: kind/triage
