### ISSUE TITLE
Handle protocols that start with a server greeting

### ISSUE THREAD

**Issue by flydave** [mitmproxy/mitmproxy#1774] opened 2016-11-22 10:32 UTC
I've tried using mitmdump 0.18.2 for POP3S and IMAP4S. In both of these protocols the client connects and then the server sends greeting. Then the client sends command(s) and the server responds. Additionally, in IMAP4 the server can send unsolicited responses at any time. (Unsolicited means responses which are not caused by a direct client command).

##### Steps to reproduce the problem:

I've tried with:
1. mitmdump --insecure --stream 0 --transparent --tcp '.*'
2. mitmdump --insecure --stream 0 --transparent --raw-tcp

Both of these act the same: TLS MITM is correctly performed and the server sends a greeting. But mitmdump doesn't forward it to the client. Instead it sits and waits for the client to send something. But the client will not send anything because it's waiting for the server greeting.

If I use telnet as a client I can press enter which will cause the client to send something. mitmdump will forward that to the server and then it will forward server's greeting to the client. And after that it will forward server's response to the client's request (just CRLF if I only pressed enter), which will normally be an error response.

After that I can use the connection because now we'll be in the mode which mitmdump expects. However, that can only be initiated from the telnet session. Normal mail clients will hang while waiting for the server greeting. And I suspect that unsolicited IMAP4 server messages won't be forwarded to the client until the client sends something.

Is there a command line option I've missed that would cause mitmdump to forward server's stream regardless of what client sends?

Failing that, can that mode of operation be implemented?

##### System information

Mitmproxy version: 0.18.2
Python version: 2.7.12
Platform: Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment] 2016-11-22 13:42
Thanks for the report. This is caused by our implementation of [`_next_layer`](https://github.com/mitmproxy/mitmproxy/blob/92516a3b5c3e3ea8e2c7d5a92373f3ebbc4aa681/mitmproxy/proxy/root_context.py#L43), where we peek in the client connection to determine the next protocol.
To be honest, there's really no good way to do that with the current infrastructure. We may get away by just peeking with a timeout, but that of course implies that all connections with server greeting have an initial delay. I have manually patched `_next_layer` previously to perform IMAP interception, but that is not a great solution either obviously.

**Comment by davemaleni** [comment] 2016-11-23 08:33
I suspected that peeking would be the cause of the problem. I'm not quite sure what's the difference between --tcp and --raw-tcp. Issue #866 has an explanation at the end, but I'm not sure if that's still completely correct. If it is, then --tcp shouldn't be trying to guess the next protocol, so there shouldn't be any peeking after SSL is handled.

If both --tcp and --raw-tcp are supposed to be peeking then you could add another option which doesn't try to guess the next protocol after SSL interception is done. That would push the burden of determining the protocol to the user, but that's a lot better than nothing.

The _next_layer implementation is first trying to peek and then the check for the --tcp option is the distant 5th (the comment incorrectly states 4th :-) I'm not sure why it's coded this way if the explanation from #866 is correct.

And another question. If we get past the initial peeking problem somehow, would the current code be able to handle IMAP's unsolicited messages correctly? That is, will it send them to the client without waiting for the client to send something first?

**Comment by mhils** [comment] 2016-12-17 01:50
Sorry, somehow missed your reply.

> I'm not sure why it's coded this way if the explanation from #866 is correct.

Let's be honest: The whole thing is fairly messy right now, apologies. :-/ `--tcp` comes as the fourth option because we do TLS detection beforehand, which requires us to check if what the client sends might be a TLS ClientHello.

> would the current code be able to handle IMAP's unsolicited messages correctly?

I hard a similar issue a while ago and hardcoding the layer fixed the issue for me, so yes, everything else should work.

Looking further ahead, I believe the correct way to handle things would be to wait for the first packet from either the client or the server and decide what to do based on that.

**Comment by jtpereyda** [comment] 2020-09-30 00:00
Attempting this on v5.2, it seems to me that mitmproxy is waiting for a request from the client before actually connecting to the server (at least in my setup). That's just based on a tcpdump.

@mhils do you have any advice on how to manually patch _next_layer for this use case?

**Comment by jtpereyda** [comment] 2020-09-30 00:30
This patch works OK when not using TLS (starting from repo commit eb71985d26b5559d99b55d47176d3e31e39bb4bb):
```patch
diff --git a/mitmproxy/proxy/root_context.py b/mitmproxy/proxy/root_context.py
index 3d4e8660..4dc0e82f 100644
--- a/mitmproxy/proxy/root_context.py
+++ b/mitmproxy/proxy/root_context.py
@@ -43,10 +43,11 @@ class RootContext:
 
     def _next_layer(self, top_layer):
         try:
-            d = top_layer.client_conn.rfile.peek(3)
+            pass
+            # d = top_layer.client_conn.rfile.peek(3)
         except exceptions.TcpException as e:
             raise exceptions.ProtocolException(str(e))
-        client_tls = tls.is_tls_record_magic(d)
+        client_tls = False  # tls.is_tls_record_magic(d)
 
         # 1. check for filter
         if self.config.check_filter:
```

**Comment by mhils** [comment] 2023-09-10 22:36
This is fixed nowadays. 🚀

**Closed by mhils** 2023-09-10 22:36 UTC
Labels: kind/feature, area/protocols
