### ISSUE TITLE
Mitmproxy Installation Errors

### ISSUE THREAD

**Issue by JPS46225** [mitmproxy/mitmproxy#612] opened 2015-06-07 08:45 UTC
This is the new issue page for installation errors while installing Mitmproxy on Windows

**Comment by JPS46225** [comment] 2015-06-07 11:08
Here is the newest command prompt output for 'Pip install mitmproxy'

Collecting mitmproxy
  Using cached mitmproxy-0.12.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyperclip>=1.5.8 in c:\python27\lib\site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>0.1.2 in c:\python27\lib\site-packages (from mitmproxy)
Collecting tornado>=4.0.2 (from mitmproxy)
  Using cached tornado-4.2.tar.gz
Collecting netlib<0.13,>=0.12 (from mitmproxy)
  Using cached netlib-0.12.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\netlib.egg-info
    writing requirements to pip-egg-info\netlib.egg-info\requires.txt
    writing pip-egg-info\netlib.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\netlib.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\netlib.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\netlib.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    running build_ext
    building '_cffi__x88a8fd90x94e38fe2' extension
    creating c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\netlib\__pycache__\Release
    creating c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\netlib\__pycache__\Release\netlib
    creating c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\netlib\__pycache__\Release\netlib\__pycache__
    C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcnetlib\__pycache__\_cffi__x88a8fd90x94e38fe2.c /Foc:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\netlib\__pycache__\Release\netlib\__pycache__\_cffi__x88a8fd90x94e38fe2.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    _cffi__x88a8fd90x94e38fe2.c
    netlib\__pycache__\_cffi__x88a8fd90x94e38fe2.c(208) : fatal error C1083: Cannot open include file: 'openssl/rsa.h': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\setup.py", line 87, in <module>
        "install": CFFIInstall,
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 207, in find_sources
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 291, in run
      File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 320, in add_defaults
      File "build\bdist.win32\egg\setuptools\command\sdist.py", line 118, in add_defaults
      File "C:\Python27\lib\distutils\cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "build\bdist.win32\egg\setuptools\command\build_py.py", line 28, in finalize_options
      File "C:\Python27\lib\distutils\command\build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "C:\Python27\lib\distutils\cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\setup.py", line 27, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "c:\users\admini~1\appdata\local\temp\pip-build-2drif6\netlib\setup.py", line 20, in get_ext_modules
        from netlib import certffi
      File "netlib\certffi.py", line 20, in <module>
        extra_compile_args=['-w']
      File "C:\Python27\lib\site-packages\cffi\api.py", line 373, in verify
        lib = self.verifier.load_library()
      File "C:\Python27\lib\site-packages\cffi\verifier.py", line 96, in load_library
        self._compile_module()
      File "C:\Python27\lib\site-packages\cffi\verifier.py", line 192, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 38, in compile
        outputfilename = _build(tmpdir, ext)
      File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 65, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by elitest** [comment] 2015-06-07 14:19
Yeah I have been having problems doing fresh installs lately.  From what I have seen I think it may be related to CFFI being updated to 1.0+.  CFFI is a dependency of several dependencies of mitmproxy, and currently things like the package [cryptography](https://github.com/pyca/cryptography) do not yet support CFFI 1.0(but they are very actively working on it).  Can anyone else confirm?

**Comment by JPS46225** [comment] 2015-06-08 00:05
Hi elitest

Are you saying that Cryptography is relatively new?

**Comment by JPS46225** [comment] 2015-06-08 00:06
Hi elitest

Also, do you know of any workarounds?

**Comment by elitest** [comment] 2015-06-08 02:40
I think the previous release of cffi was 0.8.5 or something.  Try ``pip install cffi==0.8`` or ``pip install cffi==0.8.5``.

**Comment by JPS46225** [comment] 2015-06-08 02:56
Alright, i'll uninstall cffi, then install cffi 0.8/0.8.5

**Comment by JPS46225** [comment] 2015-06-08 05:08
Hi elitest

I've managed to install mitmproxy version 0.11, but I'm having trouble starting it, any ideas?

**Comment by elitest** [comment] 2015-06-08 15:40
What specifically is happening?

**Comment by JPS46225** [comment] 2015-06-09 01:12
Hi elitist

I managed to open mitmproxy, by doing this in Command Prompt

cd C:\Python27\Scripts
python.exe mitmdump

It's not the same to how I've seen it on YouTube, but I guess it's better than nothing

0.12.1 won't allow the same method because it won't install

**Comment by syst3mw0rm** [comment] 2015-06-09 02:22
@JPS46225 Can you link to the video here? It seems like it is outdated and you should probably follow latest installation instructions.

**Comment by JPS46225** [comment] 2015-06-09 03:33
Hi

This is the video I looked at, this may be because it's on an iMac, all I know is that the Mitmproxy on my computer is harder to use

**Comment by JPS46225** [comment] 2015-06-09 03:34
And if I try to install Mitmproxy 0.12.1, the above command prompt outputs will appear

**Comment by JPS46225** [comment] 2015-06-09 10:05
I will get to uploading the video url soon, in the meantime, does anyone know how I can check for errors in Python? e.g.: Corruption of files that have or have been partially downloaded.

**Comment by JPS46225** [comment] 2015-06-10 02:41
Hi

This is the video that I was referring to, like I said, it's running on a Mac, but hopefully you get the idea...

http://youtu.be/7c0mA00is0I

**Comment by elitest** [comment] 2015-06-10 13:55
So looking at your question again, you say "It's not the same to how I've seen it on YouTube, but I guess it's better than nothing" after having run ``mitmdump``.  That is because ``mitmproxy`` as seen on the video you linked only works on Linux and OS X due to its ncurses interface.  ``mitmproxy`` does not run under Windows at this time, the only tool in the ``mitmproxy`` family that you can run under Windows is ``mitmdump``.  Please see the [documentation](http://mitmproxy.org/doc/mitmproxy.html) for more details.

**Comment by JPS46225** [comment] 2015-06-11 06:17
Ok, also, what about the problems with upgrading to 0.12.1?

**Comment by JPS46225** [comment] 2015-06-11 06:19
Also, what about upgrade problems with 0.12.1?

**Comment by JPS46225** [comment] 2015-06-11 06:19
Oops, Internet error

**Comment by JPS46225** [comment] 2015-06-11 06:20
Also, what about checking Python for errors such as corruption on fully downloaded or partially downloaded files

**Comment by JPS46225** [comment] 2015-06-11 08:43
YESSSS, don't know what I did, but it finally wants to install!!!

**Comment by JPS46225** [comment] 2015-06-11 08:50
Hmm, hang on, now it doesn't want to load at all, restarting pc

**Comment by elitest** [comment] 2015-06-11 13:15
What is the output when you attempt to run it?

**Comment by JPS46225** [comment] 2015-06-12 01:46
Hi elitest

After reinstalling netlib and mitmproxy, it seems to work fine

**Comment by JPS46225** [comment] 2015-06-12 01:47
But it was saying something along the lines of 'no module called netlib

**Comment by cortesi** [comment] 2015-06-12 01:50
Chaps, in the interest of keeping this ticket focused enough to be actionable - do you still feel the initial CFFI error is a bug that needs to be addressed?

**Comment by JPS46225** [comment] 2015-06-12 01:58
Not sure, as the cffi package error happened when I was first trying to install mitmproxy. However, if this bug still exists, then something will probably have to be done about it. I was able to fix it by installing packages, which some of them were a waste of space, but I don't know which packages, solved the problem, I might try deleting and reinstalling Python, take note of which ones were necessary to mitmproxy and ones that I don't need for mitmproxy

**Comment by JPS46225** [comment] 2015-06-12 02:01
Anyway, here are the URLs for Foxtel Go and Foxtel Play

http://win-cdn220-is-7.se.fxmultihlslive6258.ngcdn.telstra.com/channel001/channel001215.m3u8

https://foxtelgo.d2.sc.omtrdc.net/b/ss/foxtelgoproduction/0/OIP-3.0.0/s34271842?AQB=1&ndh=1&t=11/5/2015%2019%3A39%3A45%204%20-600&c.&eVar48=News%20%26%20Documentaries&eVar19=14&eVar33=7200&eVar71=Joshua%20P%20Stokes%27%20iPad&eVar1=1434015586&eVar5=d41d8cd98f00b204e9800998ecf8427e&eVar9=8.4&eVar10=IOS&eVar12=NOT%20CELLULAR&eVar2=PLAY&eVar14=2015-04-23T19%3A50%3A15&eVar21=48&eVar16=5&eVar30=GoLive&eVar6=NOLOGIN&eVar25=livetab&eVar23=830cc6973aad7313ccd970ca869af7b71fbc3072&eVar18=45&eVar41=Streaming&eVar34=5&eVar43=SKY&eVar36=0&eVar38=true&eVar50=2015-06-11T18%3A00%3A00&eVar47=News%20%26%20Documentaries&eVar70=2.9.3&eVar49=NC&a.&DeviceName=iPad5%2C3&Resolution=2048x1536&OSVersion=iOS%208.4&CarrierName=%28null%29&.a&eVar32=Reporting%20LIVE%20with%20Stan%20Grant&eVar45=SKY67812077&eVar3=event25&eVar7=iPad5%2C3&c44=NOTASSET&c45=HWW5925502&eVar11=Wifi&eVar13=2.9.3&eVar20=1&eVar4=2&eVar15=19&eVar22=0&eVar17=14&eVar31=8ec12b4a2b3eb038eec102d365f68c10ecfd8880&eVar8=e3f5536a141811db40efd6400f1d0a4e&eVar40=LIVE&eVar24=e3100bcf903ab81ac3bb9df9adc1b5ba&eVar42=SD&eVar35=0&eVar44=NOTASSET&eVar37=5&eVar51=T02%3A00%3A00&eVar46=Reporting%20LIVE%20with%20Stan%20Grant&.c&vid=4DF6024E0F6D6045AE0A7A20085240F5E987&ce=UTF-8&events=event25&pe=lnk_o&cc=AUD&pev2=foxtel-go-iPad/2.9.3%20Event&pageName=foxtel-go-iPad/2.9.3&AQE=1​

http://win-cdn220-is-9.se.fxmultihlslive6258.ngcdn.telstra.com/c
hannel001/channel001290/02928/channel00129020150611T093900_00046.ts​

http://win-cdn220-is-9.se.fxmultihlslive6258.ngcdn.telstra.com/c
hannel001/channel001290.m3u8?SIGV=2&IS=0&ET=1434026109&KO=7&KN=2&US=445dfee6131d
468a6b5177dcfbe4bccc1e2c2f41

Please let me know what you guys think.

**Comment by JPS46225** [comment] 2015-06-12 02:09
I'm trying to uninstall all pip packages, so that I can try this thing that I mentioned 2 comments ago

**Comment by cortesi** [comment] 2015-06-12 03:07
Hi there. I'm going to close this ticket for now, because it doesn't seem easily actionable. We need bug reports to contain a single, clearly defined, reproducible issue. It seems that there might be something to look at with CFFI installation, but we need a Windows-using dev to reproduce it (cc @mhils?).

**Closed by cortesi** 2015-06-12 03:07 UTC
Labels: question

**Comment by sajid-dsi** [comment] 2015-06-15 18:20
Hi @JPS46225 ,
I'm trying to install mitmproxy but facing the following error:

WindowsError: [Error 5] Access is denied: 'c:\\users\\phoenix\\appdata\\local\\te
mp\\easy_install-_8ekad\\cryptography-0.9.1\\.eggs\\cffi-1.1.2-py2.7-win32.egg\\
_cffi_backend.pyd'

Did you face the issue during your installation? I faced your problem once before installing vcpython27, but later it didn't happen again. I'm stuck with this issue for last couple of days. I'm running the command prompt in administrator mode but no use. Could you please let me know the steps you followed for the installation?? That'd be a big help for me.

Thanks in advance!

**Comment by elitest** [comment] 2015-06-15 19:32
Yeah I just tried this on a fresh windows VM.  I also had to install [Microsoft Visual C++ Compiler for Python 2.7](http://www.microsoft.com/en-us/download/details.aspx?id=44266)(Docs should be updated with this omission).  Based on the output from the installer it looks like easy_install is trying to run a function called ``auto_chmod`` on 1609 of ``C:\Python27\Lib\site-packages\setuptools\command\easy_install.py``.  Poking around this file a bit it looks like ``auto_chmod`` is called ``onerrer=auto_chmod`` as part of a function ``rm_tree``.  This is meant to recursively delete directories as part of the install process.  I took a look ``_cffi_backend.pyd`` and the file and folders in question are editable by my user and administrators, so the access denied is something else.  Is this a bug in setuptools?

[here is more details](https://gist.github.com/elitest/5ffbe8e408d29976fd3a)

**Comment by JPS46225** [comment] 2015-06-15 23:39
Hi sajid-dsi

Thanks for posting your question. I haven't come up with a final conclusion as to how I got it to work, but here are the steps which I undertook to get it to work.

1. Update all dependencies/requirements for netlib, since netlib is a major requirement for mitmproxy. This can be done by entering, 'pip install netlib=0.11'. Output will probably say that all requirements already satisfied, however, manually update (--update) all of the requirements that are outputed by the command

e.g.: downloading/using cached *.tar.gz, requirement already up-to-date (use --upgrade)
pip install * --upgrade

Make sure to install version 0.11 instead of the latest version

Do the same with Cryptography, just to be sure of any compatibility issues

Once you do this, install GitBash (https://msysgit.github.io/)

Then run these commands

pip uninstall mitmproxy netlib
git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
pip install --src . -r requirements.txt

Please let me know how you go with that and please paste in any error output that you encounter while following my steps

**Comment by JPS46225** [comment] 2015-06-15 23:43
Also Make sure that Visual Studio 2010 is installed and http://www.microsoft.com/en-au/download/details.aspx?id=44266

**Comment by mhils** [comment] 2015-06-15 23:44
I just finished packaging a Windows wheel (Python 32-bit only for now) for netlib, which @cortesi will upload to pypi later today. Once that is up, `pip install mitmproxy` will just work again.

If you are very impatient, you can `pip install https://maximilianhils.com/upload/2015-06/netlib-0.12.1-cp27-none-win32.whl` at your own risk.
(SHA256: `f053a140ff91b914a5de663de3c41191bc22157a693a2fa8308e0d822af308f4`)

Cheers,
Max

**Comment by JPS46225** [comment] 2015-06-15 23:45
Also, I will paste site packages that I've installed for Python 2.7 as well. No packages have been installed since I realised that mitmproxy was working

**Comment by JPS46225** [comment] 2015-06-15 23:46
thanks @mhils

I'll try it tonight, anyone on this forum, can still follow my instructions if they want to (what do you think @mhils)

**Comment by mhils** [comment] 2015-06-15 23:49
@JPS46225: We don't want anyone to use old mitmproxy versions unless they have a very specific requirement to do so (old dumpfiles). I'd strongly recommend to either install the wheel from my server as described above or just wait a couple of hours.

**Comment by cortesi** [comment] 2015-06-16 00:21
@JPS46225 The wheel has now been uploaded. Install away.

**Comment by JPS46225** [comment] 2015-06-16 00:27
Ok, hopefully will do in 6 hours. I'll still upload my site packages list, just to confirm if there is any packages which are unnecessary to mitmproxy, it's the main reason why I installed Python

**Comment by JPS46225** [comment] 2015-06-16 00:28
Also, is there a command that I can use to erase all dependencies installed by 'Pip' in one go?

**Comment by JPS46225** [comment] 2015-06-16 00:33
Also, can someone please explain this documentation, I'm so confused...
http://mitmproxy.org/doc/features/responsestreaming.html

**Comment by sajid-dsi** [comment] 2015-06-16 18:16
Hi @JPS46225 , 
I've tried with the latest update for 32bit python & finally been able to install it!!!! 
Thanks for your response though & also thanks a lot @mhils for the latest update.

**Comment by JPS46225** [comment] 2015-06-16 22:30
No probs sajid-dsi

**Comment by JPS46225** [comment] 2015-06-16 22:31
Has anyone found a command to delete all pip yet?

**Comment by JPS46225** [comment] 2015-06-16 22:32
All pip packages yet.

**Comment by JPS46225** [comment] 2015-06-18 01:07
Should I just assume that there is no command for deleting all installed pip packages all at once or does no-one know if there is/what it is?

**Comment by syst3mw0rm** [comment] 2015-06-18 14:42
http://stackoverflow.com/a/11250821/789774

**Comment by pwillia7** [comment] 2015-07-16 19:57
Any updates to this guys? I'm running 64bit and am still getting errors using pip install mitmproxy. The problem appears to be something with netlib... I'm getting the same openssl/rsa.h error

**Comment by sajid-dsi** [comment] 2015-07-16 20:00
Please install python for 32bit, then run ‘pip install mitmproxy’. This is how I’m running mitmproxy in my 64bit windows machine.

**Comment by mhils** [comment] 2015-07-21 23:13
We just pushed the 0.13 release which works fine on x32 and x64 Python.
