### ISSUE TITLE
How can we add an add-on as a list in python?

### ISSUE THREAD

**Issue by thanhtan27081998** [mitmproxy/mitmproxy#4286] opened 2020-11-09 18:13 UTC
In other to add an add-on variable as a string we can define the typespec as typing.Optional[str] and run command mitmdump --scripts ./log.py --set path='./content/' 
However, how can we define and which command should we run if we want the add on variable to be a List in python?

**Comment by Prinzhorn** [comment] 2020-11-10 07:25
Do you mean like this?

https://github.com/mitmproxy/mitmproxy/blob/e0c07d17556dc5a4a723f7b6be61f68b6e5c1553/mitmproxy/options.py#L66-L75

**Comment by thanhtan27081998** [comment] 2020-11-10 07:27
> Do you mean like this?
> 
> https://github.com/mitmproxy/mitmproxy/blob/e0c07d17556dc5a4a723f7b6be61f68b6e5c1553/mitmproxy/options.py#L66-L75

Yes, but which command should I run in other to pass in a list sir ?

**Comment by Prinzhorn** [comment] 2020-11-10 07:41
In theory you use `--set` multiple times. But it looks like that's broken.

You can update the option inside the addon, but not via the cli arguments 

```
ctx.options.update(
    foo        = ["1", "2", "3"]
)
```

Closing as duplicate of #3015

**Closed by Prinzhorn** 2020-11-10 07:41 UTC
Labels: area/addons, kind/question

**Comment by thanhtan27081998** [comment] 2020-11-10 18:45
I'm creating an addon which accept two params including a string and an array of string as bellow
```
def load(self, loader):
        loader.add_option(
            name = "path",
            typespec = typing.Optional[str],
            default = None,
            help = "Add a path for directory",
        )
        loader.add_option(
            name = "ignored_list",
            typespec = typing.Sequence[str],
            default = None,
            help = "Add a ignored list",
        )
```
But i don't know which command should I run in other two pass in those two arguments

**Comment by Prinzhorn** [comment] 2020-11-11 06:05
`--scripts ./log.py --set black_list=foo --set black_list=bar` but like I said there's a bug and you will only receive one of them in your list. You can subscribe to #3015
