### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

### ISSUE THREAD

**Issue by wadjsnkk** [mitmproxy/mitmproxy#4078] opened 2020-07-11 12:02 UTC
#### Problem Description
This error is reported when I use mitmWeb or mitmproxy to start and use the proxy (I have installed and trusted the mitm.it certificate)
#### Steps to reproduce the behavior:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 262, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 208, in handle_regular_connect
    layer()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 448, in _establish_tls_with_server
    **args
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/connections.py", line 292, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 386, in convert_to_tls
    **sslctx_kwargs
  File "/usr/local/lib/python3.6/site-packages/mitmproxy/net/tls.py", line 290, in create_client_context
    SSL._lib.X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS | SSL._lib.X509_CHECK_FLAG_NEVER_CHECK_SUBJECT
AttributeError: module 'lib' has no attribute 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

#### System Information
device:NanoPi_NEO_Plus2 (http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO_Plus2)
Mitmproxy: 5.1.1
Python:    3.6.1
OpenSSL:   OpenSSL 1.0.2g  1 Mar 2016
Platform:  Linux-4.11.2-aarch64-with-debian-kali-rolling

**Comment by mhils** [comment] 2020-07-11 12:32
How did you install mitmproxy? This looks like your version of `cryptography` is outdated.

**Comment by wadjsnkk** [comment] 2020-07-11 12:36
> How did you install mitmproxy? This looks like your version of `cryptography` is outdated.

"pip3 install mitmproxy"  How should I solve this problem?

**Comment by mhils** [comment] 2020-07-11 12:38
According to https://github.com/pyca/cryptography/pull/4492, the problem is your outdated OpenSSL version. So you'd need to update that. I'm closing this here as it's not really a mitmproxy bug. :)

**Closed by mhils** 2020-07-11 12:38 UTC
Labels: kind/triage

**Comment by quydox** [comment] 2020-08-11 09:36
Hello, I update OpenSSL to OpenSSL 1.1.1g  21 Apr 2020 (Library: OpenSSL 1.1.1d  10 Sep 2019)

But the same error occurs

Can you help me?

**Comment by mhils** [comment] 2020-08-11 13:36
I assume your output of `mitmproxy --version` still lists your old OpenSSL version? You need to have `cryptography` installed with the proper version.
