### ISSUE TITLE
gRPC protocol: supporting empty responses

### ISSUE THREAD

**Issue by meiraxx** [mitmproxy/mitmproxy#5890] opened 2023-01-25 13:53 UTC
#### Problem Description

MITMProxy mishandles empty gRPC responses, by performing an `assert`, giving out this error: `AssertionError: Unexpected event: ResponseTrailers(stream_id=1, trailers=Headers[(b'grpc-status', b'0'), (b'grpc-message', b'')])`.

This is an ensured mishandling of the gRPC response because the gRPC client is able to support empty gRPC messages, as long as it is properly handled at the application level.

#### Steps to reproduce the behavior:

1. Create a `responseheaders` handler with the following code:
```python
def responseheaders(flow: http.HTTPFlow) -> None:
        if flow.response.headers.get('content-type', '').startswith('application/grpc'):
                if (not flow.response.content) or len(flow.response.content) == 0:
                    ctx.log.info(f"gRPC empty response caught in {flow.request.path}. Correct action is to simply ignore it.")
                else:
                    ctx.log.info("Normal gRPC response.")
```
2. Simply perform a request to an endpoint that responds with an HTTP header "content-type:application/grpc", but with no content. This will trigger the `AssertionError`.

#### System Information

```
Mitmproxy: 9.0.1
Python:    3.10.9
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-13.1-arm64-arm-64bit
```

**Comment by LaiKash** [comment] 2023-01-25 15:03
I can confirm the same issue and behaviour.

**Comment by mhils** [comment] 2023-01-25 15:05
Can you please post a full traceback?

**Comment by meiraxx** [comment] 2023-01-25 15:27
The first step is just so you can see where the error occurs (within the condition `(not flow.response.content) or len(flow.response.content) == 0`), and the second step is the conditions in which it occurs (sorry, I'm not able to disclose the exact endpoint with which I'm working, so there's the need to reproduce this with a custom gRPC service).

I think this is something you guys would like to better support, and since it's an `AssertionError` it could simply mean removing an `assert` call.

### As requested, a full traceback

```
mitmproxy has crashed!
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/server.py", line 344, in server_event
    for command in layer_commands:
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 257, in handle_event
    yield from self._handle(event)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 94, in _handle_event
    yield from self.event_to_child(event)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/tunnel.py", line 118, in event_to_child
    for command in self.child_layer.handle_event(event):
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 168, in handle_event
    command = next(command_generator)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 852, in _handle_event
    yield from self.event_to_child(stream, event)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 926, in event_to_child
    yield from self.event_to_child(conn, command.event)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 905, in event_to_child
    for command in child.handle_event(event):
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http1.py", line 63, in _handle_event
    yield from self.send(event)
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy/proxy/layers/http/_http1.py", line 259, in send
    raise AssertionError(f"Unexpected event: {event}")
AssertionError: Unexpected event: ResponseTrailers(stream_id=1, trailers=Headers[(b'grpc-status', b'0'), (b'grpc-message', b'')])
```

**Comment by mhils** [comment] 2023-01-25 16:16
Ah. The problem here is not so much empty responses, the problem is that you are using gRPC over an HTTP/1 connection, and we don't support sending HTTP trailers over HTTP/1 yet.

**Comment by mhils** [comment] 2023-01-25 16:18
I think I can close this as a duplicate of #2474?

**Comment by meiraxx** [comment] 2023-01-25 18:27
> Ah. The problem here is not so much empty responses, the problem is that you are using gRPC over an HTTP/1 connection, and we don't support sending HTTP trailers over HTTP/1 yet.

Oh, I see. It seems that only on the empty responses these trailers were being sent, hence my confusion.

> I think I can close this as a duplicate of #2474?

Sure.

Just a few questions before you close the issue:
- Is sending HTTP trailers over HTTP/1 going to be supported as a result of closing #2474?
- Is there an expected timeline for this?

Thanks!

**Comment by mhils** [comment] 2023-01-26 23:34
> Why was `_http1` the one handling this case? Shouldn't the handler have been `_http2`, which could in theory correctly handle this case?

If you look at the Details / Connections tab, you will probably see that the client <-> proxy connection is HTTP/1 whereas the proxy <-> server connection is HTTP/2. mitmproxy usually tries to negotiate the same HTTP version in both directions, I'm not exactly sure why this isn't happening here (I'd need more details on your setup). In either case, HTTP/1 is involved here and that breaks it.

Contributions for HTTP/1 trailers are welcome, there's no timeline for it.

**Closed** 2023-03-26 18:07 UTC
Labels: kind/triage
