### ISSUE TITLE
mitmproxy has crashed!

### ISSUE THREAD

**Issue by devbrain** [mitmproxy/mitmproxy#3928] opened 2020-04-12 08:28 UTC
#### Problem Description
After running mitmdump a several hours in docker, we observed

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Exception in thread TCPConnectionHandler (ProxyServer: ::ffff:114.231.191.88:12426 -> :::8080):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 600, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    self.channel
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 78, in __init__
    None)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 487, in __init__
    super().__init__(connection)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 295, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

#### Steps to reproduce the behavior:
Cant say for sure, but I see a lot of 

 
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/http.py", line 450, in _process_flow
    layer()
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/proxy/protocol/websocket.py", line 196, in __call__
    r = tcp.ssl_read_select(conns, 0.1)
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/net/tcp.py", line 227, in ssl_read_select
    ] or select.select(rlist, (), (), timeout)[0]
ValueError: filedescriptor out of range in select()

In log files
 

#### System Information
Mitmproxy: 5.0.1
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by strategist922** [comment] 2020-04-23 15:03
I also have the similar crash issue with Windows 10 64-bit build 19041.207
Following are my crash logs:
Mitmproxy: 5.1.1 build pypi_0 from pypi
Python: 3.7.6 from conda-forge
OpenSSL: 1.1.1g build he774522_0 from conda-forge
pyopenssl: 19.1.0 build py_1 from conda-forge
cryptography: 2.9.2 build pypi_0 from pypi

==================
D:\Dev\Anaconda3\envs\WXC_prj\python.exe D:/Dev/Anaconda3/envs/WXC_prj/src/main.py
2020-04-23 22:40:16.216 | INFO     | web_server:<module>:32 - Gevent server mode
2020-04-23 22:40:19.039 | INFO     | web_server:<module>:32 - Gevent server mode
Proxy server listening at http://*:8080
192.168.1.17:58307: clientconnect
192.168.1.17:58309: clientconnect
192.168.1.17:58307: Traceback (most recent call last):
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 285, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 262, in _process_flow
    return self.handle_regular_connect(f)
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 208, in handle_regular_connect
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 448, in _establish_tls_with_server
    **args
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\connections.py", line 292, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\net\tcp.py", line 386, in convert_to_tls
    **sslctx_kwargs
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\net\tls.py", line 285, in create_client_context
    param = SSL._lib.SSL_CTX_get0_param(context._context)
AttributeError: module 'lib' has no attribute 'SSL_CTX_get0_param'

Traceback (most recent call last):
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 285, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http1.py", line 83, in __call__
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 262, in _process_flow
    return self.handle_regular_connect(f)
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\http.py", line 208, in handle_regular_connect
    layer()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\proxy\protocol\tls.py", line 448, in _establish_tls_with_server
    **args
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\connections.py", line 292, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\net\tcp.py", line 386, in convert_to_tls
    **sslctx_kwargs
  File "D:\Dev\Anaconda3\envs\WXC_prj\lib\site-packages\mitmproxy\net\tls.py", line 285, in create_client_context
    param = SSL._lib.SSL_CTX_get0_param(context._context)
AttributeError: module 'lib' has no attribute 'SSL_CTX_get0_param'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

**Comment by mhils** [comment] 2020-04-29 09:15
@strategist922: Your crash is unrelated. I'm 99% positive that you have an old cryptography version being picked up somewhere, this is not a mitmproxy bug.

**Comment by mhils** [comment] 2020-04-29 09:16
The original bug is duplicate of #2557. I would need instructions on how I could reproduce it.

**Closed** 2020-12-13 11:46 UTC
Labels: area/protocols, kind/bug
