### ISSUE TITLE
mitmweb doesn't obey "showhost" directive

### ISSUE THREAD

**Issue by wdormann** [mitmproxy/mitmproxy#2084] opened 2017-03-01 17:24 UTC
##### Steps to reproduce the problem:

1. Launch mitmweb --host
2. Observe IP addresses in traffic, rather than host

##### Any other comments? What have you tried so far?

mitmproxy with the same option behaves as expected.  That is, host names are used rather than IP addresses.

##### System information

Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS Linux 7.3.1611 Core

**Comment by mhils** [comment] 2017-03-01 17:26
Thanks. This is a duplicate of #1888.

**Closed by mhils** 2017-03-01 17:26 UTC
