### ISSUE TITLE
Occasional UnicodeDecodeError breaks flow view on mitmweb

### ISSUE THREAD

**Issue by zbuc** [mitmproxy/mitmproxy#837] opened 2015-11-16 16:45 UTC
Not sure of repro steps yet, but I have seen this a few times.

I was running `mitmweb -T --host`, had a little bit of HTTP traffic captured, then the mitmweb flow interface began throwing this error whenever it tried to update:

```
ERROR:tornado.application:Uncaught exception GET /flows (::1)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/flows', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Requested-With': 'XMLHttpRequest', 'Host': 'localhost:8081', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8081/', 'Cookie': '_ga=GA1.1.311503227.1437663507; _xsrf=2|8fedf5f8|1cbe4b1c38ae27234a71f25a3caa7ca3|1446848479'})
Traceback (most recent call last):
  File "/Users/chris/repos/venv.mitmproxy/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/chris/repos/mitmproxy/libmproxy/web/app.py", line 99, in get
    data=[f.get_state(short=True) for f in self.state.flows]
  File "/Users/chris/repos/venv.mitmproxy/lib/python2.7/site-packages/tornado/web.py", line 692, in write
    chunk = escape.json_encode(chunk)
  File "/Users/chris/repos/venv.mitmproxy/lib/python2.7/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 12: invalid continuation byte
ERROR:tornado.access:500 GET /flows (::1) 3.59ms
```

The only fix was to restart mitmweb and abandon the captured flows.

I will run mitmweb with capturing enabled to see if I can get a reproducible flow file.

**Comment by mhils** [comment] 2015-11-18 13:08
Thanks! JSON does not support binary data and we apparently have binary data in the JSON representing flows. The next step is to track down in which part we have binary contents and then see what's the best workaround.

**Comment by ganguera** [comment] 2016-02-16 17:37
@mhils This bug is gone after the release of mitmproxy 0.16. `def _strip_content(flow_state):` gets rid of the binary data contained in the json.

**Comment by mhils** [comment] 2016-02-16 19:21
That's intersting, because _strip_content was pretty much what we did before as well. Let's close this until someone complains again.

**Closed by mhils** 2016-02-16 19:21 UTC
Labels: bug, good first contribution

**Comment by ganguera** [comment] 2016-02-16 23:08
Just for the record for future reference.

In my test case it made sense to find binary data in `flow_state["request"]["content"]` or `flow_state["response"]["content"]` because both the client and the server are capable of sending compressed data `Content-Encoding: gzip, deflate`. However, in @zbuc's case, and according to my limited HTTP knowledge, it's weird to find binary data because neither the client nor the server are announcing themself as capable of it.

**Comment by mhils** [comment] 2016-02-16 23:14
@ganguera, just to be sure - you tested with @zbuc's crash.txt?

**Comment by ganguera** [comment] 2016-02-16 23:32
@mhils Yes, I did. If you reproduce it, you won't find any header setting neither the `Accept-Encoding` nor the `Content-Encoding` but the data is being POST to a Microsoft server in some kind of mixed format.

**Comment by zbuc** [comment] 2016-02-17 00:22
This was traffic from a stock Windows 10 machine. It's some sort of Windows telemetry thing.
