### ISSUE TITLE
Use pygments to colorize some content types?

### ISSUE THREAD

**Issue by dufferzafar** [mitmproxy/mitmproxy#896] opened 2016-01-26 08:31 UTC
httpie colorizes the output of content types like html, json, xml etc. The relevant source is here: https://github.com/jkbrzt/httpie/blob/master/httpie/output/formatters/colors.py

We could use that to upgrade [libmproxy/contentviews.py](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/contentviews.py) to support colorized output.

Compare mitmproxy's output: 

![no colors](https://cloud.githubusercontent.com/assets/1449512/12575792/648784b8-c435-11e5-857a-040f8906a7d0.png)

With httpie's:

![pie colors](https://cloud.githubusercontent.com/assets/1449512/12575807/7b5b4864-c435-11e5-8157-1cbfb2d74e14.png)

**Comment by mhils** [comment] 2016-01-26 10:43
This is certainly a nice idea, albeit tricky to implement:

- Performance might be an issue - how fast is pygments for larger documents? Does it support streaming?
- We want to re-use the same output in mitmproxy, mitmdump and mitmweb. What's the best way to accomplish that?

**Comment by mhils** [comment] 2016-01-26 14:19
This is a dupe of #721

**Closed by mhils** 2016-01-26 14:19 UTC
Labels: enhancement
