### ISSUE TITLE
"Error connecting to user@domain.tld" with HTTP Basic Auth

### ISSUE THREAD

**Issue by timmc** [mitmproxy/mitmproxy#228] opened 2014-03-03 00:00 UTC
I'm getting odd behavior trying to proxy my feed reader (liferea) for debugging. I have some HTTP Basic Auth RSS feeds from Livejournal which look like `http://users.livejournal.com/davis-square/data/rss?auth=digest`. Wireshark shows an unauthenticated request followed by a 401 response, then liferea re-requesting with Basic Auth and a 200 response. If I instead use mitmproxy, mitmproxy only shows a single request/response:

```
← 502: Error connecting to "bob@users.livejournal.com":
[Errno -5] No address associated with hostname
```

(Edit: Non-substantive change to make examples consistent with each other.)

**Comment by dufferzafar** [comment] 2016-02-20 16:23
@mhils I read the discussion on the issue, but it isn't exactly clear what needs to be done here. :/

Do we want to extract the username from the URL and set it as the Authorization Header?

**Comment by mhils** [comment] 2016-07-23 19:42
I can't reproduce this issue with curl anymore, and I haven't seen it pop up somewhere else. I'm closing this for now, until there's more evidence that this is still an issue.

**Closed by mhils** 2016-07-23 19:42 UTC
Labels: bug
