### ISSUE TITLE
Can't run mitmweb.exe in Windows Server 2019 Datacenter

### ISSUE THREAD

**Issue by piortest** [mitmproxy/mitmproxy#3823] opened 2020-02-18 11:45 UTC
#### Problem Description
Getting an error after installing the mitmproxy from https://mitmproxy.org/ (Download Windows Installer) v5.0.1 in Windows Server 2019 Datacenter.

Full error:
C:\Program Files (x86)\mitmproxy>mitmweb.exe
Traceback (most recent call last):
  File "mitmweb", line 2, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\main.py", line 22, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\tools\_main.py", line 14, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\master.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\addonmanager.py", line 8, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\eventsequence.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\http.py", line 7, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\__init__.py", line 1, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\request.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\message.py", line 5, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "mitmproxy\net\http\encoding.py", line 11, in <module>
  File "d:\a\mitmproxy\mitmproxy\.tox\cibuild\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\brotli.py", line 8, in <module>
ImportError: DLL load failed: The specified module could not be found.
[6576] Failed to execute script mitmweb

#### Steps to reproduce the behavior:
1. Install version 5.0.1 on Windows 2019 Datacenter
2. Run C:\Program Files (x86)\mitmproxy>mitmweb.exe

#### System Information
Can't run.

**Comment by Prinzhorn** [comment] 2020-02-18 14:22
Duplicate of #3804

**Comment by imsaion** [comment] 2020-02-18 22:11
Wikipedia says: "Windows Server 2019 is based on the Windows version 1809 codebase"
So pretty much the same. (?)

**Comment by mhils** [comment] 2020-02-21 22:05
Closing this as a duplicate of #3804, thanks @Prinzhorn!

**Closed by mhils** 2020-02-21 22:05 UTC
Labels: kind/triage
