### ISSUE TITLE
Installation issue with enum34 v1.1.2

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#924] opened 2016-02-09 19:53 UTC
Installation issue with enum34 on Mac OS X 10.11.3 (El Capitan)
Python 2.7.10

Installed netlib and mitmproxy from master:
`
   cbee3bd..1af231f  master     -> origin/master
Updating cbee3bd..1af231f
[...]
git pull mitmproxy...
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 73 (delta 49), reused 49 (delta 49), pack-reused 19
Unpacking objects: 100% (73/73), done.
From https://github.com/mitmproxy/mitmproxy
   992842d..d5aa4f0  master     -> origin/master
Updating 992842d..d5aa4f0
[...]`

Build process worked without any errors. But then:

`$ mitmdump
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34<1.2,>=1.1.2' distribution was not found and is required by mitmproxy`

Just to be sure, I uninstalled the current enum34 version. Interestingly, it is version 1.1.2 which should match the above condition >=1.1.2:

`sudo pip uninstall enum34
Uninstalling enum34:
  /Library/Python/2.7/site-packages/enum
  /Library/Python/2.7/site-packages/enum34-1.1.2-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled enum34`

Thinking that a simple re-build would be sufficient, I was wrong:

`$ sudo pip install netlib/ --upgrade
$ sudo pip install mitmproxy/ --upgrade`

but again, the same version 1.1.2 of enum43 was downloaded:

`Downloading/unpacking enum34 (from cryptography>=1.2.2,<1.3->netlib==0.16)
  Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/enum34/setup.py) egg_info for package enum34`
  
and after the build has finished, I ran into the same error:

`$ mitmdump
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (enum34 1.1.2 (/Library/Python/2.7/site-packages), Requirement.parse('enum34<1.1,>=1.0.4'), set(['h2']))`

Just my fault or maybe also popping up elsewhere?

Cheers
Gordon

**Comment by mhils** [comment] 2016-02-10 16:06
Whoops - thanks for the report, should be fixed now.

**Closed** 2016-02-10 16:05 UTC

**Comment by arnau** [comment] 2016-02-17 09:44
Hi, I got an issue with enum34 while using mitmproxy 0.16 on Circle CI.

```
error: enum34 1.1.2 is installed but enum34<1.1,>=1.0.4 is required by set(['h2']) Action failed: python setup.py install
```

Any suggestions to overcome the issue?

**Comment by mhils** [comment] 2016-02-17 11:33
@arnau, how are you installing mitmproxy?

**Comment by arnau** [comment] 2016-02-17 12:04
@mhils I have a tool built on top of mitmproxy that defines `install_requires[mitmproxy==0.16]` in the `setup.py`: https://github.com/ustwo/mastermind/blob/master/setup.py#L42

So I run

```pip install "git+https://github.com/ustwo/mastermind.git@v0.8.1#egg=mastermind"```

It worked fine with my v0.7.0 that pinned `mitmproxy==0.15`.

I'm doing more research on this, I have to be doing something wrong managing Python dependencies.  Now I have it reproduced in OS X too.

**Comment by Lukasa** [comment] 2016-02-17 14:00
So @dstufft has pointed out that this is caused by having conflicting upper bounds on the version of enum34, plus pip's lack of a proper resolver.

In part to resolve this I've just pushed hyper-h2 version 2.1.2 that lifts our upper bound on enum34 to v2.0. Grabbing that should resolve the problem in this case.

**Comment by arnau** [comment] 2016-02-17 14:02
:+1:
