### ISSUE TITLE
Host header missing after upgrading to mitmproxy 10

### ISSUE THREAD

**Issue by jvanheesch** [mitmproxy/mitmproxy#7200] opened 2024-09-20 10:37 UTC
#### Problem Description

After upgrading to mitmproxy 10, the Host header is no longer available in custom script.

#### Steps to reproduce the behavior:

- `git clone https://github.com/jvanheesch/mitmproxy-host-header-regression.git`
- `cd mitmproxy-host-header-regression`
- `docker compose up`
- `docker compose exec curl curl -k https://mitm9 -H 'Host: www.example.com'` -> log_headers.py sees Host header
  ```
  mitm9-1   | [10:26:43.595][172.18.0.2:48814] client connect
  mitm9-1   | Headers[(b'Host', b'www.example.com'), (b'User-Agent', b'curl/7.82.0-DEV'), (b'Accept', b'*/*')]
  mitm9-1   | [10:26:43.725][172.18.0.2:48814] server connect www.example.com:443 (93.184.215.14:443)
  mitm9-1   | 172.18.0.2:48814: GET https://www.example.com/ HTTP/1.1
  mitm9-1   |       << HTTP/2.0 200 OK 1.2k
  ```
- `docker compose exec curl curl -k https://mitm10 -H 'Host: www.example.com'`  -> log_headers.py does not see Host header
  ```
  mitm10-1  | [10:26:58.579][172.18.0.2:37530] client connect
  mitm10-1  | Headers[(b'user-agent', b'curl/7.82.0-DEV'), (b'accept', b'*/*')]
  mitm10-1  | [10:26:58.710][172.18.0.2:37530] server connect www.example.com:443 (93.184.215.14:443)
  mitm10-1  | 172.18.0.2:37530: GET https://www.example.com/ HTTP/2.0
  mitm10-1  |       << HTTP/2.0 200 OK 1.2k
  ```

**Comment by mhils** [comment] 2024-09-20 11:41
Thank you for the detailed report!

git bisect yields
```
The first bad commit could be any of:
0583e8e46c02ccd35ca22630d93ee6bab100b013
262cadab75d377fbe3a79561e27e477757ee142c
524adbf950384f1a7cce77abfa0ed0a4666ce5d7
edb85d4af1c4ac71caf578d6ce016644434c062d
```

**Comment by mhils** [comment] 2024-09-20 11:52
Mitmproxy 10 works if I specify `http2=false`. So this is likely related to HTTP/2 `:authority` header treatment.

**Comment by mhils** [comment] 2024-09-20 12:08
Wireshark shows that no host header is actually being sent here by cURL for HTTP/2, only the `:authority` pseudo header:

![image](https://github.com/user-attachments/assets/eb155cbb-8ff6-409f-a13f-2077371072b4)

Accessing `flow.request.host_header` continues to work as expected. 

So on some level this is working as intended, but then again I agree that the UX here is confusing at best.

**Comment by jvanheesch** [comment] 2024-09-20 12:34
Love the quick response and analysis - thank you! I agree it makes sense for `flow.request.headers` to not contain Host header if, well, the client is not sending it. Not sure if this issue warrants any further action.

**Comment by Prinzhorn** [comment] 2024-09-20 15:30
Also refs https://github.com/mitmproxy/mitmproxy/issues/7007

**Comment by mhils** [comment] 2024-09-20 17:38
Thanks! Let's close this as a duplicate of #7007 for now. :)

**Closed by mhils** 2024-09-20 17:38 UTC
Labels: kind/bug, area/protocols
