### ISSUE TITLE
Cannot login to facebook

### ISSUE THREAD

**Issue by hynguyen2610** [mitmproxy/mitmproxy#1470] opened 2016-08-04 09:03 UTC
Hi mitmproxy team, 
Your tool is a great effort. I tried it for a month. Most of pages are working smooth under mitmproxy. But I cannot login to Facebook in both mode Rugular and Transparent.
##### Steps to reproduce the problem:

1. Start mitmproxy using Regular mode: mitmproxy
2. Config the Windows-running victim proxy (IP: 192.168.6.181 to use proxy as my computer 192.168.6.211, port 8080)
3. Visit mitm.it on the victim computer, download and install the .p12 (user certificate) file.
4. Visit www.facebook.com
5. Enter valid login information (username, password) and press Enter.

##### What is the expected behavior?
I thought it will login to facebook successfully.

##### What went wrong?
The login is not success, the browser redirect to login page again with no notification. In another Facebook logged in device, I seen one new notification say "Your account was logged in to from an unrecognized browser or device. Please review this login...".
I click the notification, chose "This was me" and remember the device. But the next time I try to loggin in victim computer, every is repeat. I cannot login to facebook when mitmproxy is on. I guess this is due to Certificate pinning. Is there a workaround like "ignore the login phase" or something? Is mitmproxy official support/not support Facebook page?

##### Any other comments? What have you tried so far?
I tried to ignore the facebook login when start mitmproxy 
`mitmproxy --ignore '^(.+\.)?facebook\.com:443$'`
After that, I can login to facebook, but when I clear the ignore pattern and F5 the facebook page, nothing was intercepted except images request.

---

Mitmproxy Version: 0.17
Operating System: Linux Mint 18 (base on Ubuntu 16.04)

**Comment by vhaupert** [comment] 2016-08-04 10:57
I can't reproduce this behavior using latest mitmproxy. The Facebook login works flawless. Which browser do you use?

**Comment by dufferzafar** [comment] 2016-08-04 12:35
@hynguyen2610 and @vhaupert You are both correct! 😛 

This is not working on v0.17 but working with v0.18 (latest github master)

So for whatever reason this is happening, it's been fixed!

One tiny thing that I noticed (possible unrelated?) 

Some POST calls to a `/cookies/consent` URL were marked as `Zombie Streams` on 18 but they were just waiting in 17!

**Comment by Kriechi** [comment] 2016-08-04 12:52
@dufferzafar Zombie Streams are related to HTTP/2 - usually when a connection is closed, all remaining flows get canceled and turn in to zombies. Is this a problem - or just a log message you are seeing?

**Comment by dufferzafar** [comment] 2016-08-04 12:55
Not really a problem. I was just saying that the differences between 0.17 & 0.18 *might* be because of that. 😕

**Comment by mhils** [comment] 2016-08-04 22:03
Closing this here as this is fixed on master. :smiley:

**Closed by mhils** 2016-08-04 22:03 UTC

**Comment by hynguyen2610** [comment] 2016-08-05 00:56
I install mitmproxy using python-pip?
Sumitmproxydo pip install
And it install 0.17 in my computer.
Can you make mitmproxy 0.18 available for pip?

**Comment by mame82** [comment] 2017-01-12 18:09
Can somebody confirm that this is still working? I'm facing the same redirection issue in FB login using mitmproxy version 0.18.2 (Kali Linux - rollin repo). THX in advance
