### ISSUE TITLE
mitmdump crash during server replay 

### ISSUE THREAD

**Issue by markus-kusano** [mitmproxy/mitmproxy#1284] opened 2016-06-21 22:27 UTC
[gtm2.zip](https://github.com/mitmproxy/mitmproxy/files/326696/gtm2.zip)

##### Steps to reproduce the problem:

1. Unzip recording: `unzip gtm2.zip`
2. Replay the recording using --kill: `mitmdump --no-pop --rheader Host --kill --server-replay ./gtm2.out`
3. GET the page in the recording:  https://www.googletagmanager.com/gtm.js?id=GTM-K787WT

##### What is the expected behavior?

The webpage loads (a javascript file is shown).

##### What went wrong?

`mitmdump` throws an exception:

```
127.0.0.1:57022: clientconnect
127.0.0.1 GET https://www.googletagmanager.com/gtm.js?id=GTM-K787WT HTTP/2.0
 << Connection killed
Exception in thread Http2SingleStreamLayer-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/markus/mitmproxy/mitmproxy/protocol/http2.py", line 503, in run
    self()
  File "/home/markus/mitmproxy/mitmproxy/protocol/http2.py", line 509, in __call__
    layer()
  File "/home/markus/mitmproxy/mitmproxy/protocol/http.py", line 174, in __call__
    self.process_request_hook(flow)
  File "/home/markus/mitmproxy/mitmproxy/protocol/http.py", line 338, in process_request_hook
    request_reply = self.channel.ask("request", flow)
  File "/home/markus/mitmproxy/mitmproxy/controller.py", line 139, in ask
    raise exceptions.Kill()
Kill: None
```

##### Any other comments? What have you tried so far?

The network connection in the browser hangs attempting to download the page. This causes the browser to never fully load the page.

---

Mitmproxy Version:

commit: 
7523f41f75d69a141d2d4bf67a7cf552d3560fc2

Operating System: Ubuntu 14.04.4

**Comment by mhils** [comment] 2016-06-29 07:39
Thanks for the report! We need to take a look at this once #1265 is in. :smiley:

**Comment by Kriechi** [comment] 2016-07-11 18:53
Did you make the recording with HTTP/2 enabled?
Could you please try it with `--no-http2` again?
Maybe this is an http2-only issue. Thanks!
Please also note the recent http2-related commits in the last days.

**Comment by mhils** [comment] 2016-07-23 00:35
Closing this as a duplicate of #1395, which has a consistent way to reproduce it!

**Closed by mhils** 2016-07-23 00:35 UTC
Labels: bug
