### ISSUE TITLE
HAR file does not appears when I try to use har_dump.py script

### ISSUE THREAD

**Issue by EFES00** [mitmproxy/mitmproxy#3855] opened 2020-03-11 10:08 UTC
HAR file does not appears when I try to use har_dump.py script calling from command line

1. Type **mitmdump -s har_dump.py --set hardump=dump.har**
2. Press Enter
3. Do something in browser via proxy
4. Press Ctr+C

File dump.har doesn't present in my hard disc at all

System Information:

Mitmproxy: 5.0.1
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Windows-10-10.0.18362-SP0

**Comment by bigfoxtail** [comment] 2020-10-12 12:08
I'm having the same problem.
Mitmproxy:6.0.0.dev
python3.7.7
Platform:win10

I suspect it's the Windows console, ctrl+c causes def done not to execute

**Comment by abitrolly** [comment] 2021-02-02 21:07
Duplicate of #3377.

**Closed** 2021-02-11 20:07 UTC
Labels: kind/triage
