### ISSUE TITLE
Async event hooks

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4609] opened 2021-05-25 07:31 UTC
#### Problem Description

I don't want hooks to block the entire core but I also don't want race conditions. I'm doing I/O (gRPC) inside my addon hooks and currently this will block the entire proxy until it is finished.

#### Proposal

I vaguely remember some discussion in Slack about that. Essentially replacing the `@concurrent` hooks (https://github.com/mitmproxy/mitmproxy/blob/292e3b413cd6cff497e35f151e29c6d786417144/examples/addons/nonblocking.py) with `async` so that it's more reliable and doesn't require a thread for every single hook.

Maybe the new architecture makes this really easy to implement? To `await` every hook?

**Comment by mhils** [comment] 2021-05-25 10:11
duplicate of #4207 :)

**Closed by mhils** 2021-05-25 10:11 UTC
Labels: kind/feature

**Comment by Prinzhorn** [comment] 2021-05-25 10:14
Sorry!

**Comment by mhils** [comment] 2021-05-25 10:15
No worries, I did not find it on the first try either, just kept on searching because I knew it existed. Now we have more keywords pointing in the right direction. 😄
