### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'response'

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1419] opened 2016-07-23 22:24 UTC
On stopping mitmproxy getting below error:
```
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/Library/Python/2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 323, in __call__
    self.handle_regular_mode_connect(request)
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 409, in handle_regular_mode_connect
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 340, in __call__
    self.get_response_from_server(flow)
  File "/Library/Python/2.7/site-packages/libmproxy/protocol/http.py", line 471, in get_response_from_server
    if flow.response.stream:
AttributeError: 'NoneType' object has no attribute 'response'
```

**Comment by mhils** [comment] 2016-07-24 00:08
This is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/907. 

I appreciate getting bug reports, but it would be helpful if you could (1) search for duplicate issues, (2) list your mitmproxy version and (3) use the latest official release, which is 0.17. Everything else is not helpful at all.

**Comment by shrikantkaramkar** [comment] 2016-07-24 00:12
I am using 0.15 and ll try to upgrade to 0.17

**Closed** 2016-07-24 00:39 UTC
