### ISSUE TITLE
disable temporary filter feature

### ISSUE THREAD

**Issue by Davenjoy** [mitmproxy/mitmproxy#6869] opened 2024-05-22 20:14 UTC
#### Problem Description

For Mitmproxy, I would like to check all flows without filter temporarily. Currently, I remove filter manually to see all flows, and reset the filter to see filtered flows. 

#### Proposal
I would like to suggest adding command to disable temporary filter feature or use history of filter.

#### Alternatives
Nil

#### Additional context
Nil

**Comment by Davenjoy** [comment] 2024-05-23 20:00
this question for mitmproxy.

**Comment by mhils** [comment] 2024-05-23 20:04
refs https://github.com/mitmproxy/mitmproxy/pull/4760

**Comment by mhils** [comment] 2024-05-23 20:04
Closing as a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4604 :)

**Closed by mhils** 2024-05-23 20:04 UTC
Labels: kind/feature
