### ISSUE TITLE
Random requests fail with "Server  disconnected, 502"

### ISSUE THREAD

**Issue by knlr** [mitmproxy/mitmproxy#3043] opened 2018-04-05 11:52 UTC
Random requests (~1 in 5) fail with the above message in the flow list in red.

The client receives the following response:
{ Status Code: 502, Headers {
    Connection =     (
        close
    );
    "Content-Length" =     (
        256
    );
    "Content-Type" =     (
        "text/html"
    );
    Server =     (
        "mitmproxy 3.0.3"
    );
} }

##### Steps to reproduce the problem:

1. Use mitmproxy

##### Any other comments? What have you tried so far?

I'm developing iOS apps and have my device pointing to mitmproxy that runs on my Mac.

Tested without mitmproxy and all requests succeed.
Tried different web services (apps) and they all fail randomly.

##### System information

Mitmproxy: 3.0.3 
Python:    3.6.5
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit

**Comment by mhils** [comment] 2018-04-05 11:53
Probably a duplicate of #3038.

**Closed by mhils** 2018-04-05 11:53 UTC
