### ISSUE TITLE
Support for HTTP/3 and QUIC

### ISSUE THREAD

**Issue by Aniketh01** [mitmproxy/mitmproxy#4170] opened 2020-08-26 10:28 UTC
With the advent of the new transport protocol QUIC, a lot of the network traffic would be shifting to speak HTTP/3 soon. A number of services are already speaking HTTP/3 already. It would be nice to if mitmproxy would support these protocols as well.

The current available python-based QUIC/HTTP3 library to use would be aioquic: https://github.com/aiortc/aioquic/.

Would be happy to discuss more this and the future work this could entail :)

**Comment by mhils** [comment] 2020-08-26 10:37
That's definitely something that's on our radar. The changes involved are quite nontrivial, but @Meitinger has a working fork with QUIC support at https://github.com/Meitinger/mitmproxy. We will probably take a closer look once #1775 has landed.

**Comment by Aniketh01** [comment] 2020-10-13 16:03
Thanks for letting me know. @Meitinger Is there a working commit with https://github.com/Meitinger/mitmproxy where I can test, listen to the QUIC and HTTP/3 traffic? So far I have tested, and wasn't able to capture any QUIC traffic. Am I missing something here?

**Comment by alt-glitch** [comment] 2021-02-04 09:23
@Aniketh01 Did you manage to get this fork to work? Moreover how did you test QUIC traffic? I have installed that fork in an Ubuntu VM to try it out but haven't been able to find a way to generate QUIC traffic.

**Comment by hellodword** [comment] 2021-03-28 14:51
> @Aniketh01 Did you manage to get this fork to work? Moreover how did you test QUIC traffic? I have installed that fork in an Ubuntu VM to try it out but haven't been able to find a way to generate QUIC traffic.

`curl -i --http3 https://quic.aiortc.org`

But you need to build a cURL with HTTP/3 support.

- [cURL - HTTP3 (and QUIC)](https://github.com/curl/curl/blob/master/docs/HTTP3.md)
- [HTTP/3 test servers](https://bagder.github.io/HTTP3-test/)

hope it is helpful :)

**Comment by daMatz** [comment] 2021-12-15 15:02
Is there any news about HTTP/3 support? Would love to see it for mitmproxy but as QUIC is based on UDP it seems like a bigger task, right?

**Comment by ericbeland** [comment] 2021-12-26 18:58
Saw this comment go by, which spurred my curiosity on how popular HTTP/3 is? When this was opened, HTTP/3 was probably 2 or 3 percent of all internet traffic, but now it is up to [about 24 percent](https://w3techs.com/technologies/details/ce-http3).

**Comment by j-h-a** [comment] 2022-01-26 16:57
@ericbeland yes, totally, and many services can benefit such as video-streaming via CDNs. The lack of support in popular tools is a good reason to not use it yet. Engineers are making technical decisions all over the world, and part of that process is "how easy will my thing be to test if I use this tech?". For me, not being able to use `mitmproxy` to inspect what's going on is a deal-breaker for QUIC when building mobile apps. At least for now. It's likely we will adopt it eventually, but lack of support in tools is definitely restricting that growth. All good reasons this should be raised in priority.
(btw, I love `mitmproxy` - many thanks to all its contributors).

**Comment by mhils** [comment] 2022-01-27 11:30
QUIC remains a bit tricky to implement for us. 

- Ideally we'd use OpenSSL, but OpenSSL still does not expose reasonable APIs (https://daniel.haxx.se/blog/2021/10/25/the-quic-api-openssl-will-not-provide/). 
- One alternative is aioquic, which I'm not too enthusiastic about (yet). Given the lack of OpenSSL APIs it implements lots of low-level stuff, including some parts written in C. I don't think there've been any security reviews of the codebase and the bus factor is 1. I do think it's a great effort, but I'm not feeling confident enough to depend on it in mitmproxy.
- Finally, we could consider developing Python bindings for one of the Rust implementations (Quiche/Quinn/Neqo). This would be fun to look into, the downside of that approach is that it brings tons of additional stuff we need to maintain - cross-platform wheel builders, etc. etc.

So yes - as much fun as it would be, I can't justify taking multiple months off to work on this at the moment. If you work for a company is interested in sponsoring (parts of) the efforts in mitmproxy, please feel free to get in touch. Outside of that I don't see us adopting QUIC super soon unfortunately.

**Comment by ericbeland** [comment] 2022-01-27 12:13
@mhils Do you have a ballpark for what sponsoring that effort would cost? It might be helpful for conversations in organizations that depend on mitmproxy but are longing for QUIC support.

**Comment by hellodword** [comment] 2022-01-27 12:23
> Finally, we could consider developing Python bindings for one of the Rust implementations (Quiche/Quinn/Neqo). This would be fun to look into, the downside of that approach is that it brings tons of additional stuff we need to maintain - cross-platform wheel builders, etc. etc.

Quiche has [C API](https://github.com/cloudflare/quiche/blob/master/quiche/include/quiche.h), so maybe it's much easier than other implementations for using in Python.

> as much fun as it would be, I can't justify taking multiple months off to work on this at the moment.

Totally understand.

I've been following the QUIC/HTTP3 & MITM issue for a year. 

As it's a great challenge for "traditional" MITM tools, maybe we can open an issue and mark it as help wanted.

**Comment by mhils** [comment] 2022-01-27 13:36
> @mhils Do you have a ballpark for what sponsoring that effort would cost? It might be helpful for conversations in organizations that depend on mitmproxy but are longing for QUIC support.

Highly depends on timing (does OpenSSL have reasonable APIs yet?) and scope (interop with other HTTP versions, replay functionality, ...). Realistically it will take at least a few months of full-time work, so take your usual consulting rate and you'll have an approximate ballpark figure. There are of course lower hanging fruits, for example building an "sslsplit for QUIC" outside of mitmproxy. It may make a lot of sense to just build that first.

> Quiche has C API, so maybe it's much easier than other implementations for using in Python.

Thanks for the pointer.  I've also had some great experiences with using PyO3 on smaller projects, so I think the interop story is definitely something that can be solved. It's definitely worth to evaluate both approaches. :)

**Comment by 89z** [comment] 2022-03-08 16:33
https://github.com/httptoolkit/frida-android-unpinning/issues/13

**Comment by 89z** [comment] 2022-03-08 16:36
In another thread, someone suggested recent versions (since 2019) of the Android YouTube app (`com.google.android.youtube`) are using HTTP/3 or QUIC. Because of this, you cant really monitor the YouTube app at all. I am able to capture a few image requests that pass through lower HTTP versions, but it seems all the audio, video and JSON is possibly using HTTP/3.

**Comment by Meitinger** [comment] 2022-03-31 20:23
There is now a PR for DNS (#5232).  These changes also include support for UDP. Once they get finalized and merged, I'll start work on updating the (now mostly defunct) fork mentioned earlier for mitmproxy's new sansio implementation.

**Comment by 89z** [comment] 2022-04-07 22:12
Just found this while making a YouTube API request:

~~~json
{
  "QUIC": {
    "close_sessions_on_ip_change": true,
    "connection_options": "BWRS",
    "quic_version": "QUIC_VERSION_43"
  }
}
~~~

so I think that confirms it

**Comment by Meitinger** [comment] 2022-06-29 09:59
Draft PR #5435 for QUIC support in mitmproxy is finally here. So far reverse mode for H3 and raw stream relay have been implemented. For those who are interested: Please comment, test and report bugs, thanks :)

**Comment by RenjieTang** [comment] 2023-03-02 22:07
If I'm running mitmpxoxy in non-http3 mode, and the application tries to speak HTTP/3, what's the expected behavior?
Do we expect the UDP traffic to be excluded from the dump? Or does mitmproxy reject to do QUIC handshake and force the application to fallback to TCP?

**Comment by meitinger** [comment] 2023-03-03 22:52
> If I'm running mitmpxoxy in non-http3 mode, and the application tries to speak HTTP/3, what's the expected behavior?

If no HTTP3 mode is specified, no UDP socket will be opened. If mitmproxy acts as a reverse proxy, the application _should_ fall back to HTTP1/2 (unless any [alt-svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) points to a valid HTTP3 service on the same host).
In transparent mode, you might want to block certain UDP traffic, if otherwise UDP packets pass mitmproxy unfiltered.

**Comment by mhils** [comment] 2023-06-25 11:11
Some excellent news: The [NLnet Foundation](https://nlnet.nl/) is sponsoring the development of HTTP/3 for mitmproxy. We aim to have a first experimental release out very shortly! 😃

**Comment by 3052** [comment] 2023-12-12 23:19
>  In transparent mode, you might want to block certain UDP traffic, if otherwise UDP packets pass mitmproxy unfiltered.

how do you do that?

**Comment by 3052** [comment] 2023-12-12 23:21
https://github.com/mitmproxy/mitmproxy/issues/6199

**Comment by alyfreym** [comment] 2024-03-05 21:15
Any update?

**Comment by mhils** [comment] 2024-03-05 21:16
https://mitmproxy.org/posts/releases/mitmproxy10/

**Comment by rew1nter** [comment] 2024-04-30 12:09
There's no support for HTTP3 forward proxying right?

**Comment by mhils** [comment] 2024-04-30 12:46
We currently support HTTP/3 reverse proxying only. Support for transparent mode, WireGuard mode, and local redirect mode is coming next. :)

**Comment by rew1nter** [comment] 2024-04-30 13:19
> Support for transparent mode,

I didn't understand that. Will this include the forward proxying ?

**Comment by mhils** [comment] 2024-04-30 15:02
The term "forward proxy" does not have a super well-defined meaning. Check out https://docs.mitmproxy.org/stable/concepts-modes/ for what I mean by transparent mode. 

A "regular mode" HTTP/3 proxy (where you configure an HTTP/3 proxy in your client) will definitely come last. AFAIK client support for that is mostly not there yet.

**Comment by felixshing** [comment] 2024-05-02 01:56
Hi I am new in this area. I would like to ask can we use mitmproxy to decrypt QUIC traffic right now? Specifically, my clients are iPhone and Apple Vision Pro, and they use FaceTime, which transmits content via QUIC. I can set up a WiFi AP on MacBook or Linux. Is it possible for me to decrypt the QUIC content in this setup?

**Comment by f00kat** [comment] 2024-06-10 07:50
Hi. In order for the proxy to work with Chromium, will it be necessary to give it arguments?

```
--origin-to-force-quic-on=www.example.org:6121 \
--ignore-certificate-errors \
--ignore-certificate-errors-spki-list="${SPKI}"
```

**Comment by mhils** [comment] 2024-07-03 15:43
I think we'll be there in a few weeks! /cc @errorxyz  :)

**Comment by saunders-jake** [comment] 2024-07-03 17:07
> I think we'll be there in a few weeks! /cc @errorxyz :)

I'm SO happy to hear this, thank you!:)

**Comment by 3052** [comment] 2024-08-25 14:49
kind of shocked this hasnt been mentioned yet, but a workaround is to simply disable QUIC.

you should be able to do this with Linux and Windows by blocking outbound UDP port 443. for example with the YouTube Android app, if you do this then it defaults back to HTTP/2

**Comment by 3052** [comment] 2024-10-04 22:44
why is this still open, if it seems to be done?

https://mitmproxy.org/posts/releases/mitmproxy-11

**Closed** 2024-10-05 03:14 UTC
Labels: kind/feature, nlnet

**Comment by mhils** [comment] 2024-10-05 03:25
Fixed, thanks! :)
