### ISSUE TITLE
Error when killing HTTP/2 Flow

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1395] opened 2016-07-22 01:22 UTC
##### Steps to reproduce the problem:

1. `mitmproxy`
2. Add catch-all interception filter
2. Visit HTTP/2 URL
3. Press `X`

##### What is the expected behavior?
Flow should be killed.

##### What went wrong?
![image](https://cloud.githubusercontent.com/assets/1019198/17043891/eeb34af8-4f6f-11e6-8169-3f2f26e67ed7.png)

##### Any other comments? What have you tried so far?
When fixing this, let's make sure that killing responses works as well.

---

Mitmproxy Version: master
Operating System: Ubuntu 14.04 x64

**Comment by Kriechi** [comment] 2016-07-22 07:43
Duplicate of #1193 and #1284 - but finally we know a way to reproduce it.

**Closed** 2016-07-23 18:11 UTC
Labels: bug, in progress
