### ISSUE TITLE
Running mitmproxy's reverse-proxy mode locally

### ISSUE THREAD

**Issue by fsturmat** [mitmproxy/mitmproxy#6737] opened 2024-03-15 05:37 UTC
#### Problem Description

I have been trying to run mitmproxy's reverse proxy on the same machine that runs the application that is to be "mitm'd". Unfortunately, the good, old hosts-file approach fails because mitmproxy is also using the hosts file to resolve its domain names. I lost my sanity trying to solve this issue.

["How mitmproxy Sucks at Being a Proxy"](https://fsturmat.net/blog/03142024/)

#### Proposal
Maybe some way to let mitmproxy ignore the hosts file... or maybe some way to specify which DNS config mitmproxy should use... or at least some way to have a script perform its own name resolution?

**Comment by Prinzhorn** [comment] 2024-03-15 10:57
Please fill out the template completely including "Steps to reproduce the behavior:". I have no idea what your setup looks like and what exactly the "old hosts-file approach" is.

**Comment by mhils** [comment] 2024-03-15 11:33
Meta comment: "How mitmproxy Sucks" may not be the best way to provide constructive feedback and introduce yourself. Your actual criticism is well-founded, and that takes away from that point.

On your points:

1. Having a `dns_server` option would be really nice. We currently just rely on getaddrinfo, which always takes /etc/hosts into account. I've filed https://github.com/mitmproxy/mitmproxy/issues/6739. Contributions welcome!
2. Re DNS spoofing: Our docs are a bit outdated here, see https://github.com/mitmproxy/mitmproxy/issues/6738

Last but not least, let me say that #6531 will be the best solution to your original problem, but it's Windows and macOS only for now.

**Comment by mhils** [comment] 2024-03-20 22:11
Closing this in favor of the two issues mentioned above - thanks again for filing this!

**Closed by mhils** 2024-03-20 22:11 UTC
Labels: kind/feature
