### ISSUE TITLE
Loop with websites using cloudflare

### ISSUE THREAD

**Issue by janemba** [mitmproxy/mitmproxy#6595] opened 2024-01-09 17:42 UTC
#### Problem Description

While using `mitmproxy` with a website using `cloudflare`, I got requests loop. From the target website I got the following message:
```
Please unblock challenges.cloudflare.com to proceed.
```
Then the pages, reload and again I got this message.

On `mitmproxy` side, I got the same `GET`, `GET`, `POST` requests looping indefinitely.

#### Steps to reproduce the behavior:
1.  Start `mitmproxy` with a target website using `cloudflare`.
2.  In your browser open the target website.
3.  The loop occurs here.

#### System Information
```
Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-5.17.3-x86_64-AMD_Ryzen_7_2700X_Eight-Core_Processor-with-glibc2.35
```

**Comment by Prinzhorn** [comment] 2024-01-09 18:07
Could be https://github.com/mitmproxy/mitmproxy/issues/4575 ?

Please provide an example website that doesn't work through mitmproxy.

**Comment by janemba** [comment] 2024-01-09 18:46
Yeah sure:

https://yggtorrent.qa

I didn't investigate that much the issue but it look like similar to #4575 .

**Comment by Prinzhorn** [comment] 2024-01-09 19:46
The website loads perfectly fine for me in Chromium through mitmproxy 10.2.1

**Comment by Prinzhorn** [comment] 2024-01-10 10:33
I'm closing this until you can provide more information on how to reproduce this. It might very well be caused by user error, a browser add-on or something out of the control of mitmproxy.

**Closed by Prinzhorn** 2024-01-10 10:33 UTC
Labels: kind/triage

**Comment by janemba** [comment] 2024-01-10 17:55
Ok I just made a test with Chromium and it works fine thank you.
