### ISSUE TITLE
Setting View Filter shows Addon Error in Eventlog

### ISSUE THREAD

**Issue by fenilgandhi** [mitmproxy/mitmproxy#2969] opened 2018-03-07 06:22 UTC
error: Addon error: Traceback (most recent call last):
        File "/home/coldfire/Projects/mitmproxy/mitmproxy/addons/view.py", line 521, in update
            idx = self._view.index(f)
        File "/home/coldfire/Projects/mitmproxy/venv/lib/python3.6/site-packages/sortedcontainers/sortedlist.py", line 2343, in index
            raise ValueError('{0!r} is not in list'.format(val))
        File "/home/coldfire/Projects/mitmproxy/mitmproxy/http.py", line 182, in __repr__
            return s.format(flow=self)
        File "/home/coldfire/Projects/mitmproxy/mitmproxy/connections.py", line 215, in __repr__
            host=self.address[0],
    TypeError: 'NoneType' object is not subscriptable

##### Steps to reproduce the problem:
1. Open `mitmproxy`
2.  set a value for `view_filter` in Options or using the ` : set view_filter={str} `
3. Open a attached browser and open any url
4. Quit the browser and Open the Eventlog in mitmproxy. 

##### Any other comments? What have you tried so far?
Another error occuring for the view_filter option. I was working on a fix for #2801 #2951 when i noticed this other error occurs if any value is setup in view_filter. I think it requires a complete patch once and for all. 

##### System information
Mitmproxy: 4.0.0.dev103 (commit 77ed33b) 
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.14.21-1-MANJARO-x86_64-with-arch-Manjaro-Linux

**Comment by fenilgandhi** [comment] 2018-03-11 04:51
I noticed a weird thing, adding `time.sleep(1)` just before the return statement fixes the problem and no errors are generated. I am not sure why or how is this happening. 
https://github.com/mitmproxy/mitmproxy/blob/cc00b03554d84a37b55f911a84d70b6d7909c9cb/mitmproxy/connections.py#L212

**Comment by sozorogami** [comment] 2018-03-11 22:29
I'm seeing this too. The error appears onscreen and makes the feature hard to use. Is there a way to hide the error from displaying until a fix is found?

**Comment by mhils** [comment] 2018-03-14 23:19
Not sure why we have a connection with `address = None` at this point, but in any case we should make `ClientConnection.__repr__` and `ServerConnection.__repr__` robust so that they don't crash then. This can be either checked in those functions directly, or we amend `mitmproxy.util.human.format_address` to also accept `None` and then return "<no address information>" or something alike.

**Comment by fenilgandhi** [comment] 2018-03-19 04:45
@mhils  I think there is another way, we can handle this. As i noticed earlier, if we add `time.sleep(1)` before the return statement, somehow the self.address  is set to a actual address value. So instead of handling self.address for `None` , can we check whether self.address is `None` and if it is  give it some time set an actual value.

    if self.address is None:
            time.sleep(1)
    return {str}

**Comment by kajojify** [comment] 2018-03-19 07:57
@fenilgandhi I have an assumption concerning this issue. I am not sure it is absolutely correct.
As you can see the issue appears when mitmproxy tries to give us a representation of `ServerConnection` object, when `ValueError` is raised inside https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/view.py#L521

For some reasons for some flows `self.address` is still `None`, when we need it to be available in `ServerConnection`. When we write time.sleep(1), we suspend execution of the calling thread for 1 second. **Perhaps** mitmproxy switches to other available thread and this thread set the value for `self.address`. The problem is that suspended thread is `MainThread` and every new case with `self.address is None` almost all mitmproxy functions will stop for 1 second.

**Comment by fenilgandhi** [comment] 2018-03-19 10:05
@kajojify  I had the same notion but since i could not  find the setter/thread  which sets the value during the sleep, so i was not sure how to proceed with this. But if what you are saying is true, we can make sure that the setter method sets a value before the ServerConnection.__repr__  is returned. 

setting time.sleep(1) was just a first instinct, but yeah time.sleep(0.1) works well too.

**Comment by mhils** [comment] 2018-03-19 14:59
I can't reproduce this. Here's what I'm doing:

1. Start `mitmproxy`
2. `:set view_filter=foo`
3. switch to second window, enter `curl -x localhost:8080 -k https://google.com/`
4. Press `E` to open the event log.

**Comment by kajojify** [comment] 2018-03-19 15:25
@mhils I reproduced it only using a browser.

**Comment by mhils** [comment] 2018-03-23 03:29
I managed to reproduce this today by printing a flow in `http_connect`, which makes a bit of sense at least. This is addressed in #3008. Thanks again for the original report!

**Comment by fenilgandhi** [comment] 2018-03-23 14:48
@mhils, The pull-request #3008 only handles the scenario where the address is None and gracefully handles it but the bug which actually causes the value of an address to be None yet exists somewhere. 

So maybe until a fix can found for it, shall i keep this issue open or only handling the None value completely fixes the bug somehow ?

**Comment by mhils** [comment] 2018-03-23 15:00
I don't think there's another issue here. From the original traceback, it looks like we are checking if a flow is in the view, which isn't the case. This is totally expected, the problem here was that sortedcontainers used `{0!r}`, which triggers the flows `__repr__`, which then failed. It's okay for flows to have a server_conn.address of None, see e.g. the http_connect example.

**Closed by mhils** 2018-03-23 15:00 UTC
Labels: area/core, help wanted, kind/bug
