### ISSUE TITLE
Version 3.0.2 does not support script arguments.

### ISSUE THREAD

**Issue by clyfish** [mitmproxy/mitmproxy#2911] opened 2018-02-24 14:00 UTC
##### Steps to reproduce the problem:

$ mitmdump -p 8080 -s './replace.py a'
No such script: "./replace.py a"

##### Any other comments? What have you tried so far?

https://mitmproxy.readthedocs.io/en/v2.0.2/scripting/overview.html#handling-arguments
Version 3.0.2 does not support script arguments.

##### System information

Mitmproxy: 3.0.2 
Python:    3.6.1

**Comment by mhils** [comment] 2018-02-24 15:11
Thanks for the report! This is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/2862#issuecomment-364879561. You can find docs on how to add options to your script at https://mitmproxy.org/docs/latest/addons-options/! 😃 

(I'll leave this open for a bit for others to notice)

**Closed** 2018-03-19 15:11 UTC
Labels: kind/question
