### ISSUE TITLE
libGL error: MESA-LOADER: failed to open radeonsi

### ISSUE THREAD

**Issue by Dogey11** [mitmproxy/mitmproxy#5569] opened 2022-09-03 00:03 UTC
#### Problem Description
I get this error by running `mitmweb`, and the page never opens. `mitmproxy` works as intended, and I'm using the official linux binaries from mitmproxy.org

#### Steps to reproduce the behavior:
Occurs when trying to run `mitmweb`.

#### System Information
Mitmproxy: 8.1.1 binary
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.15.0-47-generic-x86_64-with-glibc2.35

**Comment by Dogey11** [comment] 2022-09-03 00:04
This is the full error:

```Web server listening at http://127.0.0.1:8081/
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[6934:6934:0902/165412.568584:ERROR:angle_platform_impl.cc(43)] Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[6934:6934:0902/165412.568695:ERROR:gl_display.cc(506)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[6934:6934:0902/165412.568724:ERROR:gl_display.cc(879)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[6934:6934:0902/165412.569858:ERROR:angle_platform_impl.cc(43)] Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[6934:6934:0902/165412.569897:ERROR:gl_display.cc(506)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[6934:6934:0902/165412.569924:ERROR:gl_display.cc(879)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[6934:6934:0902/165412.569948:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[6934:6934:0902/165412.570643:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[6989:6989:0902/165412.686093:ERROR:angle_platform_impl.cc(43)] Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[6989:6989:0902/165412.686234:ERROR:gl_display.cc(506)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[6989:6989:0902/165412.686281:ERROR:gl_display.cc(879)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[6989:6989:0902/165412.689057:ERROR:angle_platform_impl.cc(43)] Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:993 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[6989:6989:0902/165412.689182:ERROR:gl_display.cc(506)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[6989:6989:0902/165412.689220:ERROR:gl_display.cc(879)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[6989:6989:0902/165412.689255:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[6989:6989:0902/165412.690241:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so failed: /tmp/_MEI8SkjYW/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-13.so.1)
MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
[6967:7:0902/165412.725658:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

**Comment by Prinzhorn** [comment] 2022-09-04 06:47
I think this is a duplicate of #5522. Can you follow my instructions there and comment if it works?

**Closed** 2022-09-04 06:47 UTC
Labels: kind/triage
