### ISSUE TITLE
Missing source distribution in pypi

### ISSUE THREAD

**Issue by matejsp** [mitmproxy/mitmproxy#5991] opened 2023-03-16 14:26 UTC
#### Problem Description
There is no source uploaded from where the wheel was generated.
According to https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives

> You should always upload a source distribution and provide built distributions for the platforms your project is compatible with.

Why? We build packages ourselves so we know we can build it in case we need to fork the project from some specific version and we use:
> pip3.8 download --index-url https://pypi.python.org/simple --no-binary :all: <package_name>==<package_version>
> pip3.8 wheel <package_archive>.tar.gz

All other packages have source uploaded to pypi.

#### Steps to reproduce the behavior:
1. https://pypi.org/project/mitmproxy/#files
2. search for source tar.gz

**Comment by mhils** [comment] 2023-03-16 14:28
duplicate of #4892

**Closed by mhils** 2023-03-16 14:28 UTC
Labels: kind/triage
