### ISSUE TITLE
Allow launch via python

### ISSUE THREAD

**Issue by Mitch0S** [mitmproxy/mitmproxy#5171] opened 2022-03-11 09:53 UTC
I'm currently trying to create a web-filtering software, and there is no documentation on how to start mitmproxy via python, rather than terminal/cmd.

**Comment by Prinzhorn** [comment] 2022-03-11 11:01
This is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4297
This is not something we support and I don't think there are plans to do so.

What I _personally_ do is spawn a mitmdump child process and use an addon script to communicate with my application.

**Closed by Prinzhorn** 2022-03-11 11:01 UTC
Labels: kind/feature
