### ISSUE TITLE
"Clear list" also prompts to quit mitmproxy

### ISSUE THREAD

**Issue by ehabibov** [mitmproxy/mitmproxy#5864] opened 2023-01-12 15:15 UTC
#### Problem Description
When I want to clear current flows (which I do frequently) I also prompted to quit mitmproxy which is, at least, annoying.

#### Steps to reproduce the behavior:
1. Have any intercepted flows
2. Press 'z' (default) to clear list
3. Notice that despite cleared list mitmproxy also prompts user to quit application

![2023-01-12 17 08 47](https://user-images.githubusercontent.com/20490584/212104221-bf3e8d1e-4597-4358-91e0-9196673b6397.gif)

#### System Information
Mitmproxy: 9.0.1
Python:    3.11.0
OpenSSL:   OpenSSL 1.1.1s  1 Nov 2022
Platform:  macOS-12.5.1-x86_64-i386-64bit

**Comment by mhils** [comment] 2023-01-12 16:37
Thanks for the clear and concise description, but I unfortunately cannot reproduce this at all (there is no prompt when clearing). Can anyone else?

**Comment by ehabibov** [comment] 2023-01-12 16:44
I remember this happens quite long time - since summer (or even spring) when I was using mitm 8.x.x.

**Comment by ehabibov** [comment] 2023-01-12 17:45
Additionally have to mention that I use Oh My Zsh

**Comment by ehabibov** [comment] 2023-01-12 17:57
I'm sorry for flood. I just have investigated that cause most probably not a mitmproxy but something else related to shell.

Native Terminal:
![2023-01-12 19 48 29](https://user-images.githubusercontent.com/20490584/212141667-3cb4c9fc-e46f-4902-8511-9bd3422cdb67.gif)

Issue noticed in iTerm2 but interesting that, at least, terminal type and char encoding are same:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/20490584/212142220-804bf415-52fc-448f-a666-e92bb6aeb8c6.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/20490584/212142257-67612dda-df59-4c05-9117-d1f0ba328b3d.png">

@mhils if you think that there are nothing related to mitmproxy - close this issue, please.

**Comment by mhils** [comment] 2023-01-13 16:52
I'm pretty sure this is not a mitmproxy issue. Let's close this for now, if someone else experiences the same issues feel free to update here.

**Closed by mhils** 2023-01-13 16:52 UTC
Labels: kind/triage
