### ISSUE TITLE
No such script when full absolute path passed

### ISSUE THREAD

**Issue by michaelschem** [mitmproxy/mitmproxy#4389] opened 2021-01-08 03:08 UTC
When I pass a full path to mitmdump for a script, it says it can't find it.

```
/usr/local/bin/mitmdump -s "/Users/me/PycharmProjects/ApkRecon/src/Traffic_Logger.py --log /Users/me/PycharmProjects/ApkRecon/tests/APKs/ten --package com.example.myapplication --tag prod --sha256 774746add38dee815cd440090d8d4daaf2080f657802cef1a8354f49100355df" -p 6180 -w /Users/me/PycharmProjects/ApkRecon/tests/APKs/ten/dump --anticomp
```

I get the response
```
/usr/local/bin/mitmdump: No such script
```

It definately does exist

```
 % ls /Users/me/PycharmProjects/ApkRecon/src/Traffic_Logger.py
/Users/michaelschem/PycharmProjects/ApkRecon/src/Traffic_Logger.py
```

My version
```
mitmdump --version
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit
```

**Comment by Prinzhorn** [comment] 2021-01-08 10:20
You are passing this as the script _path_

```
/Users/me/PycharmProjects/ApkRecon/src/Traffic_Logger.py --log /Users/me/PycharmProjects/ApkRecon/tests/APKs/ten --package com.example.myapplication --tag prod --sha256 774746add38dee815cd440090d8d4daaf2080f657802cef1a8354f49100355df"
```

you cannot pass arguments this way. Scripts are meant for addons which have their own way of providing arguments called options. https://docs.mitmproxy.org/stable/addons-overview/

Closing as duplicate of #2862

**Closed by Prinzhorn** 2021-01-08 10:20 UTC
