### ISSUE TITLE
Ignor regex exclude not working

### ISSUE THREAD

**Issue by jarorg** [mitmproxy/mitmproxy#3013] opened 2018-03-25 11:40 UTC
I try to ignore all exclude example.com and use command:
`./mitmproxy --ignore-hosts '^(?!example\.com)' --mode transparent
`
Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017

But not work :-(
Can you help me tanks.

**Comment by kajojify** [comment] 2018-03-25 11:57
@jarorg Hi! 
For the latest version: `mitmproxy --ignore-hosts '^(?!example\.com)'`
More here -> https://docs.mitmproxy.org/master/howto-ignoredomains
Remember about this -> https://docs.mitmproxy.org/master/howto-ignoredomains/#limitations
The same for v2.0.2 -> https://mitmproxy.readthedocs.io/en/v2.0.2/features/passthrough.html#limitations
Good luck! :wink:

**Comment by jarorg** [comment] 2018-03-25 12:03
Nope, don't work on latest version to.

**Comment by kajojify** [comment] 2018-03-25 12:09
@jarorg it seems to work for me. 
Did you read about limitations. Hosts ignoring is applied only for HTTPS requests.

**Comment by jarorg** [comment] 2018-03-25 12:12
root@kali:~/mitm# # ./mitmdump -v --ignore-hosts '^(?!example\.com)' --mode transparent 
Proxy server listening at http://*:8080
10.0.2.15:32774: clientconnect
::ffff:10.0.2.15:32774: serverconnect
  -> ('93.184.216.34', 443)

**Comment by kira0204** [comment] 2018-03-25 12:29
Works for me too.

**Comment by jarorg** [comment] 2018-03-25 12:33
Also try by ip:
```
root@kali:~/mitm# ./mitmdump -v --ignore-hosts '^(?!93\.184\.216\.34)' --mode transparent
Proxy server listening at http://*:8080
10.0.2.15:32866: clientconnect
::ffff:10.0.2.15:32866: serverconnect
  -> ('93.184.216.34', 443)
```

**Comment by mhils** [comment] 2018-03-25 15:01
Hi,

This seems to be a duplicate of https://github.com/mitmproxy/mitmproxy/issues/2994?

**Comment by jarorg** [comment] 2018-03-25 15:55
Yes,  works for me
`
--ignore-hosts '^(?!example.com)(?![0-9\.]+:)'`


But now don't work with IP address:

`--ignore-hosts '^(?!8\.8\.8\.8)(?![0-9\.]+:)'`

**Comment by mhils** [comment] 2018-03-25 17:06
The regex in #2994 matches on everything that's not example.com `(?!example.com)` and not an IP address `(?![0-9\.]+:)`. I guess you have to fiddle a bit with some regex tools to adjust this to your needs. 😃

**Closed by mhils** 2018-03-25 17:06 UTC
