### ISSUE TITLE
mitmproxy has crashed.

### ISSUE THREAD

**Issue by nmweizi** [mitmproxy/mitmproxy#5677] opened 2022-10-25 04:32 UTC
Mitmproxy: 8.1.1
Python:    3.10.8
Platform:  macOS

1. mitmweb  -k --mode socks5  --set tcp_hosts=1.1.1.1
2. click 1.1.1.1 tcp connect
3. mitmweb has crashed.will appear randomly

```
SyntaxError: Unexpected token 'E', "Error gett"... is not valid JSON
    at JSON.parse (<anonymous>)
    at http://127.0.0.1:8081/static/app.js:58:40197
    at Object.ci [as useMemo] (http://127.0.0.1:8081/static/app.js:5:60363)
    at bt.useMemo (http://127.0.0.1:8081/static/app.js:1:8594)
    at Messages (http://127.0.0.1:8081/static/app.js:58:40184)
    at Ch (http://127.0.0.1:8081/static/app.js:5:55397)
    at li (http://127.0.0.1:8081/static/app.js:5:65240)
    at ck (http://127.0.0.1:8081/static/app.js:9:9936)
    at bk (http://127.0.0.1:8081/static/app.js:9:1017)
    at ak (http://127.0.0.1:8081/static/app.js:9:923)

Component Stack:
    at Messages (http://127.0.0.1:8081/static/app.js:58:39944)
    at section
    at TcpMessages (http://127.0.0.1:8081/static/app.js:58:41545)
    at div
    at FlowView (http://127.0.0.1:8081/static/app.js:58:42192)
    at div
    at MainView (http://127.0.0.1:8081/static/app.js:58:49804)
    at div
    at ProxyAppMain (http://127.0.0.1:8081/static/app.js:62:3048)
    at ConnectFunction (http://127.0.0.1:8081/static/app.js:51:11352)
    at Provider (http://127.0.0.1:8081/static/app.js:51:8664)
```

**Comment by mhils** [comment] 2022-10-25 11:53
We need some better instructions on how this can be reproduced.

**Comment by Prinzhorn** [comment] 2022-10-25 13:34
The error message is a duplicate of #5267, maybe they're coming from missing tcp support in mitmweb? I can't find when this was merged, but it's still not released, right?

**Comment by mhils** [comment] 2022-10-25 13:42
TCP is in mitmproxy 8, see https://mitmproxy.org/posts/releases/mitmproxy8/

**Closed** 2022-10-26 16:47 UTC
Labels: kind/triage
