### ISSUE TITLE
mitm's memory usage

### ISSUE THREAD

**Issue by nbdsp** [mitmproxy/mitmproxy#844] opened 2015-11-24 17:30 UTC
I have mitm installed on ArchArm on Raspberry Pi where it runs without restarting for days. It's only used  for proxying pages to one browser on another machine. While running, mitm's memory usage steadily grows (e.g. now, without any browser using it, I see in the 'top' that mitm uses 'VIRT 364m RES 266m' whereas yesterday it was 'VIRT 248m RES 169m' ). I don't know, maybe mitm is designed for massive scale proxying and caches memory for optimal performance, but is it possible to tweak some settings to reduce memory usage? Or it's just simpler to restart it periodically with a script?

**Comment by mhils** [comment] 2015-11-24 17:34
Just to clarify - are you running mitmproxy or mitmdump?

**Comment by nbdsp** [comment] 2015-11-24 17:45
mitmdump with a simple python script writing html content to disk. It's started with the command:

`mitmdump -b hostname -p portnumber -q -s myscript.py`

**Comment by mhils** [comment] 2015-11-24 17:47
Thanks. This looks like a duplicate of #620 then - I'm closing this here. :smiley:

**Closed by mhils** 2015-11-24 17:47 UTC
