### ISSUE TITLE
improve allow-hosts regex matching

### ISSUE THREAD

**Issue by SWW13** [mitmproxy/mitmproxy#4001] opened 2020-05-16 17:07 UTC
#### Problem Description
The regex used with `--allow-hosts` with `mitmdump -v --mode transparent --showhost` doesn't work at all or at least not in a logical expected manner.
`--allow-hosts '^.*:443$'` shows requests
`--allow-hosts '^[a-z0-9].*:443$'` shows requests
`--allow-hosts '^[a-z].*:443$'` does **not** shows requests
`--allow-hosts '^[0-9].*:443$'` does **not** shows requests
According to this logic the first symbol of the host must be a number and a character.

#### Steps to reproduce the behavior:
1. run `mitmdump -v --mode transparent --showhost --allow-hosts '^[0-9].*:443$'`

#### System Information
```
Mitmproxy: 5.1.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.6.13-arch1-1-x86_64-with-glibc2.2.5
```

**Comment by mhils** [comment] 2020-05-16 17:10
Look at your event log - it likely matches on both IP and host at some point or another. Take a look at your mitmproxy event log and https://docs.mitmproxy.org/stable/howto-ignoredomains/#limitations.

**Comment by SWW13** [comment] 2020-05-16 17:12
```
Proxy server listening at http://*:8080
10.42.128.143:50573: clientconnect
10.42.128.143:50574: clientconnect
::ffff:10.42.128.143:50574: serverconnect
  -> ('1.2.3.4', 443)
```
Disabling `--showhost` doesn't help either.

**Comment by SWW13** [comment] 2020-05-16 17:14
So the limitation is that `--allow-hosts` doesn't work? Why is this than even there and why is there no note in the help about that not working feature?

**Comment by mhils** [comment] 2020-05-16 17:39
I haven't really played around with this, this feature has been contributed by @pierlon in https://github.com/mitmproxy/mitmproxy/pull/3526, then @BlownSnail fixed some things in https://github.com/mitmproxy/mitmproxy/pull/3826. The steps you listed to reproduce this are not helping much as you don't mention your client setup. A simple repro with cURL would be useful, for example.

Lastly, it would be helpful if you could consider your tone.

**Comment by SWW13** [comment] 2020-05-16 17:46
> Lastly, it would be helpful if you could consider your tone.
Sorry about that, it was very frustrating trying to do a regex match with no help, documentation or examples about it and trying to reasoning about how the regexes are working.

The main problem seems to be the lack of proper documentation, I'm writing some examples so others should not need to feel the same pain.

**Comment by mhils** [comment] 2020-05-16 17:58
Debugging can be painful - no worries.

I haven't checked this, but from a cursory glance it looks like the problem is around here:

https://github.com/mitmproxy/mitmproxy/blob/67372d26ae213ca083c75ecaf5752c49a6c0ef17/mitmproxy/proxy/root_context.py#L51-L63

We first match on the server address (which should be an IP in transparent mode, or a domain name in regular mode), and then additionally check the server name indication. If either is true, we ignore the flow.

**Comment by SWW13** [comment] 2020-05-16 18:38
> We first match on the server address (which should be an IP in transparent mode, or a domain name in regular mode), and then additionally check the server name indication. If either is true, we ignore the flow.

So the options `*-hosts` should probably split up into `*-snis` and `*-ips` and making `*-hosts` an alias for both. Besides the need for a documentation about the `--allow-hosts` option.

**Comment by mhils** [comment] 2020-05-16 18:55
That introduces additional problems. What's the expected behavior of a plain HTTP request with `--allow-snis example.com`?

Long story short, I think the easier approach is to redefine `--allow-hosts`. Instead of the current
```python
ignore = (not any_allow_pattern_matches(ip)) or (not any_allow_pattern_matches(sni))
```
we should have it as
```python
ignore = not (any_allow_pattern_matches(ip) or any_allow_pattern_matches(sni))
```

-------------------

The current implementation of `--ignore-hosts` is
```python
ignore = any_ignore_pattern_matches(ip) or any_ignore_pattern_matches(sni)
```
which I think is fine.

**Comment by SWW13** [comment] 2020-05-16 19:02
The HTTP case is indeed a problem and would lead to more confusion.
That sounds like a good solution to me. The only downside would be that it removes the ability to match against IP and SNI hostname.

**Comment by mhils** [comment] 2021-02-14 11:15
This should be fixed on master!

**Closed by mhils** 2021-02-14 11:15 UTC
Labels: area/protocols, help wanted, kind/bug
