### ISSUE TITLE
Constant exceptions in callback StreamReaderProtocol.connection_made... at asyncio.streams.py when using transparent mode

### ISSUE THREAD

**Issue by q2dg** [mitmproxy/mitmproxy#6600] opened 2024-01-13 16:58 UTC
#### Problem Description
Mitmproxy's event logs doesn't stop showing this same error when proxying any HTTP/S traffic from some "victim"ś browser:

![mitmproxyerror](https://github.com/mitmproxy/mitmproxy/assets/7274874/781c0406-37fc-4690-bdcc-d00b63997ffc)

#### Steps to reproduce the behavior:
1. Put Mitmproxy in transparent mode
2. Navigate from "victim's" browser

#### System Information
10.2.1

**Comment by mhils** [comment] 2024-01-13 17:03
Please 1) do not post tracebacks as screenshots and 2) provide full system information as in the issue template.

**Comment by q2dg** [comment] 2024-01-13 21:25
Sorry. My system is a Ubuntu 22.04.2 and the output of `mitmproxy --version` is:

```
Mitmproxy: 10.2.1 binary
Python: 3.12.1
OpenSSL: OpenSSL 3.1.4 24 Oct 2023
Platform: Linux-5.19.0.46-generic-x86_64-with-glibc2.35
```

I attach here the log obtained from adding error redirection to Mitmproxy command, ran like this: `mitproxy -m transparent --showhost 2> errors.log`

Thanks a lot

[errors.log](https://github.com/mitmproxy/mitmproxy/files/13929543/errors.log)

**Comment by FreelancerCGN** [comment] 2024-01-18 20:01
I can confirm this error @q2dg 

Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform: Linux (different kernels)

**Comment by mhils** [comment] 2024-01-21 14:40
I can reproduce this error when shutting down mitmproxy, but I cannot reproduce this during operation. Can you folks clarify when you are hitting this?

**Comment by FreelancerCGN** [comment] 2024-01-21 14:45
I can also see these errors when I shut down mitmproxy, that's correct.

**Comment by mhils** [comment] 2024-01-21 14:50
To clarify: Do you see this *only* during shutdown (still a valid bug report of course), or also while mitmproxy is still running?

**Comment by mhils** [comment] 2024-01-21 15:13
After some digging: I think this can only be triggered during shutdown, and this will be fixed by https://github.com/python/cpython/pull/113690, which will be part of Python 3.12.2.

**Comment by q2dg** [comment] 2024-01-21 16:07
Well, I've seen this error triggered during Mitmproxy execution, shown at bottom of its screen in color red (so in event screen pushing "e" hotkey, too). Le'ts wait to Python 3.12.2 to see what happens but I opened this issue because of that, if I'd seen only when shutting down Mitmproxy I'd not have given it importance.

**Comment by Shnitzelil** [comment] 2024-02-19 21:51
Hello @mhils ,
Python 3.12.2 is out.
Is it possible to validate this issue?

Thanks!

**Comment by Shnitzelil** [comment] 2024-02-20 07:30
> Well, I've seen this error triggered during Mitmproxy execution, shown at bottom of its screen in color red (so in event screen, when pushing the "e" hotkey, too). Le'ts wait to Python 3.12.2 to see what happens but I opened this issue because of that: if I'd seen only when shutting down Mitmproxy I'd not have given it importance.

Python 3.12.2 is out..

**Comment by mhils** [comment] 2024-03-06 21:18
mitmproxy 10.2.3 is out, which should fix this.

**Closed by mhils** 2024-03-06 21:18 UTC
Labels: kind/triage
