### ISSUE TITLE
tornado.websocket.WebSocketClosedError

### ISSUE THREAD

**Issue by anchoon** [mitmproxy/mitmproxy#5498] opened 2022-07-27 18:49 UTC
![image](https://user-images.githubusercontent.com/92065528/181349384-d0d9a608-37d2-42db-aac9-a4afc3c6c3ef.png)

**Comment by Prinzhorn** [comment] 2022-08-01 15:18
Can you provide any steps to reproduce this error? Please follow the issue template for bug reports.

**Comment by Prinzhorn** [comment] 2022-08-01 15:19
I will tentatively close this as a duplicate of #5405

**Closed by Prinzhorn** 2022-08-01 15:19 UTC
Labels: kind/triage
