### ISSUE TITLE
Replaying webpages using mitmdump in --server-replay-kill-extra mode leads to in-completion of some requests, leading to blocking webpage unload event.

### ISSUE THREAD

**Issue by usama6naseer** [mitmproxy/mitmproxy#3966] opened 2020-05-01 06:22 UTC
#### Problem Description
I am not sure whether it counts as a bug but this leads to problems with replaying the webpages as the browser gets hanged at these incomplete requests. Basically the "extra" requests are killed at proxy side, without gracefully shutting them down at the client side. Any opinions on how to fix this?

Ideally, I would like to gracefully shutdown such requests,  by sending HTTP 404 or empty content.

TIA

**Comment by mhils** [comment] 2020-05-08 20:46
Yeah, that sounds like a reasonable suggestion. I'd be fine with returning a 404 or 503 instead. If someone wants the old behavior back, we can make it configurable if we are ever so inclined. I'd be happy to merge a PR!

**Comment by davehunt** [comment] 2021-11-03 14:09
Dupe of #3489?

**Comment by mhils** [comment] 2021-11-03 14:10
yes, thanks! 🍰

**Closed by mhils** 2021-11-03 14:10 UTC
Labels: kind/feature, area/addons
