### ISSUE TITLE
--ssl-insecure or -k is not being respected

### ISSUE THREAD

**Issue by Neolo** [mitmproxy/mitmproxy#3908] opened 2020-04-06 23:13 UTC
#### Problem Description
mitmproxy --mode socks5 --listen-port 1080 --ssl-insecure

"Error in HTTP connection: Certificate verification error for None: self signed certificate in certificate chain (errno: 19, depth: 2)
clientdisconnect
clientconnect
Certificate verification error for None: self signed certificate in certificate chain (errno: 19, depth: 2)
Invalid certificate, closing connection. Pass --ssl-insecure to disable validation."

#### Steps to reproduce the behavior:
Just open anything with self-signed cert, socks5 mode.

#### System Information
> Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.0.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  macOS-10.15.3-x86_64-i386-64bit

**Comment by mhils** [comment] 2020-04-08 15:51
I can't reproduce this:
```
λ curl -k --socks5-hostname localhost:1080 https://self-signed.badssl.com/
```
works fine. Here's how I invoke mitmproxy:
```
λ mitmdump --mode socks5 --listen-port 1080 --ssl-insecure
Proxy server listening at http://*:1080
127.0.0.1:52598: clientconnect
::ffff:127.0.0.1:52598: Certificate verification error for self-signed.badssl.com: self signed certificate (errno: 18, d
epth: 0)
::ffff:127.0.0.1:52598: Ignoring server verification error, continuing with connection
127.0.0.1:52598: GET https://self-signed.badssl.com/
              << 200 OK 502b
127.0.0.1:52598: clientdisconnect
```

**Comment by Neolo** [comment] 2020-04-09 05:21
You kidding me, right? There is a bunch of the reports of the same issue in your issue tracker. I posted an exact output of the log. If you can't reproduce, than this is solely your problem, but it doesn't meant bug doesn't exist. Perhaps you should follow what I have wrote, that it's on MACOS.
I used ssl split and it worked fine, comparing to mitmproxy. Bye!

**Comment by Neolo** [comment] 2020-04-09 05:24
Whoever will find this issue and gets pissed of, because author doesn't bother to fix it for years, **ditch mitmproxy and use SSL SPLIT**

**Comment by mhils** [comment] 2020-04-09 06:49
I'm glad you have found something that works for you! 

Closing this as a duplicate of #3865.

**Closed by mhils** 2020-04-09 06:49 UTC
Labels: kind/triage
