### ISSUE TITLE
Codec can't encode character: surrogates not allowed

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#2075] opened 2017-02-28 14:39 UTC
##### Steps to reproduce the problem:

1. mitmdump -T --host -s main.py
2. make a request with \udcb0 character

##### System information

```
Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.1
Platform: Linux-2.6.32-642.13.1.el6.x86_64-x86_64-with-centos-6.8-Final
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS 6.8 Final
```

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 126, in mitmdump
    master.run()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/dump.py", line 69, in run
    super().run()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/master.py", line 84, in run
    self.tick(0.1)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 224, in response
    self.echo_flow(f)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 196, in echo_flow
    self._echo_request_line(f)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 144, in _echo_request_line
    self.echo(line)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 54, in echo
    click.secho(text, file=self.outfp, **style)
  File "/usr/local/lib/python3.5/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.5/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb0' in position 148: surrogates not allowed
```

**Comment by mhils** [comment] 2017-03-01 09:06
Thanks. It looks like we need to remove surrogates in `Dumper.echo`. :)

**Comment by sxss0** [comment] 2017-03-02 04:09
Similar to the first one.

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 11, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 126, in mitmdump
    master.run()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/dump.py", line 69, in run
    super().run()
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/master.py", line 84, in run
    self.tick(0.1)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/master.py", line 109, in tick
    handle_func(obj)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/controller.py", line 70, in wrapper
    master.addons(f.__name__, message)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 90, in __call__
    self.invoke(i, name, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addonmanager.py", line 85, in invoke
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 228, in error
    self.echo_flow(f)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 196, in echo_flow
    self._echo_request_line(f)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 144, in _echo_request_line
    self.echo(line)
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/addons/dumper.py", line 54, in echo
    click.secho(text, file=self.outfp, **style)
  File "/usr/local/lib/python3.5/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.5/site-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 216-239: ordinal not in range(128)
```

**Comment by iharsh234** [comment] 2017-03-06 12:13
Hi , @mhils  , can this be resolved with something like this?.  I am not able to reproduce it for now. :sweat_smile: 
```
def echo(self, text, ident=None, **style):
        if ident:
            text = indent(ident, text)
        click.secho(text.encode('utf-8', 'surrogateescape').decode('utf-8', 'replace'), file=self.outfp, **style)
        if self.outfp:
            self.outfp.flush()
```

**Comment by mhils** [comment] 2017-03-06 12:31
This looks decent, but we definitely need a reproducible test case in the first place.

**Comment by kajojify** [comment] 2018-02-17 08:22
I wrote a reproducible test case, but I still can't reproduce it in real life :sweat_smile:
Can we fix it without real life example?

**Comment by mhils** [comment] 2018-02-18 22:17
@kajojify: Just the test is fine, but where are you struggling with reproducing this? usually just sending a few \xFF bytes should trigger this.

**Comment by hartwork** [comment] 2020-02-20 13:27
> @kajojify: Just the test is fine, but where are you struggling with reproducing this? usually just sending a few \xFF bytes should trigger this.

To reproduce from _inside_ Python, it takes any isolated [surrogate character](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates), e.g.:
```
In [2]: list(sys.version_info)                                                                             
Out[2]: [3, 6, 10, 'final', 0]

In [3]: '\ud800'.encode('utf-8')
[..]
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 0: surrogates not allowed
```
Once there is data exchange _outside_ of high level code point strings involved, you'll need to find ways to pass invalid characters around without running into encoding/decoding errors. I guess that's the tricky part.

**Comment by 0x539-Samy** [comment] 2020-06-15 09:45
i have same error with terraform 0.12 but it work with terraform version 0.11.10 for me https://releases.hashicorp.com/terraform/0.11.10/

**Comment by Kriechi** [comment] 2020-12-18 21:32
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.

**Closed by Kriechi** 2020-12-18 21:32 UTC
Labels: area/addons, kind/bug
