### ISSUE TITLE
mitmdump memory usage is always constantly growing

### ISSUE THREAD

**Issue by r00t-** [mitmproxy/mitmproxy#4456] opened 2021-02-17 03:23 UTC
(orignally mentioned in #4451 , but i don't think it's related to the issue discussed there and should get a separate ticket)

#### Problem Description
i use mitmdump for interactive browsing a lot.
that is, i run an mitmdump instance continuously, and use it from multiple browsers on multiple computers.

i find that mitmdump's memory usage constantly grows,
it *appears* as if it allocates memory for any request/response data it processes and then never frees it.
note that i would _expect_ this behaviour from mitmproxy running interactively, as it displays all the data in the UI,
but mitmdump should have no reason to keep flows in memory after writing them out.

here's a typical mitmdump memory usage graph out of my monitoring stack:
![mitmdump_rss](https://user-images.githubusercontent.com/2834981/108147170-b9efb380-70ce-11eb-8389-89997a72cb5b.png)

mitmdump memory usage appears as a sawtooth pattern, rising until it's terminated.
the growth rate is currently typically around 500mb/hour, it was less in the past, when it got through a whole day with under 2gb,
and is higher than the rate of data actually dumped (under 1gb/day). 
in this graph mitmdump is manually terminated a few times, because of debugging #4451, and by a daily restart at midnight.
(i also run a script that terminates it if it exceeds 3gb, to avoid it taking down my system.)

some very rare phases of non-growth (as seen in the graph above) are very unlikely related to zero traffic - thanks to websites constantly loading stuff in the background nowadays, and many browsers and tabs, it's unlikely that traffic is ever zero.

i see some _extremely_ rare occurences (at most once a week) of larger amounts of memory being allocated and freed again, in the expected pattern of allocating it to handle a request, and freeing it again after the request is finished.

#### Steps to reproduce the behavior:
1. run mitmdump for a longer period and use it, possibly with multiple browsers with a large number of tabs open  
2. observe memory usage

#### System Information
i think it has been the case ever since i started using mitmproxy, the above graph is of current git master. (running with `--set proxy_debug -vvv`, but it doesn't make a difference to the behaviour.)

**Comment by mhils** [comment] 2021-02-17 17:14
I assume the drops are restarts and not done by mitmproxy itself? 😄 

Based on https://gist.github.com/r00t-/a35b52b68cd457a455bc515c4294a36a you seem to have a bunch of flow objects around that are not garbage collected. I have written a small mitmproxy addon that overwrites SIGUSR1 and outputs which other objects still hold a reference:

```python
import collections
import gc
import os
import signal

from mitmproxy import flow


def debug(*_):
    print()
    print("Memory")
    print("=======")
    gc.collect()

    d = collections.Counter()
    for o in gc.get_objects():
        t = str(type(o))
        if "mitmproxy" in t:
            d[t] += 1

    for t, count in d.most_common(10):
        print(count, t)

    print()
    print("Flow References")
    print("===============")
    objs = gc.get_objects()
    for i in range(len(objs)):
        if isinstance(objs[i], flow.Flow):
            print(f"{objs[i]}")
            holder = {"val": objs[i]}

            # We hold references here ourselves. Ignore those, and make sure that we don't run into cycles.
            _seen = {id(objs), id(holder)}

            def seen(x):
                if x in _seen:
                    return True
                _seen.add(x)

            for _ in range(20):
                referrers = [
                    val for val in gc.get_referrers(holder["val"])
                    if not seen(id(val))
                ]
                if referrers:
                    print(f"  {len(referrers)=} {type(referrers[0])=}")
                    holder["val"] = referrers[0]
                    del referrers
                else:
                    break
            break
    else:
        print("No flows!")


def load(loader):
    print(f"Registering debug signal... {os.getpid()}")
    signal.signal(signal.SIGUSR1, debug)
```

If you run this as a regular mitmproxy addon, sending SIGUSR1 should show you 1) object statistics and 2) the reference chain for the first flow object found. Does that yield anything useful?

**Comment by r00t-** [comment] 2021-02-17 21:06
cool, i was wondering if the object stats in that that dump are expected or not.
i'll try this as i get to it, but as mentioned, #4451 is the more important issue for me.
(i have also not used addons before, time to learn something new ;) )

**Comment by mhils** [comment] 2021-02-17 21:56
> cool, i was wondering if the object stats in that that dump are expected or not.

If there are no active connections, I have zero flow.Flow instances in mitmdump. Anything else is unintended behavior. :)

**Comment by r00t-** [comment] 2021-02-19 15:51
curiously, since the three fixes from #4451 (and #5532 ) are in, memory usage has never exceeded 200mb.
is it possible that objects were simply not being cleaned up after those crashes?
did you expect the memory usage and crashes to be related? it was not obvious to me.

![mitmdump_mem_commits](https://user-images.githubusercontent.com/2834981/108527018-1969e100-72d2-11eb-8abb-1befac4ea325.png)
the three marks are deploys of the last three commits,
https://github.com/mitmproxy/mitmproxy/commit/c8eca9a396adb63f50e00506c53cf24ec723291d
https://github.com/mitmproxy/mitmproxy/commit/ff4120d4f3dd1d786377a541ec790945ae321b08
https://github.com/mitmproxy/mitmproxy/commit/70e08c880cadc5b87eb5187787a65c7857e0750c

but i also added `--no-http2` about an hour after the last one.

**Comment by mhils** [comment] 2021-02-19 18:57
> is it possible that objects were simply not being cleaned up after those crashes?

There really isn't anything that should keep them around... some cyclic references in the traceback objects, maybe? I am not convinced, but I also don't mind them going away without much effort. 😅 To put a positive spin on this: if they reappear the script from https://github.com/mitmproxy/mitmproxy/issues/4456#issuecomment-780710897 should help us out. :)

**Comment by r00t-** [comment] 2021-02-19 20:22
> you have got me to the point that I'm tunneling all my own traffic through mitmproxy
already losing my newly gained tester positon ;(

![mitmdump_mem_2020-02-19](https://user-images.githubusercontent.com/2834981/108554353-40390f00-72f4-11eb-9cf0-ecda132b05c3.png)
the run starting at ~1:50 is with `--no-http`, at 16:30 i turned http2 back on and loaded the script you provided above.
so:
```
Memory
=======
4515 <class 'mitmproxy.websocket.WebSocketMessage'>
573 <class 'mitmproxy.certs.Cert'>
563 <class 'mitmproxy.http.Headers'>
378 <class 'mitmproxy.proxy.context.Context'>
342 <class 'mitmproxy.http.HTTPFlow'>
342 <class 'mitmproxy.http.Request'>
342 <class 'mitmproxy.http.RequestData'>
262 <class 'mitmproxy.connection.Server'>
221 <class 'mitmproxy.http.Response'>
221 <class 'mitmproxy.http.ResponseData'>

Flow References
===============
<WebSocketFlow (1109 messages)>
  len(referrers)=2 type(referrers[0])=<class 'set'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addons.save.Save'>
  len(referrers)=3 type(referrers[0])=<class 'list'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addonmanager.AddonManager'>
  len(referrers)=49 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.tools.dump.DumpMaster'>
  len(referrers)=36 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'module'>
  len(referrers)=34 type(referrers[0])=<class 'dict'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'module'>
  len(referrers)=198 type(referrers[0])=<class 'builtin_function_or_method'>
```

**Comment by mhils** [comment] 2021-02-19 20:49
Imitation is the sincerest form of flattery. 😋 Jokes aside, really appreciate your super useful bug reports. :)

The log explains a lot. You are probably running `mitmdump -w something` and the `Save` addon is simply not discarding errored flows right away. This should be easily fixable! :)

**Comment by mhils** [comment] 2021-02-19 21:20
#4461 has the fix for the Save addon. There might be other memleaks, but I don't see any on my system at the moment. If there are, the script should point out the next one. :)

**Comment by r00t-** [comment] 2021-02-23 23:24
is it plausible that all of that memory is from messages on websocket connections that are still open?

if so, would it be a valid feature for mitmproxy (or probably just a possible plugin) to close close all active websockets and flush their data?
(as it would probably also mean that that data is lost on exit.)

i updated my daily restart script to send SIGUSR1 before sigterm, so this is the memory graph for yesterday, with associated memory stats from just before shutdown.
(graph with gigabyte scale this time)
![mitmdump_rss_2021-02-23](https://user-images.githubusercontent.com/2834981/108920981-ee66f080-7635-11eb-83c7-c03fc95ca9af.png)
```
Memory
=======
16500 <class 'mitmproxy.websocket.WebSocketMessage'>
1347 <class 'mitmproxy.certs.Cert'>
818 <class 'mitmproxy.proxy.context.Context'>
816 <class 'mitmproxy.http.Headers'>
416 <class 'mitmproxy.http.HTTPFlow'>
416 <class 'mitmproxy.http.Request'>
416 <class 'mitmproxy.http.RequestData'>
416 <class 'mitmproxy.proxy.layers.http.HttpStream'>
400 <class 'mitmproxy.http.Response'>
400 <class 'mitmproxy.http.ResponseData'>

Flow References
===============
<WebSocketFlow (2778 messages)>
  len(referrers)=2 type(referrers[0])=<class 'set'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addons.save.Save'>
  len(referrers)=3 type(referrers[0])=<class 'list'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addonmanager.AddonManager'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.tools.dump.DumpMaster'>
  len(referrers)=33 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'module'>
  len(referrers)=34 type(referrers[0])=<class 'dict'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'module'>
  len(referrers)=198 type(referrers[0])=<class 'builtin_function_or_method'>
```

**Comment by mhils** [comment] 2021-02-24 13:06
That is at least somewhat plausible, but did you have ~400 active HTTP connections when creating this screenshot? Probably not, so it looks like we still leak somewhere.

> if so, would it be a valid feature for mitmproxy (or probably just a possible addon) to have a way to close all active (websocket) connections and flush their data?
(as it would probably also mean that that data is otherwise lost on exit.)

You can probably write a custom addon that iterates through `asyncio.all_tasks()` and then cancels all connections... but that's a terrible workaround, not a solution. 😅  FWIW we do have [a watchdog](https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/proxy/server.py#L30-L64) that closes connections after ten minutes of absolutely no activity.

> (as it would probably also mean that that data is otherwise lost on exit.)

No, at least all active flows are written to disk on exit:

https://github.com/mitmproxy/mitmproxy/blob/4bd7b6c4eadeaca712f63e0e73f20bcf6aadbffb/mitmproxy/addons/save.py#L115-L118

Do you have any particular website that you suspect could be leaking here? Maybe you can modify your script to check for  `if isinstance(objs[i], http.HTTPFlow):` and then `print(objs[i].request.url)`. I'll also see if I can reproduce this locally. This week is super busy for me, so probably not before Sunday :)

**Comment by r00t-** [comment] 2021-03-02 05:19
thanks for the explanations on handling of flows!

> but did you have ~400 active HTTP connections when creating this screenshot? 

actually i think i saw 150 client connections when i checked after reading your post, so 400 is not completely unthinkable.
whatever my browsers were doing there - sadly i did not check in detail. ofcourse an excessive number of clients could explain the usage, but i can't imagine what those would be doing, i will re-check.

i added this to the script you provided:
```
    objs = gc.get_objects()
    for i in range(len(objs)):
        if isinstance(objs[i], http.HTTPFlow):
            print(f"HTTPFlow: {objs[i].request.url}")
```
at a first look with very little uptime, i find that the top of the list is always `https://venus.web.telegram.org/apiw1` (i see that URL all over my logs too, i guess that is from http://web.telegram.org/ ), and the count seems to be slowly but steadily growing. but i don't think those are possibly large enough to account for the usage observed.

**Comment by r00t-** [comment] 2021-03-02 13:37
it got killed by my script due to exceeding 2.5gb, 10 hours later.
in this case it's kind of obvious that some tab with twitch.tv open decided to start playing a video.
so as for that, this is possibly related to #4470 ... i don't have stream_large_bodies set, so mitmproxy buffers the whole stream in memory? for what i remember, it's actually possible to watch twitch streams through mitmproxy, as it loads seperate video segments in separate http requests, only latency is a bit higher than ususal. (but in this case all http request point to the exact same url, i will find out what exactly was playing there.)

in any case, telegram and wordpress look weird.

{code}
Memory
=======
36545 <class 'mitmproxy.websocket.WebSocketMessage'>
9801 <class 'mitmproxy.certs.Cert'>
7506 <class 'mitmproxy.proxy.context.Context'>
7456 <class 'mitmproxy.http.Headers'>
3729 <class 'mitmproxy.http.HTTPFlow'>
3729 <class 'mitmproxy.http.Request'>
3729 <class 'mitmproxy.http.RequestData'>
3729 <class 'mitmproxy.proxy.layers.http.HttpStream'>
3728 <class 'mitmproxy.connection.Server'>
3727 <class 'mitmproxy.http.Response'>
{code}

{code}
$ tail -n 10024 2021-03-02c.log | tac | sed -n '1,/Flow References/p' | grep ^HTTPFlow: | cut -d\? -f1 | sort|uniq -c|sort -nr
   2156 HTTPFlow: https://venus.web.telegram.org/apiw1
    754 HTTPFlow: http://private-wordpress-site/wp-admin/admin-ajax.php
     79 HTTPFlow: https://gql.twitch.tv/gql
     68 HTTPFlow: https://embeds.driftcdn.com/embeds/***.json
     63 HTTPFlow: https://c.go-mpulse.net/api/config.json
     59 HTTPFlow: https://video-edge-b0b5d3.pdx01.abs.hls.ttvnw.net/v1/segment/**removed**.ts
     59 HTTPFlow: https://static.twitchcdn.net/config/manifest.json
      6 HTTPFlow: https://connectivitycheck.gstatic.com/generate_204
{code}

(the references list seem to be missing because the script did not give mitmproxy enough time to log them before killing it.)

**Comment by hazcod** [comment] 2021-04-08 16:49
@r00t- I have stream_large_bodies set with `stream_large_bodies: "1k"` to enhance my comparable setup.
Any obvious use cases I can try to reproduce?

**Comment by r00t-** [comment] 2021-04-08 17:27
@hazcod:
setting `stream_large_bodies` is not an option for me, as i do want all data logged.
so if it's that, i rather live with the memory usage.

i could never pinpoint a specific site that causes or reproduces this.
the last stats dump i posted, showing even wordpress stuff sticking around made it seem to be a more general issue,
but i have no idea about the details of this.

**Comment by hazcod** [comment] 2021-04-09 14:22
I am able to reproduce with :

```shell
% curl -x localhost:3128 -v -o ~/Downloads/1gb.bin -k https://speed.hetzner.de/1GB.bin
```

**Comment by r00t-** [comment] 2021-04-09 16:29
> mitmproxy will get killed in my case when memory usage raises above 1GB, which happens every time I try download this file.

that is a different issue, or rather expected behaviour.
mitmproxy holds any stream in memory until exit,
mitmdump until it writes it our to disk.

this issue is about mitmdump's memory usage growing over time,
while the number of _active_ streams should not be growing.

**Comment by bratao** [comment] 2022-03-24 00:17
@mhils there is any pointers you can give me to how to solve or debug this problem?
I do have a constant running mitmproxy instance handling hundreds of connections, and I had to restart it daily because the memory do not stop growling

**Comment by mhils** [comment] 2022-03-25 18:35
Thanks @solovievv! The problem is that we keep all streams for a HTTP/2 connection around until the client disconnects, and some clients just keep using a single connection for a long time... That's not to blame the clients though, we "just" need to implement some logic to delete completed streams while the connection is still active.

**Comment by solovievv** [comment] 2022-03-25 23:51
> The problem is that we keep all streams for a HTTP/2 connection around until the client disconnects, and some clients just keep using a single connection for a long time... 

@mhils Could you explain why keepalive_expiry=5 mins doesn't help? As I understand it should close the connection every 5 mins

Is it possible to delete flows older than 5 mins(or any defined value) by a scheduler for example? It can be an additional option flow_lifetime.

mitmproxy is a great tool and solving this issue will allow using it in high loads. Please let me know what you think about it. Possibly I can help somehow.

**Comment by mhils** [comment] 2022-03-26 10:07
> Could you explain why keepalive_expiry=5 mins doesn't help? 

My guess would be that this five minute timer is reset after every request, the connection would only be expired after 5 mins of inactivity (which never happens).

Deleting old/completed flows is on my to-do list, it's just a somewhat nontrivial change that requires some thought. https://github.com/mitmproxy/mitmproxy/issues/4786#issuecomment-928002790 has another workaround. If not using keepalive causes performance issues, you can maybe do it randomly for every Nth flow.

**Comment by bra-fsn** [comment] 2022-04-22 12:11
I have the same (or similar) issue.
I start the proxy with `mitmproxy --set stream_large_bodies=1 --set  command_history=false --view-filter '!~all'` (tried to turn everything off which looked to keep state/history inside the process).

After this, `RSS` size of the process is `59888` bytes.

After running this:
```python
import requests

proxies = {
   'http': 'http://localhost:8080',
   'https': 'http://localhost:8080',
}

for i in range(1000):
    requests.get("http://ftp.fsn.hu/README")
```
the `RSS` grows to `73516` bytes and grows constantly with each HTTP requests.

Is it possible to use `mitmproxy` as a constantly running service without storing (meta)data from each flows getting through it?

**Comment by mhils** [comment] 2022-04-22 12:31
@bra-fsn: `view_filter` only controls which flows are currently visible. mitmproxy always keeps all flows in memory. If you want to avoid that, use `mitmdump` (which discards after completion) or manually clear the flow list within mitmproxy.

**Comment by bra-fsn** [comment] 2022-04-22 12:37
> @bra-fsn: `view_filter` only controls which flows are currently visible. mitmproxy always keeps all flows in memory. If you want to avoid that, use `mitmdump` (which discards after completion) or manually clear the flow list within mitmproxy.

I can see the same with `mitmdump`. RSS grows with each completed requests.

**Comment by mhils** [comment] 2022-04-22 13:44
@bra-fsn: Can I ask you to try the memoryleak branch (https://github.com/mitmproxy/mitmproxy/tree/memoryleak, https://mitmproxy.org/downloads/#branches/memoryleak/)?

rss stabilizes after a few minutes for me. I'm using your example and `mitmdump -q -s script.py`:
```python
import gc
import os
import psutil

def response(flow):
    gc.collect()
    print("rss", psutil.Process(os.getpid()).memory_info().rss)
```

**Comment by bra-fsn** [comment] 2022-04-22 14:20
> @bra-fsn: Can I ask you to try the memoryleak branch (https://github.com/mitmproxy/mitmproxy/tree/memoryleak, https://mitmproxy.org/downloads/#branches/memoryleak/)?
> 
> rss stabilizes after a few minutes for me. I'm using your example and `mitmdump -q -s script.py`:
> 
> ```python
> import gc
> import os
> import psutil
> 
> def response(flow):
>     gc.collect()
>     print("rss", psutil.Process(os.getpid()).memory_info().rss)
> ```

Sure. Starting the proxy with `PYTHONPATH=. python release/specs/mitmdump --set stream_large_bodies=1` from branch `memoryleak` gives an initial size of `54640`.
After 10.000 queries its RSS shows `59120`.
If I add `-s /tmp/script.py`, initial: `55568`, after 10k: `56544`.

If I use the `main` branch without the script:
initial: `54600`, 10k: `118152`
with the script:
initial: `55484`, 10k: `117708`

And the response times deteoriate pretty much (the last request is more than the double of the first one) with the number of completed requests.

Both branches are actual ATM.

**Comment by mhils** [comment] 2022-04-22 14:24
> If I add -s /tmp/script.py, initial: 55568, after 10k: 56544.

This pretty much seems like it fixes it, or would you disagree?

> And the response times deteoriate pretty much (the last request is more than the double of the first one) with the number of completed requests.

This is fixed on the memoryleak branch as well, correct?

**Comment by bratao** [comment] 2022-04-22 14:31
@mhils I'm super excited by this. Thank you!
(BTW, I previously spent a couple of hours debugging to discover the leak. I was planning to do another round using the https://github.com/bloomberg/memray released a few days ago. If you don´t know about it, may be helpful).

**Comment by bra-fsn** [comment] 2022-04-22 14:32
> > If I add -s /tmp/script.py, initial: 55568, after 10k: 56544.
> 
> This pretty much seems like it fixes it, or would you disagree?
> 
> > And the response times deteoriate pretty much (the last request is more than the double of the first one) with the number of completed requests.
> 
> This is fixed on the memoryleak branch as well, correct?

Yes to both!

**Closed** 2022-04-25 10:52 UTC
Labels: kind/triage

**Comment by avaitla** [comment] 2022-04-30 17:11
Nice one, we also just had a bunch of headache to debug this! Thanks for all the notes and work on this.

**Comment by bra-fsn** [comment] 2022-05-06 20:37
@mhils I think this alone deserves a new release. :)

**Comment by mhils** [comment] 2022-05-15 16:01
mitmproxy 8.1 is out now. :)
