### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reply'

### ISSUE THREAD

**Issue by marjomercado** [mitmproxy/mitmproxy#1387] opened 2016-07-21 15:44 UTC
##### Steps to reproduce the problem:

1. Run something like "mitmproxy --cert "example1.org=sslcerts/example1.org.pem" --cert "example2.org=sslcerts/example2.org.pem" --no-http2 --ignore devbox.com

##### What is the expected behavior?
No crash.

##### What went wrong?
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

----------------------------------------
Error in processing of request from 10.161.129.35:38896
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/netlib/tcp.py", line 854, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 64, in handle_client_connection
    h.handle()
  File "/usr/lib/python2.7/site-packages/mitmproxy/proxy/server.py", line 152, in handle
    self.channel.tell("clientdisconnect", root_layer)
  File "/usr/lib/python2.7/site-packages/mitmproxy/controller.py", line 68, in tell
    m.reply = DummyReply()
AttributeError: 'NoneType' object has no attribute 'reply'

##### Any other comments? What have you tried so far?
None.

---

Mitmproxy Version: 0.17
Operating System: Centos 7

**Comment by mhils** [comment] 2016-08-11 21:27
I cannot reproduce this on master anymore, I believe this should be fixed with the latest changes. Thanks for the report!

**Closed by mhils** 2016-08-11 21:27 UTC
Labels: bug, ready
