### ISSUE TITLE
HTTPS tunneling doesn't seem to work in mitmproxy

### ISSUE THREAD

**Issue by hiranya911** [mitmproxy/mitmproxy#3398] opened 2018-11-30 01:00 UTC
Not sure if I'm missing something obvious. But here goes:

##### Steps to reproduce the problem:

1. Start `mitmproxy`
2. Send a HTTPS proxy request (note that the proxy URL is HTTPS): 
```
curl -v -k https://jsonplaceholder.typicode.com/todos/1 --proxy-insecure --proxy https://localhost:8080
```

Output:

```
* Establish HTTP proxy tunnel to jsonplaceholder.typicode.com:443
> CONNECT jsonplaceholder.typicode.com:443 HTTP/1.1
> Host: jsonplaceholder.typicode.com:443
> User-Agent: curl/7.53.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 502 Bad Gateway
< Server: mitmproxy 4.0.4
< Connection: close
< Content-Length: 286
< Content-Type: text/html
< 
* Received HTTP code 502 from proxy after CONNECT
```

##### Any other comments? What have you tried so far?

HTTPS over HTTP tunneling works as expected:

```
$ curl -v -k https://jsonplaceholder.typicode.com/todos/1 --proxy http://localhost:8080
> GET /todos/1 HTTP/1.1
> Host: jsonplaceholder.typicode.com
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 30 Nov 2018 00:51:29 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 83
< Connection: keep-alive
```

##### System information

```
Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.17.0-3rodete2-amd64-x86_64-with-debian-buster-sid
```

**Comment by vulnz** [comment] 2019-01-31 13:01
did you go to mitm.it ?

**Comment by akrieger** [comment] 2019-02-04 19:14
I can repro. I'm using libcurl manually configured to go through mitmproxy.

`
V0204 10:59:10.174718 19300  [b223778bb103fd9d] == Info: TLSv1.2 (IN), TLS handshake, Finished (20):
V0204 10:59:10.175196 19300  [b223778bb103fd9d] <= Recv SSL data \x14\x00\x00\x0c%áÕÓu±\x0c0_¤e}
V0204 10:59:10.175741 19300  [b223778bb103fd9d] == Info: SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
V0204 10:59:10.176216 19300  [b223778bb103fd9d] == Info: ALPN, server accepted to use http/1.1
V0204 10:59:10.176729 19300  [b223778bb103fd9d] == Info: Proxy certificate:
V0204 10:59:10.177253 19300  [b223778bb103fd9d] == Info:  subject: [NONE]
V0204 10:59:10.179166 19300  [b223778bb103fd9d] == Info:  start date: Feb  2 18:59:10 2019 GMT
V0204 10:59:10.179417 19300  [b223778bb103fd9d] == Info:  expire date: Feb  3 18:59:10 2021 GMT
V0204 10:59:10.179975 19300  [b223778bb103fd9d] == Info:  issuer: CN=mitmproxy; O=mitmproxy
V0204 10:59:10.182257 19300  [b223778bb103fd9d] == Info:  SSL certificate verify ok.
V0204 10:59:10.182634 19300  [b223778bb103fd9d] == Info: allocate connect buffer!
V0204 10:59:10.186670 19300  [b223778bb103fd9d] == Info: Establish HTTP proxy tunnel to <redacted>.com:443
V0204 10:59:10.187552 19300  [b223778bb103fd9d] => Send SSL data \x17\x03\x03\x00{
V0204 10:59:10.188077 19300  [b223778bb103fd9d] => Send header CONNECT <redacted>.com:443 HTTP/1.1
V0204 10:59:10.188077 19300  Host: <redacted>.com:443
V0204 10:59:10.188077 19300  Proxy-Connection: Keep-Alive
V0204 10:59:10.188985 19300  [b223778bb103fd9d] <= Recv SSL data \x17\x03\x03\x01¬
V0204 10:59:10.189571 19300  [b223778bb103fd9d] <= Recv header HTTP/1.1 502 Bad Gateway
V0204 10:59:10.190241 19300  [b223778bb103fd9d] <= Recv header Server: mitmproxy 4.0.4
V0204 10:59:10.190873 19300  [b223778bb103fd9d] <= Recv header Connection: close
V0204 10:59:10.191675 19300  [b223778bb103fd9d] <= Recv header Content-Length: 286
V0204 10:59:10.192369 19300  [b223778bb103fd9d] <= Recv header Content-Type: text/html
`

Is it possibly the `V0204 10:59:10.187552 19300  [b223778bb103fd9d] => Send SSL data \x17\x03\x03\x00{` part is confusing mitmproxy if it's expecting the connect header first? Also it sends back SSL data so maybe that's expected.

**Comment by Neolo** [comment] 2020-09-13 23:34
Confirmed, CONNECT on http are not getting intercepted by mitmproxy

**Comment by Kriechi** [comment] 2020-12-18 21:27
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.

**Closed by Kriechi** 2020-12-18 21:27 UTC

**Comment by lubronzhan** [comment] 2022-02-17 23:38
Hi @Kriechi I just tried today:
1. Start mitmproxy: version: `6.0.2`
```
sudo ./mitmproxy -p 80  -k
```

First try a curl on the same VM where the proxy is running
```
kubo@jumper:~$ curl  -k --proxy https://10.206.98.187:80 https://githubstatus.com -v
* Rebuilt URL to: https://githubstatus.com/
*   Trying 10.206.98.187...
* Connected to 10.206.98.187 (10.206.98.187) port 80 (#0)
* Establish HTTP proxy tunnel to githubstatus.com:443
> CONNECT githubstatus.com:443 HTTP/1.1
> Host: githubstatus.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 600 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: githubstatus.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=githubstatus.com
* 	 start date: Tue, 15 Feb 2022 23:37:28 GMT
* 	 expire date: Fri, 17 Feb 2023 23:37:28 GMT
* 	 issuer: CN=mitmproxy,O=mitmproxy
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: githubstatus.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 129
< Server: GitHub.com
< Content-Type: text/html; charset=utf-8
< Last-Modified: Mon, 10 Dec 2018 11:23:48 GMT
< Access-Control-Allow-Origin: *
< ETag: "5c0e4cc4-81"
< expires: Fri, 28 Jan 2022 01:33:14 GMT
< Cache-Control: max-age=600
< x-proxy-cache: HIT
< X-GitHub-Request-Id: 14F0:1629:1B0CA2:234972:61F34620
< Accept-Ranges: bytes
< Date: Thu, 17 Feb 2022 23:37:28 GMT
< Via: 1.1 varnish
< Age: 0
< X-Served-By: cache-pao17453-PAO
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1645141049.703659,VS0,VE91
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 54e36816671633bbeaed20dfa098c86dca17920a
<
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=https://www.githubstatus.com/">
  </head>
  <body></body>
</html>
* Connection #0 to host 10.206.98.187 left intact
```

Try on my local machine
```
 ✘  ~  curl --proxy-insecure -k --proxy https://10.206.98.187:80 https://githubstatus.com -v
*   Trying 10.206.98.187...
* TCP_NODELAY set
* Connected to 10.206.98.187 (10.206.98.187) port 80 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Proxy certificate:
*  subject: [NONE]
*  start date: Feb 15 23:37:07 2022 GMT
*  expire date: Feb 17 23:37:07 2023 GMT
*  issuer: CN=mitmproxy; O=mitmproxy
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* allocate connect buffer!
* Establish HTTP proxy tunnel to githubstatus.com:443
> CONNECT githubstatus.com:443 HTTP/1.1
> Host: githubstatus.com:443
> User-Agent: curl/7.64.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 502 Bad Gateway
< Server: mitmproxy 6.0.2
< Connection: close
< Content-Length: 285
< Content-Type: text/html
<
* Received HTTP code 502 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 502 from proxy after CONNECT
```

I could see in the event log `10.166.136.*:50753: Cannot connect to server, no server address given.`
While `10.166.136.*` is my local ip address.

**Comment by lubronzhan** [comment] 2022-02-18 01:23
Ok looks like it only supports on 7+?
Secure Web Proxy: Mitmproxy now supports TLS-over-TLS to already encrypt the connection to the proxy.
https://mitmproxy.org/posts/releases/mitmproxy7/

**Comment by mhils** [comment] 2022-02-18 07:54
Correct, this only works on 7+.

**Comment by NathanPB** [comment] 2023-09-19 17:50
Sorry to reopen, but did anyone get this to work with ngrok or argo tunnels (cloudflare)?

`$ ngrok http 8080`
`$ mitmproxy -p 8080`

and paste the ngrok URL in my app to be proxied

It does not work. However, if I configure it to use just `http://192.168.0.1:8080` it works. Same for cloudflare tunnels.

I'm not sure how to debug this, but I believe that this is related

```
λ ~> mitmproxy --version
Mitmproxy: 10.0.0
Python:    3.11.5
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  Linux-6.5.3-arch1-1-x86_64-with-glibc2.38
```
