### ISSUE TITLE
mitm.it error 

### ISSUE THREAD

**Issue by liyuemin7** [mitmproxy/mitmproxy#4199] opened 2020-09-14 06:42 UTC
#### Problem Description

The phone can't be turned on mitm.it

#### Steps to reproduce the behavior:
1. After executing the (mitmweb -p 8080) command
2. Open in collection （mitm.it）
3. error:
Exception in thread TCPConnectionHandler (ProxyServer: ::ffff:114.240.84.34:59258 -> :::8080):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 602, in connection_thread
    self.handle_client_connection(connection, client_address)
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 66, in handle_client_connection
    self.channel
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 78, in __init__
    None)
  File "/usr/lib/python3.6/site-packages/mitmproxy/connections.py", line 38, in __init__
    super().__init__(client_connection, address, server)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 489, in __init__
    super().__init__(connection)
  File "/usr/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 297, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by mhils** [comment] 2020-09-19 22:23
Duplicate of #4200

**Closed by mhils** 2020-09-19 22:23 UTC
Labels: kind/triage
