### ISSUE TITLE
[Feature] Socks Mode With Upstream Proxy

### ISSUE THREAD

**Issue by realgam3** [mitmproxy/mitmproxy#2181] opened 2017-03-17 19:57 UTC
##### Features Needed:

1. Socks Mode With Upstream Proxy
2. HTTP Mode With Socks Upstream Proxy

##### Background Story:

While developing PyMultitor (Proxy Version) I used MitmProxy as a infrastructure,
My problem was that i couldn't use socks proxy on upstream mode,
My simple solution was to use requests + pySocks on request handler and then translate the response.
This solution will not work on tcp packets - that means that websockets won't work.

* I Hope in the future to remove the use of requests and i will be able to support websockets.

**Comment by Kriechi** [comment] 2017-03-21 20:48
duplicate of #211?

**Closed** 2017-06-04 12:52 UTC
