### ISSUE TITLE
mitmproxy install issues

### ISSUE THREAD

**Issue by saalmaan** [mitmproxy/mitmproxy#716] opened 2015-08-08 19:10 UTC
Hi All

I am trying to install mitmproxy but when I run it I get following errors

**System details:**
Mac: 10.10.4
Python version: 2.7.6
pip version: 7.1.0
mitmproxy: 0.13

**Error Log:**
```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 9, in <module>
    load_entry_point('mitmproxy==0.13', 'console_scripts', 'mitmproxy')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/libmproxy/main.py", line 7, in <module>
    from . import version, cmdline
  File "/Library/Python/2.7/site-packages/libmproxy/cmdline.py", line 5, in <module>
    from netlib import http
  File "/Library/Python/2.7/site-packages/netlib/http.py", line 7, in <module>
    from . import odict, utils, tcp, http_status
  File "/Library/Python/2.7/site-packages/netlib/tcp.py", line 26, in <module>
    'TLSv1.2': SSL.TLSv1_2_METHOD,
AttributeError: 'module' object has no attribute 'TLSv1_2_METHOD'
```

**Install log:**
```
sudo -H pip install mitmproxy                                                                                                     ◉ ◼◼◼◼◼◼◼◼◼◻
Collecting mitmproxy
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached mitmproxy-0.13.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyperclip>=1.5.8 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>0.1.2 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.2 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.3.6 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): netlib<0.14,>=0.13 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): urwid>=1.3 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): blinker>=1.3 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.2 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): configargparse>=0.9.3 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): html2text>=2015.4.14 in /Library/Python/2.7/site-packages (from mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /Library/Python/2.7/site-packages (from tornado>=4.0.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): certifi in /Library/Python/2.7/site-packages (from tornado>=4.0.2->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.15.1 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.9 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): passlib>=1.6.2 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): hpack>=1.0.1 in /Library/Python/2.7/site-packages (from netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /Library/Python/2.7/site-packages (from pyOpenSSL>=0.15.1->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): idna in /Library/Python/2.7/site-packages (from cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Library/Python/2.7/site-packages (from cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /Library/Python/2.7/site-packages (from cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cffi>=0.8 in /Library/Python/2.7/site-packages (from cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Library/Python/2.7/site-packages (from cffi>=0.8->cryptography>=0.9->netlib<0.14,>=0.13->mitmproxy)
Installing collected packages: mitmproxy
  Running setup.py install for mitmproxy
Successfully installed mitmproxy-0.13
```

**What I already tried:**
1. pip install mitmproxy -U
2. tried to uninstall and install mitmproxy again
3. restart my mac :)

Any suggestions?

--Many thanks

**Comment by Kriechi** [comment] 2015-08-08 20:01
duplicate of #705

**Closed by Kriechi** 2015-08-08 20:01 UTC

**Comment by karneaud** [comment] 2015-08-08 20:44
same here...and i'm running the latest openssl and cyrptography

**Comment by saalmaan** [comment] 2015-08-08 23:02
just found a simple solution to similar problem I had, I renamed the default openSSL folder

```
sudo mv /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_OpenSSL
```
