### ISSUE TITLE
Mitmproxy doesn't seem to work with ios9

### ISSUE THREAD

**Issue by niravnagda** [mitmproxy/mitmproxy#803] opened 2015-10-15 21:26 UTC
Hi,
I am trying to get the proxy working with ios9 and the ATS in the new os, is somehow not allowing the apps to recognize the certificate

I am getting "the client may not trust the proxy's certificate" error. I have certificate installed in the device

**Comment by ra7bi** [comment] 2015-10-16 10:28
i tested in my IOS 9 iphone 6 and it's works !

**Comment by mhils** [comment] 2015-10-16 13:45
@niravnagda, do you want to debug your own application or a third-party app?

**Comment by niravnagda** [comment] 2015-10-16 17:48
@ra7bi it works with browser connections, but with app it does not work

@mhils I am trying to get it working with an internal app

**Comment by mkagenius** [comment] 2015-10-26 10:35
I am primarily working with 3rd party apps. 

I tried 5 apps, 3 of them do not work on ios9 while the rest 2 work fine. 

Have you guys identified this issue?

**Comment by mhils** [comment] 2015-11-04 16:05
Not sure what the root cause is here - some apps employ certificate pinning, which is something we can't do much about (you need a jailbreak to patch that). 
I'm not sure if iOS 9's AppTransportSecurity is compatible with mitmproxy though - if someone wants to take a stab, playing around with [`nscurl --ats-diagnostics`](https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33) should provide some helpful insights. I don't own an OSX device to test that unfortunately.

**Comment by zeaphoo** [comment] 2015-11-11 09:29
mitmproxy 0.14

When disable Perfect Forward Secrecy(PFS), mitmproxy works perfect. But apple ATS require PFS to be opened.  Can mitmporxy support PFS?

```
/usr/bin/nscurl --ats-diagnostics https://apple.com -v
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://apple.com.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
ATS Dictionary:
{
}
2015-11-11 17:21:39.676 nscurl[60036:3294457] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fec31c131d0 [0x7fff7483f390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fec31c0e820 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31c0ed90 [0x7fff7483f390]>"
), NSUnderlyingError=0x7fec31e002b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x7fec31c131d0 [0x7fff7483f390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x7fec31c0e820 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31c0ed90 [0x7fff7483f390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://apple.com/, NSErrorFailingURLStringKey=https://apple.com/, NSErrorClientCertificateStateKey=0}
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
ATS Dictionary:
{
    NSAllowsArbitraryLoads = true;
}
Result : PASS
---

================================================================================

Configuring TLS exceptions for apple.com

---
TLSv1.2
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
        };
    };
}
2015-11-11 17:21:43.192 nscurl[60036:3294457] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fec31f21090 [0x7fff7483f390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fec31f20490 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31f20ba0 [0x7fff7483f390]>"
), NSUnderlyingError=0x7fec343000c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x7fec31f21090 [0x7fff7483f390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x7fec31f20490 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31f20ba0 [0x7fff7483f390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://apple.com/, NSErrorFailingURLStringKey=https://apple.com/, NSErrorClientCertificateStateKey=0}
---

---
TLSv1.1
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
        };
    };
}
2015-11-11 17:21:44.015 nscurl[60036:3294457] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fec31d9a9f0 [0x7fff7483f390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fec31d9a330 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31d970e0 [0x7fff7483f390]>"
), NSUnderlyingError=0x7fec340002b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x7fec31d9a9f0 [0x7fff7483f390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x7fec31d9a330 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31d970e0 [0x7fff7483f390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://apple.com/, NSErrorFailingURLStringKey=https://apple.com/, NSErrorClientCertificateStateKey=0}
---

---
TLSv1.0
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
        };
    };
}
2015-11-11 17:21:45.833 nscurl[60036:3294457] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x7fec31d966f0 [0x7fff7483f390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x7fec31d94210 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31d9ea00 [0x7fff7483f390]>"
), NSUnderlyingError=0x7fec31e01510 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x7fec31d966f0 [0x7fff7483f390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x7fec31d94210 [0x7fff7483f390]>",
    "<SecCertificate 0x7fec31d9ea00 [0x7fff7483f390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://apple.com/, NSErrorFailingURLStringKey=https://apple.com/, NSErrorClientCertificateStateKey=0}
---

================================================================================

Configuring PFS exceptions for apple.com

---
Disabling Perfect Forward Secrecy
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for apple.com

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for apple.com

---
TLSv1.2 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for apple.com

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================
```

**Comment by mhils** [comment] 2015-11-15 05:50
Thanks a lot, @zeaphoo!

Can somebody who is affected by this please point a random browser at mitmproxy and let me know which cipher suite is negotiated between the browser and mitmproxy? (You can see that in the browser connection info).

**Comment by zeaphoo** [comment] 2015-11-17 03:08
In ios9, chrome, open https://apple.com, got `HttpSyntaxException('Invalid headers',)`. Browser connection info shows 
```
Your connection to apple.com is encrypted using a modern cipher suite.

The connection uses TLS 1.2.

The connection is encrypted and authenticated using AES_128_GCM and uses ECDHE_RSA as the key exchange mechanism.
```
On my macbook pro, open https://apple.com (not https://www.apple.com), the connection info is same, also got the same error.

**Comment by mhils** [comment] 2015-11-17 10:24
Thanks. The invalid headers thing is unrelated and was just fixed by mitmproxy/netlib#105. AES_128_GCM and ECDHE_RSA means there's Perfect Forward Secrecy, weird to see the ATS thing fail on that.

**Comment by karlwmacmillan** [comment] 2015-12-09 16:53
I've found that this ATS works fine with mitmproxy unless you use mitmrpoxy certs generated by an older version (I was using certs generated by 0.11). If you delete ~/.mitmproxy/*.pem and restart mitmproxy things will work fine. Of course you'll have to re-add the CA cert using mitm.it.

**Comment by mhils** [comment] 2015-12-09 16:56
@karlwmacmillan ran the nscurl test suite against mitmproxy with the newer certs and everything was fine. Looks like this is fixed then. Thanks everyone for contributing, I think we can close this :smiley:

**Closed by mhils** 2015-12-09 16:56 UTC

**Comment by zeaphoo** [comment] 2015-12-10 03:24
@karlwmacmillan  great jobs.   @mhils  I ran the nscurl test suite, it works fine. (mitmpoxy version 0.15, delete ~/.mitmproxy/*.pem,  restart mitmproxy, re-add the CA cert)
```
/usr/bin/nscurl --ats-diagnostics https://apple.com -v
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://apple.com.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
ATS Dictionary:
{
}
Result : PASS
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
ATS Dictionary:
{
    NSAllowsArbitraryLoads = true;
}
Result : PASS
---

================================================================================

Configuring TLS exceptions for apple.com

---
TLSv1.2
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
        };
    };
}
Result : PASS
---

---
TLSv1.1
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
        };
    };
}
Result : PASS
---

---
TLSv1.0
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
        };
    };
}
Result : PASS
---

================================================================================

Configuring PFS exceptions for apple.com

---
Disabling Perfect Forward Secrecy
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for apple.com

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for apple.com

---
TLSv1.2 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for apple.com

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "apple.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================
```

**Comment by DineshKumar7** [comment] 2015-12-10 03:48
Hai, 
I couldn't able to access the App on connecting mitm. I am using a 3rd party app in iOS 9 device. Is it anything I should configure to make that work. Can someone please provide a solution. Thanks

**Comment by mhils** [comment] 2015-12-10 09:18
@DineshKumar7: Looks like your app is using certificate pinning: http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning

**Comment by jvillacorta** [comment] 2015-12-11 15:33
I have an implementation based on the flow basic example (https://github.com/mitmproxy/mitmproxy/blob/master/examples/flowbasic), I removed the certificates and started the proxy again.

Using mitmproxy or mitmdump, I do not have any problems with iOS9 ATS, but as soon as I try it with the flow_basic.py sample the iOS devices rejects the connection with the following error:
```
2015-12-11 10:04:56.396 sampleapp[259:9872] CFNetwork SSLHandshake failed (-9824)
2015-12-11 10:04:56.397 sampleapp[259:9872] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
```
All SSL connections without ATS work fine, I can manipulate the flow and there are no problems. Am I missing something here?

**Comment by mhils** [comment] 2015-12-11 15:38
You may need to set `ciphers_client` in the `ProxyConfig` to `libmproxy.proxy.config.DEFAULT_CLIENT_CIPHERS`. Could you quickly check if that fixes it and then send a PR that sets it as the default argument [here](https://github.com/mitmproxy/mitmproxy/blob/f446dc4b83b8d92bf7b4430d4ba62ae0d7213a17/libmproxy/proxy/config.py#L59)?

**Comment by jvillacorta** [comment] 2015-12-11 16:12
That worked. I submitted the PR.
Thanks!
