### ISSUE TITLE
twitter.com goes in timeout if HTTP2 is enabled

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#1745] opened 2016-11-14 21:57 UTC
##### Steps to reproduce the problem:

1. Intercepting twitter.com with Firefox and Chrome -> timeout after ClientConnect
Page never appears, with no error in logs

Seen on SlackFor @cortesi, for him was working on Firefox but not Chrome

##### Any other comments? What have you tried so far?
Disabling HTTP2 works directly with --no-http2

##### System information

Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64

**Comment by Kriechi** [comment] 2016-11-14 22:31
This seems to be the same bug as https://github.com/python-hyper/hyper-h2/issues/302
Even the repro script seems to work almost without modification for `twitter.com`:
```python
#!/usr/bin/env python3

import certifi
import h2.connection
import h2.events

import errno
import socket
import ssl
import time

SERVER_NAME = 'twitter.com'

socket.setdefaulttimeout(2)

c = h2.connection.H2Connection()
c.initiate_connection()

ctx = ssl.create_default_context(cafile=certifi.where())
ctx.set_alpn_protocols(['h2', 'http/1.1'])
ctx.set_npn_protocols(['h2', 'http/1.1'])

s = socket.create_connection((SERVER_NAME, 443))
s = ctx.wrap_socket(s, server_hostname=SERVER_NAME)

s.sendall(c.data_to_send())

c.prioritize(1, weight=201, depends_on=0, exclusive=False)

headers = [
    (':method', 'GET'),
    (':path', '/'),
    (':authority', SERVER_NAME),
    (':scheme', 'https'),
    ('user-agent', 'custom-python-script'),
]
c.send_headers(1, headers, end_stream=True)

s.sendall(c.data_to_send())


while True:
    data = s.recv(65536 * 256)
    if not data:
        break

    try:
        events = c.receive_data(data)
        s.sendall(c.data_to_send())
    except:
        break

    for event in events:
        print(event)
```

Running it results in stream 1 just being reset by the server:
`<StreamReset stream_id:1, error_code:ErrorCodes.STREAM_CLOSED, remote_reset:True>`

Since we had such great success last time: 
ping @fsareshwala

**Comment by fsareshwala** [comment] 2016-11-14 23:44
Thanks for the ping! I'll take a look as soon as I can.

**Comment by Kriechi** [comment] 2016-11-21 12:07
@fsareshwala any update? If you need more time to investigate, just let us know.
Thanks for the help!

**Comment by fsareshwala** [comment] 2016-11-21 14:40
I haven't been able to look at this yet unfortunately. Do you have an idea of how high priority this is? I'll be able to schedule things internally a bit better with that information.

**Comment by Kriechi** [comment] 2016-11-21 14:56
No worries! As long as we know somebody is listening at the other end we are happy 👍 

As I understand it right now, everybody using mitmproxy (with http2 enabled, which is the default) to try to browse to twitter.com with Google Chrome gets a blank page (or an error).

**Comment by fsareshwala** [comment] 2016-11-21 15:15
That's definitely no bueno. I'll take a look after I finish working on the current issue I'm handling. Thanks!

**Comment by cortesi** [comment] 2016-12-09 21:42
See https://github.com/python-hyper/hyper-h2/issues/373

**Comment by Kriechi** [comment] 2016-12-10 09:40
ping @fsareshwala 
We recently had a very similar bug with reddit.com (i.e. the Fastly CDN). And it seems they just merged a fix for this into h2o: https://github.com/h2o/h2o/pull/1136
ref #1824

**Comment by cortesi** [comment] 2016-12-11 20:19
Bumping this to next release milestone - unless upstream has a revolution, we'll be shipping the next release with http2 disabled by default. Begrudgingly, and while wagging our finger in an accusatory way.

**Comment by fsareshwala** [comment] 2016-12-12 00:32
@cortesi Is Twitter the reason you can't enable http2 by default? :(

**Comment by cortesi** [comment] 2016-12-12 01:09
@fsareshwala Not only Twitter - we have issues with some major CDNs that affect sites like Reddit as well. We'll do a bit of tutting and finger-wagging, and reassess things during the next iteration. :)

**Comment by Kriechi** [comment] 2016-12-18 12:22
Reddit seems to have deployed the fix from h2o.
mitmproxy can now successfully proxy requests for Reddit (and probably all other Fastly sites).

**Comment by chhsiao90** [comment] 2017-01-13 06:34
@fsareshwala , is that twitter http2 implementation based on netty?
If so, I could help investigate on that, and I had just found that they had similar issue recently.
Thanks!

**Comment by chhsiao90** [comment] 2017-01-13 07:11
No problem! just found that netty had similar issue and think that maybe I could help :)

**Comment by mike820324** [comment] 2017-01-18 04:43
Hi, we have also encounter a similar issue that can not connect to twitter.
https://github.com/mike820324/microProxy/issues/243

However our scenario is a bit different. The root cause of our issue is that,

>If a client first sent a HEADER frame with END_HEADERS flag set, after that sent a PRIORITY frame with the same stream id, twitter server will reply with a RESET frame.

Not quite sure whether or not it is the same root cause.

B.T.W, @fsareshwala , is the above scenario the expected behavior? Seems like it is violating the http2 rfc.
Based on the RFC section 5.1 half-close(remote),
> If an endpoint receives additional frames, other than
      WINDOW_UPDATE, PRIORITY, or RST_STREAM, for a stream that is in
      this state, it MUST respond with a stream error (Section 5.4.2) of
      type STREAM_CLOSED.


 (Or maybe I have misunderstand the RFC again.)

**Comment by Kriechi** [comment] 2017-01-20 21:30
Just for my own curiosity, and to turn a bit on @fsareshwala's thumbscrews:
How high does "failure to serve web requests" rank on the priority list in the grand scheme of things for the Twitter operations team? It has been more than 3 months now - without seeing even an acknowledgment of the error. I'm a bit puzzled, since we had such great experiences with other big organizations, who found, fixed, and deployed a patch within days...

**Comment by fsareshwala** [comment] 2017-02-17 19:29
@Kriechi I truly apologize for the delay in getting to this issue. We've been busy with some other stuff internally but rest assured that this is a major issue for us.

Just to make sure I understand the impact, does issue mean that anyone using http2 experiences twitter go into timeout when connecting or just when they use the mitmproxy implementation?

**Comment by mhils** [comment] 2017-02-17 21:11
@fsareshwala: Thanks for getting back at this!

> does issue mean that anyone using http2 experiences twitter go into timeout when connecting or just when they use the mitmproxy implementation?

This is not mitmproxy-specific - any client that sends early PRIORITY frames (in accordance with the RFCs) is affected. I know that this issue has been reported to mitmproxy and hyper-h2, but this is also going to affect all other clients that to optimize for HTTP/2 and send early PRIORITY frames.

**Comment by fsareshwala** [comment] 2017-02-21 23:41
@mhils Got it. Will post that into our internal issue tracking system and try and prioritize it as much as I can. Thanks!

**Comment by Kriechi** [comment] 2017-03-22 09:23
Happy 2^7 days anniversary! 🎉 👏 🎈 
It's been 128 days since this issue was reported and 4 weeks since the last sign of life.

We are still hoping to get this bug fixed and are waiting for acknowledgment, or any other kind information. Please let us know if you need help finding and debugging this @fsareshwala!

**Comment by fsareshwala** [comment] 2017-03-28 20:39
I'm really sorry for the late response here guys. I am trying to get this issue prioritized internally and we will get a fix in as soon as we can. Just wanted to let you know that I'm still here and monitoring it. It is important to us to get fixed. I'm sorry this isn't the best answer :(.

**Comment by Kriechi** [comment] 2017-04-29 08:58
Friendly monthly reminder. We are still getting `RST_STREAM` with `STREAM_CLOSED` errors when sending PRIORITY frames.

**Comment by fsareshwala** [comment] 2017-05-23 00:30
Just checking in to say that we still haven't been able to fix this issue on our end. We plan to get to it soon but there have been some internal projects that need to be addressed first. We're still here and listening :).

**Comment by Kriechi** [comment] 2017-06-01 08:55
@fsareshwala thanks for the update.
Can you in the mean time at least acknowledge or refute that this is an actual bug on your side?
I'm pretty confident - but I might as well be wrong and all the waiting is for nothing 😉

**Comment by fsareshwala** [comment] 2017-06-01 14:34
@Kriechi I'm pretty sure that it is a bug. We've gotten reports from another third party that they are experiencing the same issue. We definitely want to address this but there are some other projects that have taken a higher priority at the moment. I do apologize for the wait. I'll personally see to this as soon as I can.

**Comment by Kriechi** [comment] 2017-11-14 09:20
Happy 1st year anniversary! 🎉 👏 🥇 

I just verified that this bug still exists. It does. 
Increasing the character limit to 280 was probably more important than fixing a broken webserver...

**Comment by fsareshwala** [comment] 2017-11-15 17:04
Hey guys, apologies for not keeping up on this ticket. We are definitely working on this internally and will have it fixed soon. I can't give an exact timeline but it is being actually being addressed as compared to my last post.

**Comment by Kriechi** [comment] 2018-02-20 18:31
Well, "fixed soon" seems to be a rather flexible statement.

The twitter.com webserver is still in violation of the HTTP/2 protocol as defined in its RFC.

**Comment by BookGin** [comment] 2018-11-20 02:55
These websites will also timeout if HTTP2 is enabled (HTTP2 is enabled by default).

-  `yahoo.co.jp` (Alexa 35th, Nov. 2018)
- `ettoday.net` (Alexa 122th, Nov. 2018)

Tested on Moto G5 plus (Android 7.0) Chrome 69.0.3497 with HTTP/HTTPS proxy.

**Comment by Prinzhorn** [comment] 2020-10-16 08:55
I think this can be closed? Looks like all websites listed here are working by now :tada:

**Closed** 2020-10-16 16:54 UTC
Labels: area/protocols, upstream
